alphagov/publisher

README.md
Capped up GOV.UK in the README.
=> Capped up GOV.UK ('cos we mean business)

data/local_services.csv
So we can create a local transaction for this service.
Zendesk: https://govuk.zendesk.com/agent/tickets/921650
=> Add LGSL code for the Care Act 2014

app/assets/javascripts/modules/downtime_message.js, spec/javascripts/spec/downtime_message.spec.js
Update the messaging to reflect this.
cc @vinayvinay
=> Downtime messages begin at midnight the day before

app/presenters/edition_churn_presenter.rb, app/presenters/organisation_content_presenter.rb
By request from @lutgendorff 
Should also reduce timeouts on the org report, but more optimization may be needed.
=> Remove URL and add slug for new reports.

app/assets/javascripts/modules/ajax_save.js, app/assets/javascripts/modules/tab_switcher.js, spec/javascripts/spec/ajax_save.spec.js
Get a better idea of user behaviour when editing or working with editions by:
* tracking tab switches on editions as pageviews
* tracking ajax save successes and errors
=> Track edition interactions

data/local_services.csv
Adding a new LGSL code as requested by Content: https://govuk.zendesk.com/agent/tickets/986387
=> Add LGSL code 266

Gemfile, Gemfile.lock, app/views/shared/_admin.html.erb, app/views/shared/_clone_buttons.html.erb, test/integration/change_edition_type_test.rb
The body of the previous edition is copied across.
https://www.pivotaltracker.com/n/projects/1261204/stories/89923420
=> Allow users to convert published Answer editions to Simple Smart Answer editions

test/unit/answer_edition_test.rb
This test file has no tests. Remove it from the tree.
=> Delete empty `AnswerEditionTest` test file

Gemfile, Gemfile.lock
- This picks up
https://github.com/alphagov/govuk_content_models/pull/303 for
https://www.pivotaltracker.com/story/show/95556412.
=> Bump govuk_content_models to 28.7.1

app/models/area.rb
- See https://github.com/alphagov/business-support-api/pull/31.
=> Comment that the AREA_CODES list should stay in sync with Business Support API

lib/edition_tagger.rb, test/unit/edition_tagger_test.rb
Add a third column to the CSV being used to import mainstream browse
tags to indicate whether the tag should be applied as a "primary" tag
(ie, at the start of the list of browse pages, so used for breadcrumbs
on the page, or at the end of the list).
Complain if we get any value other than "TRUE", "FALSE" or unspecified
from this field, so we don't get confused when converting from the value
in the CSV to a boolean.
Needed for https://trello.com/c/QAEn1zX6/230-tag-mainstream-browse-pages-for-childcare
=> Support ordering browse_page tags when importing

test/integration/video_edition_create_edit_test.rb
We have been unable to make this particular test run reliably in
CI. See:
https://github.com/alphagov/publisher/pull/401
https://github.com/alphagov/publisher/pull/402
https://github.com/alphagov/publisher/pull/403
=> Delete entire nondeterministic failing test

app/presenters/published_edition_presenter.rb, test/unit/published_edition_presenter_test.rb
Use updated_at value if public_updated_at is nil.
cc @jamiecobbett
=> Fix publishing API presenter for unpublished items

app/workers/publishing_api_publisher.rb, app/workers/publishing_api_updater.rb
Speculative fix for `NameError: uninitialized constant PublishingAPIUpdater::Services`
=> Ensure that Services is loaded.

Gemfile, Gemfile.lock
* Redact emails from Google Analytics event labels and actions
=> Bump admin gem to 4.2.0

app/presenters/dates_report_presenter.rb, lib/tasks/export_dates_report.rake, test/unit/dates_report_presenter_test.rb
To create the report:
```
publisher$ rake export_dates_report[<start_date> (format: YYYY-MM-DD), <end_date> (format: YYYY-MM-DD)]
```
The report is produced inside `/reports`
=> Create a report for all mainstream content that was published between 2 dates

config/environments/production.rb
Publisher does not use active_record.
=> Remove mistakenly-added active_record config.

Gemfile, Gemfile.lock
=> Use version 35.0.1 of govuk_content_models

Gemfile, Gemfile.lock
[Trello card](https://trello.com/c/QEjTaHBW/408-clean-up-legacy-promo-storage)
=> Bump govuk_content_models gem to 37.0.0

app/views/shared/_tagging.html.erb
Trello: https://trello.com/c/qsABwQjf/17-publisher-style-update-tags-button
=> Style "Update tags" button

lib/local_service_importer.rb
CI was failing (with seed 34491). This should put a stop to that.
=> Fix order dependant test

Rakefile
Avoid every rake task needs the CI Reporter gem
=> Amend Rakefile

Gemfile
The Gemfile should now be alpha-sorted and relatively tidy.
No dependencies have been changed.
=> Clean up the Gemfile

lib/tasks/sync_checks.rake
Update sync checker to support other formats (for future migrated formats)
=> Update sync checker to support other formats

test/integration/edition_workflow_test.rb
Current test runs take 263s on my dev VM. This change reduces that by 50s.
=> Reduce test run time by 50s

lib/enhancements/edition.rb, test/unit/edition_test.rb
Without this preview won't link to draft stack but private frontend instead.
=> Add LocalTransaction to migrated formats for Preview

app/helpers/publications_helper.rb, app/views/shared/_metadata.html.erb, test/integration/root_overview_test.rb, test/unit/programme_edition_test.rb
This removes some panopticon-related code. This app hasn't talked to panopticon in a while, and panopticon has been retired.
https://trello.com/c/dGPNmVub
=> Remove last of panopticon

app/presenters/formats/guide_presenter.rb, app/services/edition_presenter_factory.rb, lib/enhancements/edition.rb, test/unit/edition_test.rb, test/unit/presenters/formats/guide_presenter_test.rb
Trello: https://trello.com/c/r2gA1lxN/640-migrate-guide-format-to-rendered
Paired with @emmabeynon
=> Add publishing-api presenter for Guide editions

app/presenters/formats/simple_smart_answer_presenter.rb, app/services/edition_presenter_factory.rb, lib/enhancements/edition.rb, test/unit/edition_test.rb, test/unit/presenters/formats/simple_smart_answer_presenter_test.rb, test/unit/services/edition_presenter_factory_test.rb
Tests will only pass once https://github.com/alphagov/govuk-content-schemas/pull/531 gets merged and deployed
=> Add simple smart answer presenter

Gemfile, Gemfile.lock, app/presenters/formats/answer_presenter.rb, app/presenters/formats/edition_format_presenter.rb, app/presenters/formats/help_page_presenter.rb, app/presenters/formats/local_transaction_presenter.rb, app/presenters/search_index_presenter.rb, app/services/unpublish_service.rb, lib/enhancements/artefact.rb, lib/enhancements/edition.rb, lib/tagging/linkables.rb, test/test_helper.rb, test/unit/edition_test.rb, test/unit/presenters/formats/answer_presenter_test.rb, test/unit/presenters/formats/edition_format_presenter_test.rb, test/unit/presenters/search_index_presenter_test.rb, test/unit/services/search_indexer_test.rb, test/unit/services/unpublish_service_test.rb
https://trello.com/c/jWVgYcxQ/618-investigate-unpublishing-parted-formats-with-redirects
Mobbed with @brenetic & @whoojemaflip
=> Fix unpublishing formats with parts redirects

app/presenters/formats/place_presenter.rb, app/services/edition_presenter_factory.rb, lib/enhancements/edition.rb, test/unit/edition_test.rb, test/unit/presenters/formats/place_presenter_test.rb, test/unit/services/edition_presenter_factory_test.rb
Migrate the Place format, such that it is rendered through the Publishing API.
Do not merge yet, as the merging/release of this needs to be coordinated with Frontend.
=> Migrate Place

app/presenters/formats/licence_presenter.rb, app/services/edition_presenter_factory.rb, lib/enhancements/edition.rb, test/unit/edition_test.rb, test/unit/presenters/formats/licence_presenter_test.rb
This will only pass once https://github.com/alphagov/govuk-content-schemas/pull/566 has been merged and deployed
=> Add licence presenter for new schema

Jenkinsfile
This uses alphagov/govuk-puppet#5611 to build this project.
https://trello.com/c/iDWjE1Vz
=> Use shared Jenkins build feature

app/helpers/paths_helper.rb, test/unit/helpers/admin/paths_helper_test.rb
https://trello.com/c/THjwpcKs/695-remove-cache-busting-in-frontend-and-publisher
=> Remove cache bust from preview links

lib/tasks/bulk_discard_placeholder_draft_content.rake
These are leftover data from the migration process to the Publishing API.
=> Add rake task for discarding drafts with schema_name "placeholder"

app/presenters/formats/help_page_presenter.rb, lib/enhancements/edition.rb, test/unit/presenters/formats/help_page_presenter_test.rb
this supports the template consolidation work
=> Change help rendering app to government frontend

app/presenters/formats/guide_presenter.rb, test/unit/presenters/formats/guide_presenter_test.rb
Switch rendering from frontend to government-frontend:
https://trello.com/c/uGsuRVGJ/297-penultimate-stage-re-publish-guides-to-switch-rendering-app-1
=> Switch guides rendering app to government-frontend

lib/tasks/publish_start_page_ab_test_pages.rake
For [Trello](https://trello.com/c/zfJiG9v8/145-sa-a-b-test-make-changes-to-government-frontend)
This updates the paths, titles and rake task descriptions for publishing the
Start Page A/B test content.
=> Update start page ab test content slugs

Dockerfile, config/mongoid.yml, db/seeds/user.rb
Is required for running publisher under publishing-e2e-tests.
=> Add a Dockerfile for this app

README.md
Currently used to generate the number of working days in this file
app/views/noisy_workflow/request_fact_check.text.erb
=> Add calendars to publisher README

db/seeds/user.rb
Was defaulting to saving a null value previously.  Also log message
in the event that the user already exists.
=> Explicitly set the uid of the test user.

lib/service_sign_in/file_self_assessment.cy.yaml, lib/service_sign_in/file_self_assessment.en.yaml
Add YAML files containing the English and Welsh content for the service_sign_in pages.
They will be published using the rake task created here: #668
=> Add self assessment content

lib/service_sign_in/check-update-company-car-tax.en
This is the service sign-in page content for the 'Check or update your company car tax' service. There won't be a Welsh version of this content.  
Background is in the Trello card - https://trello.com/c/IPh4orCg/303-release-company-car-tax
=> Add English content for company car tax

lib/service_sign_in/check-income-tax.en.yaml
This is the service sign-in page content for the 'Check your Income Tax for the current year' service.
There will not be a Welsh version of this content.
Part of: https://trello.com/c/CNlBsBsY/302-release-check-your-income-tax
=> Add English content for check your income tax

lib/service_sign_in/file_self_assessment.en.yaml
I've changed the text on the options from "Use XXXX" to "Sign in with XXXX". I've also removed the introductory sentence ("If you’re filing online for the first time...") and added a similar sentence as hint text under the 3rd option. 
These changes were made in response to some user feedback we'd received over the last couple of weeks.
=> Updated option and hint text

lib/service_sign_in/personal-tax-account.cy.yaml, lib/service_sign_in/personal-tax-account.en.yaml
We now have welsh translations for the new sign-in pattern.
Co-Authored-By: Rylan Gooch <rylan.gooch@digital.cabinet-office.gov.uk>
=> HUB-95: Add welsh version for the PTA sign-in page

lib/service_sign_in/check-update-company-car-tax.cy.yaml
https://trello.com/c/SsXmyXS0/1086-update-company-car-details-welsh-content-version-content-change-request
=> Create Welsh version for check or update your company car tax

lib/service_sign_in/check-income-tax.en.yaml
[Zendesk Ticket](https://govuk.zendesk.com/agent/tickets/2803860)
=> Update Government Gateway links for check-income-tax

lib/tasks/publishing_api.rake
https://trello.com/c/4mRr4Mzi/30-create-knowledge-api
=> Run rake task with `environment`

lib/service_sign_in/example.en.yaml, lib/service_sign_in/file_self_assessment.en.yaml
Requested by HMRC.
The Welsh version is not being changed just yet
as there are some issues with previous slug
changes which need to be resolved.
https://trello.com/c/ftfbgmxM/334-update-urls-in-self-assessment-start-page
=> Update HMRC self-assessment signin URL

Gemfile, Gemfile.lock, test/integration/completed_transactions_create_edit_test.rb, test/integration/edition_workflow_test.rb, test/integration/guide_create_edit_test.rb, test/integration/help_page_create_edit_test.rb, test/integration/licence_create_edit_test.rb, test/integration/local_transaction_create_edit_test.rb, test/integration/simple_smart_answers_test.rb, test/integration_test_helper.rb, test/support/govuk_test.rb
https://trello.com/c/HSY8wGK0/414-switch-publisher-from-poltergeist-to-headless-chrome
Poltergeist is unmaintained so we're replacing with the Capybara headless chrome driver.
Updates Capybara to v3.6
=> Switch to headless chrome

app/models/artefact.rb
=> Don't error when discarding drafts

lib/service_sign_in/check-state-pension.cy.yaml, lib/service_sign_in/check-update-company-car-tax.cy.yaml, lib/service_sign_in/file_self_assessment.cy.yaml, lib/service_sign_in/personal-tax-account.cy.yaml
Authors: @felixmarcusmillne @kerrr
=> EID-970: Add welsh service sign in eidas hint text

app/presenters/formats/service_sign_in_presenter.rb, lib/service_sign_in/example.en.yaml, test/unit/presenters/formats/service_sign_in_presenter_test.rb
Missed in https://github.com/alphagov/publisher/pull/962
=> Present tracking-domain attribute in service sign in presenter

.gitignore, lib/service_sign_in/check-income-tax.cy.yaml, lib/service_sign_in/check-state-pension.cy.yaml, lib/service_sign_in/check-update-company-car-tax.cy.yaml, lib/service_sign_in/personal-tax-account.cy.yaml
Also added an ignore for Intellji files in the git ignore.
=> EID-1196: Updated translations for the sign-in pages. 

lib/service_sign_in/check-income-tax.cy.yaml
https://trello.com/c/veMo9zB9/2408-check-how-much-income-tax-you-paid-last-year-welsh-version-content-change-request
CHANGED:
Creu cyfrif Porth y Llywodraeth
TO:
Creu cyfrif GOV.UK Verify 
BECAUSE:
HMRC requested change as button was inaccurate
=> Update GOV.UK Verify start button

data/local_services.csv
See https://standards.esd.org.uk/?uri=service%2F1788
https://trello.com/c/HBvlmYak/1022-adding-new-service-to-local-links-manager
=> Enable service 1788

data/local_services.csv
https://trello.com/c/AsflZ3Ce/1067-edits-to-recently-added-local-links-service
=> Change service 1788 from 'all' to 'county/unitary'

Dockerfile
As building is failing without it set.
=> Set GOUVK_WEBSITE_ROOT in the Dockerfile

lib/service_sign_in/check-income-tax.en.yaml, lib/service_sign_in/check-state-pension.en.yaml, lib/service_sign_in/check-update-company-car-tax.en.yaml, lib/service_sign_in/file_self_assessment.en.yaml, lib/service_sign_in/personal-tax-account.en.yaml
Italy will soon be connecting to the Verify eIDAS connector-node,
allowing users to sign in to services using their Italian digital
identities. We need to update the content on the sign in pages to
reflect this.
This should not be deployed to production until the connection has been
made.
=> [DO NOT MERGE] EID-1650 Update eIDAS sign in content

app/assets/stylesheets/forms.scss
These fields are not required and will result in an error if they are filled in.
[Trello Card](https://trello.com/c/FmE5xU1p/1478-3-add-new-bespoke-message-to-specific-completed-transaction-pages)
=> Hide opt in/opt out URLs for electric vehicle promo

app/presenters/formats/completed_transaction_presenter.rb
This allows it to be included in the content item and rendered on the frontend.
[Trello Card](https://trello.com/c/FmE5xU1p/1478-3-add-new-bespoke-message-to-specific-completed-transaction-pages)
=> Add electric vehicle to list of promotions

Gemfile, Gemfile.lock, app/mailers/application_mailer.rb, app/mailers/noisy_workflow.rb, app/views/noisy_workflow/request_fact_check.text.erb, config/application.rb, config/environments/production.rb, config/secrets.yml, test/functional/multi_noisy_workflow_test.rb, test/functional/noisy_workflow_test.rb, test/unit/edition_clone_test.rb, test/unit/guide_edition_test.rb
https://trello.com/c/72QJ9IBL/1877-publisher-use-notify-instead-of-ses
=> Use mail-notify gem to deliver via GOV.UK Notify

data/local_services.csv
See https://standards.esd.org.uk/?uri=service%2F1113 for more information.
[Trello Card](https://trello.com/c/h89SwLyy/1908-5-add-a-new-covid-19-volunteering-service-to-local-links-manager)
=> Add volunteering service

Gemfile, Gemfile.lock, app/mailers/application_mailer.rb, app/mailers/noisy_workflow.rb, app/views/noisy_workflow/request_fact_check.text.erb, config/application.rb, config/environments/production.rb, config/secrets.yml, test/functional/multi_noisy_workflow_test.rb, test/functional/noisy_workflow_test.rb, test/unit/edition_clone_test.rb, test/unit/guide_edition_test.rb
Reverts alphagov/publisher#1263
=> Revert "Use mail-notify gem to deliver via GOV.UK Notify"

app/mailers/noisy_workflow.rb, app/views/noisy_workflow/request_fact_check.text.erb
https://trello.com/c/EgwMYcXj/1987-3-update-publisher-interface-and-email-text-to-match-new-fact-check-workflow
=> Warn users not to remove edition id from subject header

app/views/noisy_workflow/request_fact_check.text.erb, test/integration/edition_workflow_test.rb
https://trello.com/c/jCpYumNF/2009-include-reply-to-address-in-body-of-publisher-fact-check-emails
=> Tweak fact-check email formatting

lib/fact_check_email_handler.rb, test/integration/fact_check_email_test.rb
We've configured a custom email account in integration and staging, so it's safe to run the fact check in all environments.
[Trello Card](https://trello.com/c/IspoUGnj/1971-5-enable-fact-check-emails-in-integration-and-staging)
=> Always run fact check

.rubocop.yml, app/helpers/base_helper.rb, app/helpers/editions_helper.rb, app/helpers/tabs_helper.rb, app/models/edition/tab.rb, app/views/editions/show.html.erb, app/views/root/index.html.erb
https://github.com/alphagov/rubocop-govuk/issues/73
A few manual fixes were necessary to do this. Please see the commits for more details.
=> Remove redundant RuboCop config

doc/fact-checking.md, lib/fact_check_email_handler.rb, lib/fact_check_mail.rb, script/mail_fetcher, test/unit/fact_check_mail_test.rb, test/unit/lib/fact_check_email_handler_test.rb
See individual commit messages for more detail.
Trello card: https://trello.com/c/NbgFTMR4/2022-5-alert-on-fact-check-replies-that-werent-parsed
=> Delete out of office emails and send uprocessed emails count to Graphite

lib/service_sign_in/README.md
=> Point to AWS Jenkins

lib/service_sign_in/check-update-company-car-tax.en.yaml, lib/service_sign_in/personal-tax-account.en.yaml
I missed off a sentence in the earlier update to this page.
=> Add missing line about other Verify services

test/integration/edition_workflow_test.rb
https://trello.com/c/AB5sPEMm/2121-5-handle-not-in-team-notify-error-in-mainstream-publisher
=> Add a test to ensure the not-in-team error is handled

app/lib/fact_check_email_handler.rb, app/lib/fact_check_message_processor.rb, test/integration/fact_check_email_test.rb, test/unit/fact_check_message_processor_test.rb, test/unit/lib/fact_check_email_handler_test.rb
https://trello.com/c/BNNRuF8E/980-whos-fixing-me-unprocessed-fact-check-emails
Please see the commits for more details.
=> Ignore fact check emails for deleted editions

data/local_services.csv
See https://standards.esd.org.uk/?uri=service%2F1826 for more
information.
[Trello](https://trello.com/c/gfu0Sp2q/608-set-up-a-new-service-in-local-links-manager)
=> Add Test and Trace Support Payment service

app/lib/fact_check_email_handler.rb
We already send an Icinga alert when there is a problem processing
the email: https://github.com/alphagov/govuk-puppet/blob/ce4eb1c7acc732e920e68cc1c3acdc7e5f86f9fb/modules/govuk/manifests/apps/publisher/unprocessed_emails_count_check.pp
And we log an error in Sentry:
https://sentry.io/organizations/govuk/issues/1951927797/?project=202241&query=is%3Aunresolved
We don't need to log it in Sentry too. The question is, which is
the most appropriate vehicle for notifying developers about the
error?
I would argue that it is more important for the Icinga alert to
happen, as we have 2nd line developers actively allocated to
responding to such issues. Errors logged to Sentry (currently)
languish until a developer periodically checks Sentry. Given the
sometimes urgent nature of fact checking, it is …
=> Stop logging fact check email errors to Sentry

README.md, lib/service_sign_in/file_self_assessment.en.yaml
Just the English sign in page for now, as the Welsh version of the new page isn't ready yet.
=> Redirect "Register for Self Assessment" result to URL

app/controllers/application_controller.rb
It almost certainly would not occur in production anyway but regardless we should make sure this message is only displayed for the correct cases.
=> Be more specific about the team-only error and don't display it in production

data/local_services.csv
Add COVID testing centres to the local services list
[Trello](https://trello.com/c/SV76e3D5/732-create-service-in-local-links-manager-for-local-covid-testing)
=> Add COVID testing centres service

lib/service_sign_in/help-friends-family-tax.en.yaml
This is a new service sign in page for a HMRC service.
Deploy by running the following Rake task:
```
rake service_sign_in:publish[help-friends-family-tax.en.yaml]
```
PR will remain draft for now, as we are awaiting confirmation of the URLs.
[Content change document](https://docs.google.com/document/d/1O51h7eiZkpzpeVN3IySgy_qtjRMKopJ12jMtySuSb1s/edit#heading=h.w66o3vejhzdc)
[Trello card](https://trello.com/c/TjtPl4oA)
=> Add service sign in page for /help-friends-family-tax

.github/workflows/deploy.yaml, .github/workflows/set-automatic-deploys-enabled.yaml
History of update:
https://github.com/alphagov/smart-answers/commit/bf83acfea948d1c38506202d7b65a25999a507f6
=> Updating Github actions to match the latest:

app/views/shared/_govspeak_help.html.erb
Trello card: https://trello.com/c/WbNNHNqB/764-update-publishing-apps-to-reflect-change-of-monarch
=> Change references from the Queen to the King

app/presenters/content_workflow_presenter.rb, app/presenters/dates_report_presenter.rb, app/presenters/primary_listing_presenter.rb, config/initializers/gds_api.rb, test/functional/editions_controller_test.rb, test/integration/root_overview_test.rb, test/integration/tagging_test.rb, test/unit/content_workflow_presenter_test.rb, test/unit/dates_report_presenter_test.rb, test/unit/helpers/admin/paths_helper_test.rb
Trello card: https://trello.com/c/o1PTrZUs/797-stop-using-deprecated-plek-method
=> Replace deprecated Plek.current with Plek.new

lib/service_sign_in/claim-rural-payments.en.yaml
=> Removed Verify radio button

app/models/simple_smart_answer_edition.rb, test/models/simple_smart_answer_edition_test.rb
=> AC/ACB - Add Question/Outcome number and on newline

docs/arch/adr-006-use-mermaid-for-simple-smart-answer-visualisation.md
This PR will add an ADR, that proposes we should use mermaid.js to add visualisations of simple smart answers.
This was following a review spike into the best library to adopt. 
This PR does not cover the implementation of the required behaviour, which will be raised in future PRs.
[Trello card](https://trello.com/c/FtSuDOJa/545-spike-for-decision-tree-visualisation)
=> Add ADR for using mermaid to visualise simple smart answers

docs/arch/adr-007-dont-use-asynchronous-javascript-for-simple-smart-answers.md
=> Adds ADR for SSA Ajax

app/models/simple_smart_answer_edition.rb, test/models/simple_smart_answer_edition_test.rb
=> Add answers and routing to simple smart answers history

app/assets/javascripts/smart-answers.js, app/views/simple_smart_answers/_node.html.erb
=> Consistent naming of question and outcome nodes within buttons

app/assets/javascripts/modules/smart_answer_flowchart.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/smart_answer_flowchart.scss, app/controllers/editions_controller.rb, app/views/editions/diagram.html.erb, app/views/editions/show.html.erb, config/routes.rb, package.json, test/functional/editions_controller_test.rb, yarn.lock
[Trello card](https://trello.com/c/sVv5WWXO/575-flow-visualisation-mvp-step-2-render-diagram-in-publisher)
The work in this PR adds a new view to display a flowchart for a particular Smart Answer together with other associated tasks: 
- Add a link from the simple smart answer edition view to the diagram visualisation page.
- Add new view and route
- Add a new stylesheet
- Add a new JS module
- Add mermaid as a dependency
- Add a loading message to be shown while mermaid initialises
|Page|Screenshot|
|-|-|
|Simple Smart Answer edition page - showing location of added link|![Screenshot 2023-12-18 at 10 57 24](https://github.com/alphagov/publisher/assets/6080548/5bd9a5f2-a8e4-48cc-a6a0-3b98874f034f)|
|New view rendering the associated flowchart|![Screenshot 2023-12-18 at 11 02 …
=> Create a new page for displaying SSA diagrams

app/views/layouts/design_system.html.erb
Minor design tweak requested.
[Trello ticket](https://trello.com/c/erOwzh02)
=> Increase top-padding of main content wrapper

app/controllers/downtimes_controller.rb
=> Remove link from the create downtime success message

app/views/places/_fields.html.erb
Update guidance text to reflect new name.
https://trello.com/c/HAEH2bVF/2338-rename-imminence
=> Imminence is now Places Manager

docs/arch/adr-010-ensuring-consistent-edition-state-when-unpublishing.md
[Trello card](https://trello.com/c/Vx4ZTIwU)
=> A new ADR to document a change in unpublishing

app/assets/stylesheets/application.scss, app/assets/stylesheets/popular_links.scss, app/assets/stylesheets/sidebar_components.scss, app/views/homepage/popular_links/show.html.erb
[Trello Card](https://trello.com/c/szYiEKlQ/298-enable-publishing-of-popular-links)
=> Publishing popular links - make sidebar sticky

test/unit/presenters/formats/popular_links_presenter_test.rb
Remove redundant code left with the [PR](https://github.com/alphagov/publisher/pull/2235)
=> Remove redundant code

docs/arch/adr-011-restricting-access-to-content-by-organisation.md
ADR has been approved, update the document's status.
=> Update status of ADR-011 to accepted

test/functional/editions_controller_test.rb, test/integration/edition_edit_test.rb
A few minor test name changes for consistency.
=> Make test names consistent

config/application.rb
Add secrets for notification api for dev and integration
=> Add notify key

.github/workflows/deploy_mongo_to_pg.yml
=> Update workflow to use custom workflow for test

.github/workflows/minitest.yml
To be able to run ci test for postgres, we need postgres setup in the workflow, this should hopefully set that up.
=> Add setup for postgres database

.github/workflows/minitest.yml, Gemfile, app/helpers/publications_helper.rb, app/helpers/tabbed_nav_helper.rb, app/lib/tagging/tagging_update_form.rb, app/models/action.rb, app/models/application_record.rb, app/models/artefact.rb, app/models/artefact_action.rb, app/models/edition.rb, app/models/user.rb, app/models/workflow.rb, app/presenters/filtered_editions_presenter.rb, app/views/legacy_editions/_reviewer_field.html.erb, config/application.rb, config/database.yml, db/migrate/20250212162143_create_user.rb, db/schema.rb, db/seeds/user.rb, test/functional/event_mailer_test.rb, test/functional/event_notifications_test.rb, test/legacy_integration_test_helper.rb, test/models/edition_test.rb, test/models/user_test.rb, test/test_helper.rb, test/unit/helpers/admin/publications_table_helper_test.rb, test/unit/presenters/filtered_editions_presenter_test.rb
=> P o p b migrate user

app/presenters/all_content_workflow_presenter.rb, app/presenters/content_workflow_presenter.rb, test/unit/all_content_workflow_presenter_test.rb
This applies to All Content and Published Content reports.
https://trello.com/c/uPT0R91e/
=> Append Version Number to Content Workflow Reports

test/unit/all_content_workflow_presenter_test.rb, test/unit/content_workflow_presenter_test.rb
As suggested in the PR https://github.com/alphagov/publisher/pull/2581
=> Simplify small portion of workflow presenter report tests

app/presenters/formats/answer_presenter.rb, test/unit/presenters/formats/answer_presenter_test.rb
Related PR to be merged
https://github.com/alphagov/frontend/pull/4704
Trello card https://trello.com/c/Dv4uSqX0
=> Change rendering app to frontend for Answer

data/local_services.csv
Ref Trello: https://trello.com/c/lGHQaN0h
=> Remove library services

app/views/layouts/design_system.html.erb, app/views/layouts/legacy_application.html.erb
=> Temporarily remove Maintenance banner for Publisher

app/views/layouts/design_system.html.erb, app/views/layouts/legacy_application.html.erb
The maintenance banner was not correctly commented-out.
=> Comment-out maintenance banner

.github/workflows/deploy_mongo_to_pg.yml
We want to be able to deploy publisher-on-postgres-branch to staging
=> Allow publisher-on-postgres-branch to deploy to staging

app/controllers/editions_controller.rb, test/functional/editions_controller_test.rb
=> 785 fix publisher 2i reviewer name issue

app/presenters/formats/guide_presenter.rb, test/unit/presenters/formats/guide_presenter_test.rb
- Guides are being moved to frontend in https://github.com/alphagov/frontend/pull/5028 as part of the frontend consolidation work.
https://gov-uk.atlassian.net/browse/PNP-9604
=> [PNP-9604] Update rendering app for guides to frontend
