- app/controllers/editions_controller.rb
- test/integration/root_overview_test.rb
If a user opens the “In review” list and leaves it for a while, they may come back to it and click “Claim 2i” later, eg if they’ve finished reviewing something else.
If in the meantime someone had already claimed the edition, the old behaviour would overwrite that reviewer. The old reviewer wouldn’t be notified, and the new reviewer wouldn’t know to tell them.
* Prevent claiming of 2i when there’s already a reviewer
> Don't let ‘Claim 2i’ work when an edition is already claimed

- app/controllers/notes_controller.rb
Now notes are linkable we can use the path directly, rather than prepending a hash which didn’t actually work.
> After adding notes, redirect back to notes tab

- app/assets/stylesheets/notes.scss
- app/helpers/action_helper.rb
- app/helpers/important_note_helper.rb
- app/views/shared/_edition_header.html.erb
- app/views/shared/_important_note.html.erb
- test/integration/edition_history_test.rb
* Remove important note changes from edition history, important notes don't need to be visible within an edition’s audit trail.
* When an important note has been modified, include details of who changed it and when in a table, hidden behind a toggle until it’s needed.
* Make links and zendesk tickets in important notes clickable
* Make important note content bigger and bolder
https://www.agileplannerapp.com/boards/173808/cards/9004
https://govuk.zendesk.com/tickets/898008
Prototype: https://github.com/alphagov/publisher/commit/9254fada1f72de5ae86eba8991839912817808b3#commitcomment-9174019
> Improve display of important note changes

- jenkins.sh
To ensure we have a clean state, and to prevent logfiles etc from
growing without bounds etc.
> Do a git clean before jenkins build.

- app/controllers/editions_controller.rb
- test/integration/root_overview_test.rb
Resetting the 2i user through the edit edition form would set the user to an empty string, rather than nil.
* Update logic to match that used in reviewer.html.erb
* Include what was a failing test
Fixes https://govuk.zendesk.com/tickets/923214
https://www.agileplannerapp.com/boards/173808/cards/9155
> Allow claiming of 2i when reviewer has been reset

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/modules/downtime_message.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/downtime.scss
- app/controllers/application_controller.rb
- app/controllers/downtimes_controller.rb
- app/controllers/editions_controller.rb
- app/helpers/downtimes_helper.rb
- app/helpers/editions_helper.rb
- app/views/downtimes/_form.html.erb
- app/views/downtimes/edit.html.erb
- app/views/downtimes/index.html.erb
- app/views/downtimes/new.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/javascripts/spec/downtime_message.spec.js
- test/functional/downtimes_controller_test.rb
- test/integration/downtime_test.rb
- test/unit/helpers/downtimes_helper_test.rb
www.agileplannerapp.com/boards/173808/cards/8805
As a content designer
I want a better way to indicate on start pages when a service is down for planned maintenance
So that I don't have to re-edition multiple pages and push these through workflow, then repeat the process again once the downtime is over
related:
https://github.com/alphagov/govuk_content_models/pull/277
https://github.com/alphagov/govuk_content_api/pull/209
https://github.com/alphagov/frontend/pull/728
> Downtime manager

- app/assets/stylesheets/bootstrap_and_overrides.css.scss
No modals have the “fade” class on them anymore, this reset isn’t necessary.
> Remove modal fade shim previously used in tests

- app/assets/javascripts/bootstrap_tabs_affix.js
- app/assets/javascripts/modules/tab_switcher.js
A less brittle shim is now part of the tab_switcher javascript module. See https://github.com/alphagov/publisher/commit/d6ab337dcd924445f16f2d6fd8d74228f01234ed
(Instead of removing a specific `active` class, the newer shim removes all `active` classes before Bootstrap puts it back on the now selected tab)
> Remove old bootstrap js tab shim

- Gemfile
- Gemfile.lock
- app/presenters/organisation_content_presenter.rb
Optimization to bring down the request time for the `organisation-content.csv` report.
> Use an index for sorting on the org content report.

- app/assets/javascripts/application.js
- app/assets/javascripts/modules/parts.js
- app/assets/javascripts/multi-part.js
- app/assets/stylesheets/panel_part.scss
- app/views/guides/_fields.html.erb
- app/views/programmes/_fields.html.erb
- app/views/shared/_part.html.erb
- spec/javascripts/helpers/jquery.simulate.drag-sortable.js
- spec/javascripts/spec/parts_spec.js
- test/integration/adding_parts_to_guides_test.rb
When editing part titles on new editions of published guides, the slug was auto updating. This change of slug would go unnoticed and lead to those old URLs no longer working (they redirect to the guide's first page rather than 404ing). This breaks a lot of cross-linking between editions and can take a user out of the context of what they are doing.
Change the auto slug generation behaviour to:
* only update the slug if the slug is empty or has a data attribute "accepts-generated-value"
* use this data attribute to continue auto generating slug values on first editions
* if the slug started empty (eg a new part), then all subsequent changes before saving continue to generate slugs (eg typo correction in title)
This PR also moves a lot of the parts javascript into a module with tests. It …
> Improve auto generation of slugs

- app/controllers/downtimes_controller.rb
- app/workers/expired_downtime_cleaner.rb
- test/integration/downtime_test.rb
- test/unit/workers/expired_downtime_cleaner_test.rb
https://www.agileplannerapp.com/boards/173808/cards/9233
we're using Sidekiq's `perform_at` to minimise the gap between downtime's `end_time` and the time that it gets deleted. this will ensure all information showed in Publisher related to downtimes is realtime. the other option is to use cron which will have to be run very frequently to achieve the same level of realtime. given there aren't many downtime objects running cron that frequently is not worth it.
> Delete downtime once end_time has passed

- app/assets/javascripts/modules/ajax_save.js
- app/assets/javascripts/modules/parts.js
- app/helpers/editions_helper.rb
- spec/javascripts/spec/ajax_save.spec.js
- spec/javascripts/spec/parts_spec.js
- test/integration_test_helper.rb
* When adding a new part, it would immediately display with validation errors. Remove these messages.
* Prevent loading of the ajax-save module on archived, scheduled and published editions. Neither of these can be edited so we don't need to setup all the listeners etc.
* Give better error feedback when there is a message relating to the whole form, this is a `base` error. (eg "Archived editions can't be saved")
* Prevent multiple form saves from being requested while an ajax request is in progress (unlikely from the save button as this is obscured, but a user could hit the keyboard shortcut a few times)
(Weirdly `@resource.locked_for_edits?` in content models doesn't include archived editions. Currently, and it must have been like this for a while, all form fields on archived editions …
> Improve behaviour of ajax saving

- app/views/shared/_part.html.erb
- test/integration/adding_parts_to_guides_test.rb
- test/integration/campaign_edit_test.rb
- test/integration/edition_workflow_test.rb
- test/integration/video_edition_create_edit_test.rb
- test/integration_test_helper.rb
Fix tests that were intermittently failing due to changes not being picked up before assertions, or changes happening too quickly before assertions. Specifically:
* use aria-expanded attributes to test for open/closed parts
* be explicit about saving without ajax in video and campaign tests, and avoid save message assertion which would sometimes be missed
Tests using javascript which submit a form that cannot be saved with ajax (eg campaign image upload or video caption upload) were intermittently failing. Within save_edition there was a check for a dynamic saving message. Whilst this does show, it is likely that occasionally the form would submit and the page would change before this message appeared, leading to a failing test.
Instead pull the post-save assertions out of the …
> Make ajax tests more rugged

- app/assets/javascripts/modules/collapsible_group.js
- app/views/shared/_part.html.erb
- spec/javascripts/spec/collapsible_group.spec.js
Use the events emitted by the nested form javascript to trigger changes in the link text for collapsing or expanding groups. Also remove the “if valid” check on the collapse class. All parts are shown expanded at page load, and all should be collapsible.
For example:
* When a part is added and all parts were collapsed, change text to “expand”
* When a part is removed and it was the only open part, change text to “expand”
> Alter expand/collapse text when adding/removing parts

- app/assets/javascripts/modules/tab_switcher.js
Google Analytics’s automatic detection of the current page wasn’t picking up the replaced href correctly. Instead explicitly set this when sending the page view.
https://developers.google.com/analytics/devguides/collection/analyticsjs/pages#overriding
> Tweak tab tracking to pass in tab href

- db/migrate/20141205103230_remove_expectations.rb
www.agileplannerapp.com/boards/173808/cards/8852
an [earlier story](www.agileplannerapp.com/boards/173808/cards/8707) migrated expectations to a govspeak field `need_to_know`, and this got deployed to production. so we no longer need this data in mongodb.
> Remove expectation data from mongodb

- lib/local_contact_importer.rb
- test/unit/local_contact_importer_test.rb
This was blowing up if the CSV didn't contain a URL entry for a
particular authority.
Fixes https://errbit.production.alphagov.co.uk/apps/5304e0520da11511b0000011/problems/54d057870da1156623003e96
> Fix local_contact_importer error with nil URLs

- app/assets/javascripts/modules/ajax_save.js
- spec/javascripts/spec/ajax_save.spec.js
Using keyboard shortcuts, the form could still be submitted when the save button is disabled or when it’s not visible (eg from a different tab). This behaviour was spotted via analytics events.
* Only allow keyboard shortcut to work when the save button is visible and enabled.
> Only save when the save button is visible and enabled

- app/views/layouts/application.html.erb
Keep track of the success, error and warning messages displayed to
users by using events.
* Track the alert type as the action
* Track the alert message as the label
* The page URL is captured as the event category automatically.
This will allow tracking of edition saves that happen without ajax.
> Track flash messages in analytics

- app/views/downtimes/index.html.erb
The slugs were linking to:
https://www.production.alphagov.co.uk/apply-universal-credit
Instead of:
https://www.gov.uk/apply-universal-credit
* Use the public website root, ie the GOVUK_WEBSITE_ROOT environment variable, instead of `find(‘www’)`
https://www.pivotaltracker.com/story/show/87991876
> Fix downtime slug links in production

- Gemfile
- Gemfile.lock
- app/assets/javascripts/modules/ajax_save.js
- app/assets/javascripts/modules/tab_switcher.js
- app/views/layouts/application.html.erb
- spec/javascripts/spec/ajax_save.spec.js
* Upgrade Bootstrap to 3.3.2 (via bootstrap-sass 3.3.3)
* Includes autoprefixer rails which is a new Bootstrap dependency
* Include Google analytics managed by gem https://github.com/alphagov/govuk_admin_template/pull/59
* Remove existing snippet
* Update analytics usage to match new API
https://github.com/alphagov/govuk_admin_template/blob/master/CHANGELOG.md
> Upgrade Bootstrap to 3.3.2 and manage analytics via admin gem

- Gemfile
- Gemfile.lock
- app/assets/javascripts/modules/checkbox_toggle.js
- app/views/completed_transactions/_fields.html.erb
- config/initializers/inflections.rb
- test/integration/completed_transactions_create_edit_test.rb
https://trello.com/c/caDndyIX
Completed transaction pages need to optionally show organ donor registration promotion. Form fields are stored as `presentation_toggles` on `Edition`: https://github.com/alphagov/govuk_content_models/pull/292
Checking "Promote organ donor registration" shows the URL text input:
If you've chosen to promote, entering the URL is mandatory:
> Organ donor registration on Completed Transaction

- app/controllers/application_controller.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_scheduled_publishing_test.rb
https://www.pivotaltracker.com/story/show/91500052
content designers noticed that scheduling an edition at 00:01 was showing-up as 01:01 in the publishing tool.
when the edition schedule time is submitted through the form, the `ApplicationController#squash_multiparameter_datetime_attributes` method squashes multi-parameter datetime into a single attribute before saving the field in the database. this logic was ignoring the local timezone, and made all field handling logic beyond this point think that `publish_at` field is in UTC.
using `Time.zone.local` preserves the timezone information, and fixes this issue.
also correcting the integration test that was masking this issue.
> Fix timezone conversion issues

- Gemfile
- Gemfile.lock
This version is forward-compatible with the new folder structure of
govuk-content-schemas. Upgrading will allow us to gracefully migrate to
the [new folder structure](https://github.com/alphagov/govuk-content-schemas/pull/60).
> Bump govuk-content-schema-test-helpers to 1.3.0

- app/assets/javascripts/application.js
Currently, even if a select dropdown has a blank option (`include_blank: true`), there is no way to clear the selection.
To enable this we have to specify `allowClear: true` in select2's config.
Fixes a particular problem whereby users cannot undo their "Primary topic" selection.
Note that when include_blank: false (the rails default), the clear button will not show up. Only selects where it was explicitly set will allow clearing after this commit.
> Once you've assigned a primary sub-topic to a piece of mainstream content, there's no way of getting rid of it. Where we've selected something from the drop-down in error or later realised it's not quite right, and there's no suitable alternative, we're having to assign a dummy topic that doesn't appear on the front end as a workaround. eg, …
> Allow users to clear selects with include_blank

- lib/csv_parser.rb
- lib/edition_tagger.rb
- lib/tasks/associate_editions_with_mainstream_browse_pages.rake
- test/unit/csv_parser_test.rb
- test/unit/edition_tagger_test.rb
This work is required by this [ticket](https://trello.com/c/MfDxYdta/125-tag-all-content-in-publisher-with-the-childcare-tags-using-a-data-migration). 
We need to update all content in publisher which should be tagged to childcare mainstream browse pages to have those tags.  Doing this through the publisher interface would be slow, and interfere with any existing edits in progress.
To avoid this, we will write a rake task to take a list of content and the mainstream browse pages they should be tagged to, perhaps as a CSV, and apply that to the editions in publisher.
This PR adds a rake task that associates Editions with mainstream browse pages from a CSV file.
(Tested locally with a sample CSV file)
> Associate Editions with mainstream browse pages

- app/presenters/organisation_content_presenter.rb
- test/integration/organisation_content_report_test.rb
This report was generating an error when it encountered an artefact without any
editions.
This commit doesn't address the fact that the report takes a very long time to
generate and so users aren't able to access them because nginx times out first. The solution to that is probably to generate the reports off-line.
> Fix the organisation content report

- config/environments/production.rb
We would like to offload (static file) CSV reports to be served by nginx
rather than rails. [This is possible](http://wiki.nginx.org/XSendfile) by setting
the correct header in the rails config.
The header was already set but it was configured to work with Apache, which we
no longer use.
This requires [a puppet change](https://github.gds/gds/puppet/pull/3005) to work.
/cc @alext 
The build is failing on an unrelated test (because the test relies on mongo ids increasing with subsequent insertions, as far as I can see).
> Fix static file serving to work with nginx

- app/controllers/reports_controller.rb
- lib/csv_report_generator.rb
- test/functional/reports_controller_test.rb
- test/unit/edition_churn_presenter_test.rb
Addresses the comments in https://trello.com/c/QqiFmXZ3/10-reports-in-publisher-shouldn-t-time-out-medium:
- The "weird redirect" was caused by Rails trying to send e.g. `/data/vhost/publisher.preview.alphagov.co.uk/releases/20150706083530/re
ports/organisation_content.csv` because the filename was based on `Rails.root`. Nginx is only configured to server `/var/apps/publisher/reports`, so use that as the CSV path.
- Ensure "Generated" times are displayed as Local time. This seems to be the only way to achieve this - mtime is reported as being in local time, but with a UTC offset of 0. So we have to explicitly convert this to local time, which currently means being in BST. 
- Fixes a randomly-failing test. The sort order needs to be explicitly specified in the test.
There is another …
> Fix offline generation of Publisher reports

- test/integration/video_edition_create_edit_test.rb
Using `assert_selector` makes Capybara wait for the element to appear. This should fix the not-so-random test failures
> Fix random test failures

- lib/edition_tagger.rb
- test/unit/edition_tagger_test.rb
This PR makes two main changes to the rake task which adds mainstream browse page tags to editions (`migrate:associate_editions_with_mainstream_browse_pages`):
- ensure that all non-archived editions are tagged (fixes a bug where if no edition of the document had yet been published, the edition wasn't tagged).
- republish to panopticon and the publishing-api after changing the tagging, so that search is updated correctly.
There are separate commits to make each of these changes - this is probably the easiest way to review.
> Improve edition tagger

- app/views/transactions/_fields.html.erb
- db/migrate/20150715113301_add_analytics_profiles.rb
- test/integration/transaction_create_edit_test.rb
Add a "Department analytics profile" field to transaction editions so that publishers can self serve, and migrate existing cross domain analytics (from https://github.com/alphagov/frontend/blob/d940889b5bb779ca72266c03c7458bb296e010af/app/helpers/cross_domain_analytics_helper.rb).
> As a government editor, I need to be able to add cross-domain tracking to my service start page, so that I can measure the entire user journey for my service, and measure the success of any promotional efforts for my service.
https://trello.com/c/QyHwb1Zu/
Related: https://github.com/alphagov/govuk_content_models/pull/307
> Let publishers self serve cross-domain analytics tracking

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/forms.scss
- app/helpers/editions_helper.rb
- app/views/shared/_common_edition_tags.html.erb
- test/integration/tagging_to_collections_test.rb
- test/integration_test_helper.rb
The list of tags is not orderable, but is shown during editing in the order that the tags were added. However, when the draft is saved and then re-displayed, the tags appear in alphabetical order. This has caused some confusion in the past amongst editors.
Similar solution to: https://github.com/alphagov/policy-publisher/pull/66
> Arrange mainstream browse pages in prefered order

- lib/tasks/export_local_transactions.rake
- Generates a CSV of the form "slug","lgsl","lgil","title".
- This might need to be done again in future, and across environments,
hence the rake task.
Trello: https://trello.com/c/IycgidgH/52-export-list-of-local-transaction-formats-from-publisher
> Add a rake task to generate a CSV of Local Transactions

- test/integration/campaign_edit_test.rb
- test/integration/video_edition_create_edit_test.rb
- test/integration_test_helper.rb
Attempt to improve the reliability of two integration tests (`campaign_edit_test` and `video_edition_create_edit_test`) as they fail regularly on CI.
These changes seem to make the test suite a lot more stable - Famous Last Words.
> Make integration tests more reliable

- test/integration/campaign_edit_test.rb
- test/integration/video_edition_create_edit_test.rb
The deleted areas of code seem to cause frequent test failures in CI
which is blocking deploys. A lot of time has been spent trying to
improve this already, and previous attempts have not worked (see https://github.com/alphagov/publisher/commit/3a53f28348fe7120c2aaa2d1391ea6aa73c63d66)
> Delete nondeterministic test sections

- test/integration/campaign_edit_test.rb
- test/integration/video_edition_create_edit_test.rb
Deployment is still blocked by CI failing on the master branch. Previous attempts at fixing the nondeterministic test failures:
https://github.com/alphagov/publisher/pull/401
https://github.com/alphagov/publisher/pull/402
> More nondeterministic test failure deletions

- lib/tasks/export_local_transactions.rake
- Duplicates were appearing in the output of this because it was
checking all editions and not differentiating between published and
archived editions. As per
https://github.com/alphagov/publisher/pull/398#discussion_r34978263,
display the `state` of an edition to guard against this confusion and
provide opportunities for filtering.
> Add an Edition's state to the local transaction export CSV

- Gemfile
- Gemfile.lock
This fixes a bug where Simple Smart Answers question option slugs get out of
sync with their labels, thus forcing Content team to redo questions from
scratch to get correct url slugs.
More info: https://github.com/alphagov/govuk_content_models/pull/317
> Update govuk_content_models to 29.1.1

- lib/fact_check_email_handler.rb
- script/mail_fetcher
This is an attempt to make the fact check email fetcher more robust and
more transparent. It seems like errors extending the lock time in Redis
may be causing emails to not be processed correctly and exit the loop
early, so we now rescue from the after_message hook and report errors
to Errbit.
Also added a few extra instances of Errbit logging in order to find
other errors in production.
Re: https://govuk.zendesk.com/agent/tickets/1121762
> Make Fact Check email fetching more robust

- app/views/transactions/_fields.html.erb
- test/integration/transaction_create_edit_test.rb
This label more closely matches reality. Not all services relate to a
department, and even if they do, they might be a separate profile from the
department-wide one.
I did contemplate renaming the field in the database, but it would be a lot of
work across several repos for little benefit.
> Department analytics profile => Service analytics profile

- app/views/shared/_admin.html.erb
- test/integration/change_edition_type_test.rb
This is a request from the content team. These changes are similar to the ones from #399, which converts a licence to an answer.
cc @jamiecobbett @boffbowsh 
[Trello](https://trello.com/c/siIF3DDX/83-self-serve-changing-a-simple-smart-answer-to-a-quick-answer-in-mainstream-publisher-small)
> Allow SimpleSmartAnswer to be converted to Answer

- Gemfile
- Gemfile.lock
- app/presenters/published_edition_presenter.rb
- test/unit/published_edition_presenter_test.rb
We want to use content IDs instead of slugs to represent items in curated lists, so that things like slug changes don't break the linkage. In order to do this, we need to ensure that all content in publisher has a content-id, and these content-ids are published to the publishing API.
https://trello.com/c/rmBoBPm9/290-ensure-that-all-content-in-publisher-has-a-content-id
> Send content id to content store

- Gemfile
- Gemfile.lock
- app/controllers/publications_controller.rb
See: https://github.com/alphagov/govuk_content_models/blob/bc152f7c2d1381d685c00cba1014ccf5b6f9e143/CHANGELOG.md
I did look at removing the `PANOPTICON_API_CREDENTIALS` constant, but this is
used by [gds-api-adapters directly](https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/helpers.rb#L57-L63) to authenticate with.
> Bump govuk_content_models for various fixes

- README.md
Since now Publisher is Rails 3.2.22 and `script/` is gone.
> Replace old 'script/console' by 'rails console'

- app/assets/javascripts/views/business_support/areas_relator.js
- app/controllers/editions_controller.rb
- app/helpers/areas_helper.rb
- app/views/business_supports/_areas.html.erb
- app/views/editions/areas.js.erb
- config/routes.rb
- spec/javascripts/spec/areas_relator.spec.js
- test/functional/editions_controller_test.rb
- test/integration/business_support_create_edit_test.rb
- test/unit/helpers/areas_helper_test.rb
Editors of Business Support Schemes can specify geographic areas (regions, counties, local authorities) related to a particular scheme.
Until now, this was implemented using a `<textarea>` progressively enhanced with select2. Without JavaScript enabled, an editor would need to enter a comma-separated list of the related areas' slugified names.
Using a "multiple" `<select>` instead doesn't change the JavaScript-on behaviour, but means that a user with no JavaScript can select from a list of area names.
> Use <select multiple="multiple"> for "related areas"

- app/workers/publishing_api_notifier.rb
- lib/enhancements/edition.rb
- lib/services.rb
- lib/tasks/publishing_api.rake
We have added a `content_id` for all artefacts owned by this application in https://github.com/alphagov/panopticon/pull/298
We'd like to send these documents to the content-store, to make sure the new `content_id` is in there as well (for example, https://www.gov.uk/api/content/check-register-rents).
This PR adds a rake task - `rake publishing_api:republish_content` to republish all published editions quickly. 
There's [a rake task named `reregister:all` that does the same but also for panopticon](https://github.com/alphagov/publisher/blob/master/lib/tasks/register.rake#L6). @rboulton and I decided against using that because we don't really know what the effect of the republishing will be on panopticon, and because it is very slow.
Trello: …
> Add rake task for fast republishing

- lib/republish_content.rb
- lib/tasks/publishing_api.rake
- test/unit/republish_content_test.rb
`edition.id` returns a `BSON::ObjectId` object and not a string.
When Sidekiq gets this object as an argument it calls `.to_json` on it and that will crash the `PublishingAPINotifier` because it expects a string with the ID. `BSON::ObjectId#to_s` returns the ID we want.
PR includes a simple test to verify that the `PublishingAPINotifier` can handle whatever arguments we're sending it.
Trello: https://trello.com/c/rmBoBPm9
> Fix republishing bug

- Gemfile
- Gemfile.lock
- app/controllers/editions_controller.rb
- app/helpers/areas_helper.rb
- db/migrate/20151008153331_change_business_support_edition_areas_to_gss_codes.rb
- spec/javascripts/spec/areas_relator.spec.js
- test/functional/editions_controller_test.rb
- test/imminence_areas_test_helper.rb
- test/integration/business_support_create_edit_test.rb
- test/unit/area_test.rb
- test/unit/business_support_export_presenter_test.rb
- test/unit/helpers/areas_helper_test.rb
- test/unit/lib/business_support_areas_importer_test.rb
We're working on removing BusinessSupportEdition's dependence on 'area slugs' in favour of referring to areas by their (more stable) GSS codes (http://www.ons.gov.uk/ons/guide-method/geography/products/names--codes-and-look-ups/standard-names-and-codes/index.html).
This is the new, improved attempt at adding GSS codes to these Editions. @jennyd's review of the first attempt (https://github.com/alphagov/publisher/pull/414) highlighted the need for more preparatory work, which has now been done and merged (https://github.com/alphagov/publisher/pull/418).
Since the migration involves multiple applications and gems, we've decided to first add the GSS Codes to the BusinessSupportEditions, then think about removing the current area slugs after.
I've explained the reasoning behind each change in …
> GSS codes for Business Support Editions

- db/migrate/20151012154512_rename_east_of_england_area.rb
Our MapIt doesn't recognise the "east-of-england" area, it has data for the "eastern" area instead.
This migration updates those editions that don't already use the "eastern" area to use it.
Is there a better way of doing this? E.g. a MongoDB update command I should be using and/or a better way to substitute an element in an array?
(This was originally done https://github.com/alphagov/publisher/pull/327, but that didn't update archived editions.)
> Rename "east-of-england" area to "eastern"

- app/presenters/business_support_export_presenter.rb
- db/seeds/business_support_facets.rb
- test/unit/business_support_export_presenter_test.rb
The ability to edit a Business Support Scheme's `locations` seems to've been
removed in https://github.com/alphagov/publisher/pull/212, when it was replaced
with Imminence `areas`. (Since Imminence areas are more easily searchable by
postcode.)
The only place this was still being used was the
BusinessSupportExportPresenter, which is used to produce the Business Support
Schemes CSV report (served at https://publisher.publishing.service.gov.uk/reports/business_support_schemes_content).
> Remove references to Business Support Locations

- app/helpers/areas_helper.rb
- app/models/area.rb
- test/imminence_areas_test_helper.rb
- test/unit/area_test.rb
At the moment on master visiting the edit page for any business support edition [errors with `ArgumentError: comparison of NilClass with String failed`](https://errbit.preview.alphagov.co.uk/apps/5304e0470da1152df9000004/problems/563b6a1d65786306a12e0500), which is caused by trying to sort an array of GSS codes which contains a `nil` as well as strings. This was introduced by https://github.com/alphagov/publisher/commit/86b5a5ee2a82a71bbe4c4d253c28987fb219b8ec.
The `nil` is for a [fake `England` region](https://github.com/alphagov/imminence/blob/1295ff3c5b6caeb2a16f24d34165c369b237ef03/lib/mapit_api.rb#L48-L50) which Imminence adds to the regions returned by MapIt, and no GSS code is included in that region's data. That region already doesn't work as intended (it isn't in MapIt so it's …
> Exclude areas without GSS codes

- app/controllers/editions_controller.rb
- app/helpers/editions_helper.rb
- app/views/shared/_admin.html.erb
- app/views/shared/_clone_buttons.html.erb
- lib/enhancements/edition.rb
- test/integration/change_edition_type_test.rb
This will allow the authentication token to be passed through and
therefore fix the form.
Instead of Edition.subclasses, I am now using the list of formats provided in govuk_content_models, so that all formats are available and loaded when needed by the select tag in the view.
cc @benilovj
[Trello](https://trello.com/c/p7wzEHo0/79-self-serve-changing-a-format-to-any-format-in-mainstream-publisher-medium)
> Use Rails form helper for conversion form

- lib/local_authority_interaction_ghost_detector.rb
- lib/tasks/check-for-ghosts.rake
- test/unit/lib/local_authority_interaction_ghost_detector_test.rb
The CSV of interactions from local.directgov includes a complete list of all interactions in their database.  Those that have been deleted are marked with an "X" instead of a URL.  Our importer handles this to add/remove/update our DB so it mirrors this file.  However, we've noticed lots of "ghost" interactions where we have a record of an interaction that does not appear in the CSV file.  This shouldn't happen, but it does.  While we get to the root of the problem this rake task allows us to generate a CSV of all interactions that are in our DB but not in the CSV.
We iterate over all the local interactions stored against all the local authorities in our DB and so-doing we can detect 3 types of ghost:
* interaction_in_input_to_be_deleted - any interaction that still lives in our DB but is …
> Add rake task for detecting "ghost" interactions

- lib/tasks/check-for-ghosts.rake
- lib/tasks/local_transactions.rake
The current process to import local transactions from [http://local.direct.gov.uk/Data/](http://local.direct.gov.uk/Data/local_authority_service_details.csv) does not check to see if existing entries in our database have been removed from the CSV.  This has resulted in a number of "ghost" entries which could still be visible in GOV.UK.
I have added the `local_transactions:fetch_and_clean` task to perform the import as before, but then
subsequently run the `check_for_ghosts:remove` task to do the clean up.
The `check_for_ghosts:remove` task also now aborts if it fails checks.  This is to ensure that a run failure results in a non-zero return code that will be picked up in the monitoring software.
@jennyd has changed `schedule.rb` in deployment to call the new rake task. …
> Created new rake task to import local transactions and remove ghosts

- Gemfile
- Gemfile.lock
- lib/local_contact_importer.rb
- test/unit/local_contact_importer_test.rb
This is part two of https://trello.com/c/td7NzjPG/261-use-local-authority-home-page-url-when-we-don-t-have-a-matching-transaction
There is a PR on frontend that uses this newly imported attribute in the "we matched your postcode to an LA but don't have a service endpoint for it" case (see: https://github.com/alphagov/frontend/pull/914).
> Import Home page URL from local contact csv

- app/models/area.rb
- test/imminence_areas_test_helper.rb
- test/unit/area_test.rb
They have their own special area type in mapit (COI) so we have to add
it to the list.  Also we update the comment pointing out the other
places that this list needs to be synchronized with.
For: https://trello.com/c/BI5QN49V/308-add-isles-of-scilly-council-to-the-related-areas-tag-available-in-publisher-imminence-3
This doesn't live on it's own, it will not work unless we also merge / deploy: 
* https://github.com/alphagov/imminence/pull/126
* https://github.com/alphagov/business-support-api/pull/34
> Allow Isles of Scilly in tags

- test/integration/business_support_create_edit_test.rb
On leap day `1.year.ago(Date.today)` and `1.year.since(Date.today)` land
on the 28th, not the 29th.  This means the tests that change the year
on the form to `Date.today.year` fail because they expect `Date.today`,
but actually get `Date.yesterday`.  We avoid this by recording a new
value for "today" based on calling `1.year.since` on the
`1.year.ago(Date.today)` value and then using that "today" to get the
`1.year.since` for the future value.
> Avoid leap day failures in integration specs

- config/initializers/mapit.rb
This will make the app use the environment specific Mapit meaning that we don't have to override this file in alphagov-deployment.
It will also change Publisher so that it uses Mapit over HTTPS rather than HTTP.
> Use Plek to find Mapit

- .gitignore
The following rake tasks generate CSV reports which git doesn't need to know
about:
- rake check_for_ghosts:remove
- rake check_for_ghosts:run
- rake local_transactions:fetch_and_clean
> Exclude local transaction import "ghost" csvs from git

- config/environments/production.rb
- config/mongoid.yml
Use a single MONGODB_URI env var, and fix a deprecated setting in the production environment file.
> Fix settings after Rails upgrade.

- Gemfile
- Gemfile.lock
We are going to need the most recent versions of these gems in upcoming pull requests.
cc @MatMoore @jackscotti
> Update govuk_content_models & gds-api-adapters

- app/presenters/edition_links_presenter.rb
- app/workers/publishing_api_publisher.rb
- lib/tasks/publishing_api.rake
- test/unit/edition_links_presenter_test.rb
- test/unit/publishing_api_publisher_test.rb
- test/unit/republish_content_test.rb
Ticket: https://trello.com/c/Cx3K3y8I/544-publisher-migration-publisher-should-send-links-to-publishing-api-on-publish
Part of: https://trello.com/c/nGta782z/525-epic-migrate-publisher-to-the-new-tagging-infrastructure
Paired on this with @MatMoore.
cc: @tijmenb @mobaig @Davidslv @bishboria
> Save links to publishing-api on publish

- app/presenters/edition_links_presenter.rb
- test/unit/edition_links_presenter_test.rb
When we started sending links to the publishing api, we missed
the parent link. This is used for the breadcrumb in mainstream browse and is
always the first tagged browse page.
https://trello.com/c/B8J0eOkm/561-send-parent-mainstream-browse-page-from-publisher
> Send parent mainstream browse to publishing api

- lib/tasks/publishing_api.rake
We introduced this task to migrate the tags to the publishing-api.
However, the [rake task in panopticon](https://github.com/alphagov/panopticon/blob/ae5426fcebe457ad7d6fa6f9eb74666c1762ab94/lib/tasks/migrate_taggings.rake) is actually more suited for this task because it also sends the `organisation` taggings. Panopticon and Publisher share a database, so we can use the task. 
cc @MatMoore
> Remove rake task to republish all tags

- app/controllers/editions_controller.rb
- test/integration/completed_transactions_create_edit_test.rb
- It was reported that new done pages failed to save when adding the
organ donation promo to them.
> Fix a bug with setting the transaction done page promos

- app/controllers/reports_controller.rb
- app/presenters/content_workflow_presenter.rb
- app/views/reports/index.html.erb
- config/routes.rb
- lib/csv_report_generator.rb
- test/unit/content_workflow_presenter_test.rb
This PR is aimed at producing a Content Summary and Workflow history report that will offer Content Delivery Managers  better insights into the flow of work through Publisher, 
This report will be listed and accessed via this [url](https://publisher.publishing.service.gov.uk/reports)
This CSV report comprises of the following columns:
- Content title
- Content slug
- Content URL
- Current status
- Format
- Current assignee
- *** Timestamps for each request type during the workflow ***
> Content Summary and Workflow History report

- Gemfile
- Gemfile.lock
- Rakefile
- bin/bundle
- bin/rails
- bin/rake
- config.ru
- config/application.rb
- config/environment.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/routes.rb
The rails-upgrade branch has been merged back to master and released, so switching back to that.
Also bring Rails ancillary files up to date after upgrade.
> Switch back to released version of content_models

- app/assets/stylesheets/forms.scss
- app/controllers/editions_controller.rb
- app/views/completed_transactions/_fields.html.erb
- test/integration/completed_transactions_create_edit_test.rb
- This allows us to have mutually exclusive EITHER "organ_donor" OR
"register_to_vote" OR "none" built-in, as radio buttons only allow one
selection at once.
- If "none" is selected, the URL field doesn't appear.
A PR on frontend to understand these changes is open as alphagov/frontend#942
> Change the done page promo checkbox to radio buttons, to add a new one

- lib/local_interaction_importer.rb
The Isles of Scilly have a [unique area type in MapIt, `COI`](http://mapit.mysociety.org/areas/COI.html). It's an [unusual
local authority](https://en.wikipedia.org/wiki/Isles_of_Scilly#Local_government) but is most similar to a unitary authority - [Cornwall doesn't
cover it](http://mapit.mysociety.org/area/2250.html) so this is the [only local authority which covers the islands](http://mapit.mysociety.org/postcode/TR210LB.html).
Frontend [already treats COI as unitary](https://github.com/alphagov/frontend/blob/3b12a066f0787f9a926912becf04a8b440792f12/lib/location_identifier.rb#L11), so users get redirected to the right
page for local transactions, but the [results page for district-level local
transactions](https://www.gov.uk/pay-council-tax/isles-of-scilly) is incorrectly rendered at …
> Fix Isles of Scilly for district-based local transactions

- .gitignore
- Gemfile
- Gemfile.lock
- app/workers/panopticon_reregisterer.rb
- app/workers/publishing_api_publisher.rb
- app/workers/publishing_api_republisher.rb
- app/workers/publishing_api_updater.rb
- app/workers/worker_base.rb
- test/integration/request_tracing_test.rb
- test/integration_test_helper.rb
https://trello.com/c/Eddv2AiS/688-for-migrated-formats-update-for-request-tracing
This change makes it so that a `request_id` is passed into Sidekiq jobs so that we can send this as a header downstream, via `GdsApi::GovukHeaders`. Currently, this header is lost when the Sidekiq jobs run because they run in a separate process to the one in which the request was processed.
This is based on this pull request: https://github.com/alphagov/whitehall/pull/2567
> Worker request tracing

- db/migrate/20160505130158_fix_gss_codes_for_some_councils_in_existing_support_schemes.rb
- Following on from frontend PR 948, we had to edit existing Business
Support Editions so that they would refer to the correct GSS codes
from the new data in MapIt, not the old ones that no longer worked.
This migration does just that, replacing the old GSS codes in the
edition's `area_gss_codes` array with the new ones. The councils
edited are: Northumberland, Gateshead, East Hertfordshire and
Stevenage.
- We had to skip callbacks that checked for archived Artefacts in
Panopticon, and skip validations that said that already published
editions couldn't be edited.
> Fix GSS codes for some councils in existing Business Support editions

- README.md
We add extra information about the dependency on MapIt and the need to have valid MapIt data loaded. Publisher only uses MapIt in the `LocalInteractionImporter` class.
> Update the README with MapIt information

- db/migrate/20160527152831_unset_local_authority_contact_details.rb
- lib/local_contact_importer.rb
- test/unit/local_contact_importer_test.rb
Stop importing local authority contact details, and delete the existing contact details. We already don't use most of them and are stopping using the contact URL now. We're also [archiving the unused local authorities API](https://github.com/alphagov/govuk_content_api/pull/245) which exposes the contact details.
This is the third in a series of PRs to remove local authority contact details, and the first two should be merged and deployed before this one:
- https://github.com/alphagov/frontend/pull/962
- https://github.com/alphagov/govuk_content_api/pull/245
https://trello.com/c/asuAAsR6/399-delete-code-related-to-local-authority-contact-details
> Remove local authority contact details

- db/migrate/20160622135527_remove_organ_donor_legacy_data.rb
We no longer want to provide the api for accessing organ donor
registration promotions directly and we also don't want the presentation
toggles storage to store this promote differently.  This migration
removes all the organ donor registration promotion data and re-saves it
in the promotion choice hash instead.  We also make sure that all the
done pages have the new promotion choice hash in presentation toggles so
that everything is consistent.
Corresponding PRs:
https://github.com/alphagov/govuk_content_models/pull/387
https://github.com/alphagov/frontend/pull/972
https://github.com/alphagov/govuk_content_api/pull/248
[Trello card](https://trello.com/c/QEjTaHBW/408-clean-up-legacy-promo-storage)
> Migrate organ donor registration promotion data

- data/local_services.csv
- db/migrate/20160621120231_fix_incorrect_lgsl_code_in_archived_local_transaction_edition.rb
- lib/local_service_cleaner.rb
- lib/tasks/local_transactions.rake
- test/unit/lib/local_service_cleaner_test.rb
For: https://trello.com/c/bXJG1RU8/401-investigate-and-fix-data-discrepancies-3
We want to use the local_services.csv as an indicator of which LGSL codes are actually used by GOV.UK documents.  To this end we remove all rows from it that are not currently used by a local transaction and provide rake tasks to clean up the now "orphaned" instances that would be left in the DB.
There's also a db migration which should be run before the rake task to fix the LGSL code used in an archived edition.
See the individual commits for a more verbose description of why we're doing this.
> Reduce local services to only those in use

- data/local_services.csv
- `LocalTransactionEdition.where(state: "published").to_a.map(&:lgsl_code).sort`
and
https://github.com/jennyd/ldg-mappings/blob/master/source_data/govuk-local-transactions.csv
helped us find Local Transactions on GOV.UK that we actually still
use. We should tidy up and remove the ones we don't use from this
file, so they don't get reimported into Local Links Manager as they
don't need to be.
Trello: https://trello.com/c/G8GfEDcH/424-disable-services-in-local-links-manager-that-are-actually-licences.
> Make the local_services.csv only contain transactions we use

- data/local_services.csv
We currently use LGSL 230 to refer to sheltered housing, however this is from the Scottish list and is not supported in England and Wales.  107 seems like a better bet for us, also because it refers to sheltered housing more generally, as opposed to just for older people.
As a first step, we'll add 107 as an enabled service.
There is other work that needs to be done as part of this, and this is coordinated via [this Trello card](https://trello.com/c/Zb42F6Jq/417-switch-local-transaction-for-apply-for-sheltered-housing-from-one-lgsl-to-another-3).  Once that work is done, we can retire 230.
> Add LGSL 107 as first step of replacing 230

- data/local_services.csv
- db/migrate/20160719141858_change_lgsl_230_to_107_on_local_transaction.rb
LGSL 230 is being retired in favour of LGSL 107 which was added in a previous commit.
We're waiting until we've done the rest of the shuffling steps in https://trello.com/c/Zb42F6Jq/417-switch-local-transaction-for-apply-for-sheltered-housing-from-one-lgsl-to-another-3 before removing 230 from the CSV.  This means that we will no longer import URLs for LGSL 230 from Local Direct Gov. 
We'll then run the migration to change the LGSL code on the LocalTransactions from 230 to 107 (which we are still importing)
We'll then run the `local_transactions:remove_old_services` task to clean up
> Retire LGSL 230 (sheltered housing) in favour of LGSL 107

- db/migrate/20160805145635_remove_local_interactions.rb
The commits after this migration removed the LocalAuthority model
entirely so this migration can no longer run successfully.  The next
migration also removes the local_authorities collection so the work
this migration does is superceded by that migration.  Commenting out
the broken reference to LocalAuthority seems like the best approach
to making it runnable.
> Make 20160805145635_remove_local_interactions.rb runnable

- app/presenters/organisation_content_presenter.rb
- test/unit/organisation_content_presenter_test.rb
[Trello card](https://trello.com/c/MFIzBBFZ/23-add-new-fields-to-publisher-export)
Titled as 'format' because that's what's shown in panopticon. We want to make this information available in the publisher reports so that it's still available when panopticon is retired.
TODO:
> Add 'kind' column to generated report

- test/imminence_areas_test_helper.rb
For: https://trello.com/c/PKAohBzb/468-stop-adding-slugs-to-areas-returned-from-mapit-by-imminence-2
Imminence will shortly stop providing slugs for areas in it's api
responses.  Happily we don't rely on them, but we update our test
fixtures so that it doesn't look to future developers that slugs are
valid bits of data.
See https://github.com/alphagov/imminence/pull/136 for the imminence change
> Stop relying on slugs for areas in imminence API responses

- Gemfile
- Gemfile.lock
- app/controllers/editions_controller.rb
- app/views/simple_smart_answers/_fields.html.erb
- test/integration/simple_smart_answers_test.rb
As requested in this [Trello card](https://trello.com/c/CUe4odRB/45-make-start-now-editable-in-simple-smart-answers), the need to add the capability to change the text of the start button for simple smart answers.
Here, I have added a new form attribute "start_button_text"
Also included are integration tests that ensure that this start button text is rendered on the SimpleSmartAnswerEdition form page.
This PR is related and/or dependent on the changes made to the following:
* [Content Models](https://github.com/alphagov/govuk_content_models/pull/383)
* [Content API](https://github.com/alphagov/govuk_content_api/pull/242)
* [Frontend](https://github.com/alphagov/frontend/pull/950)
SEE Trello ticket
> Add capability to change start button text on Simple Smart Answer page

- db/migrate/20160901083027_remove_unused_collections.rb
These collections are old and redundant so we'll clean them up.
They last had documents added in Feb 2012 at the latest and we can't find any reference of them being used now.
[Trello card](https://trello.com/c/2NFVxE0F/472-clean-up-old-unused-collections-in-shared-database-3-2)
> Remove unused collections in shared database

- lib/tagging/linkables.rb
- test/support/tag_test_helpers.rb
https://errbit.publishing.service.gov.uk/apps/5304e0520da11511b0000011/problems/57d7ed6c6578636cf0a40100
Publisher is erroring due to a redirected browse page which now has a nil title. So filter out items with nil titles.
> Filter out Linkables with nil titles (eg. redirects)

- app/presenters/published_edition_presenter.rb
- test/unit/published_edition_presenter_test.rb
The final objective is storing and retrieving them from the content-store.
This PR needs to be merged first: https://github.com/alphagov/govuk-content-schemas/pull/392
Ticket: https://trello.com/c/rDKC4sLm/133-send-related-external-links-to-pub-api-from-publisher
Part of: https://trello.com/c/mOeDK914/107-epic-related-links-and-panopticon
> Send external related links to publishing api

- app/presenters/search_payload_presenter.rb
- app/services/search_indexer.rb
- lib/edition_slug_migrator.rb
- lib/enhancements/edition.rb
- lib/mainstream_slug_updater.rb
- lib/published_slug_registerer.rb
- lib/registerable_edition.rb
- lib/services.rb
- lib/tasks/panopticon.rake
- lib/tasks/rummager.rake
- test/integration/edition_scheduled_publishing_test.rb
- test/integration/request_tracing_test.rb
- test/test_helper.rb
- test/unit/edition_slug_migrator_test.rb
- test/unit/edition_test.rb
- test/unit/lib/mainstream_slug_updater_test.rb
- test/unit/lib/published_slug_registerer_test.rb
- test/unit/search_indexer_test.rb
Previously this app would send documents to Panopticon in order to have
them added to the search index. This flow is now being simplified so
that all apps send documents to Rummager directly.
This commit adds:
- a presenter to form the payload required by Rummager. The payload now
includes the following extra attributes: publishing_app, rendering_app
and content_id.
- an indexer service object to handle the actual sending.
- updates across codebase and test suite wherever interaction with
panopticon takes place.
search-admin result before:
search-admin result after:
> Send documents to Rummager directly

- app/views/shared/_tagging.html.erb
- lib/tagging/tagging_update_form.rb
- test/integration/tagging_test.rb
- test/support/tag_test_helpers.rb
- test/unit/tagging/linkables_test.rb
Trello: https://trello.com/c/tSuV5leL/192-add-publishing-organisation-to-mainstream-publisher
> Add possibility to tag organisations

- lib/tasks/rummager.rake
All other repos that perform document indexing directly via Rummager have rake
tasks called `rummager:index`. The intent of this change is to keep things
consistent.
> Rename index_all task to index

- Gemfile
- Gemfile.lock
- config/initializers/gds_api.rb
Update to the latest version, particularly as we've updated the
Panopticon adapter to stop handling search-related attributes (see
alphagov/gds-api-adapters#592).
> Update gds-api-adapters to 36.4.0

- app/controllers/editions_controller.rb
- app/views/shared/_related_external_links.html.erb
- test/integration/tagging_test.rb
This makes impossible to save without having added new external related links. 
Different approach the one proposed that was hiding/showing the save button based on the addition of external links (with JS).
This works updates the copy of the buttons too. Wasn't very clear.
> Bugfix: do not crash when trying to save an unmodified item

- app/controllers/root_controller.rb
- app/controllers/user_search_controller.rb
- app/helpers/base_helper.rb
- app/helpers/editions_helper.rb
- app/views/root/index.html.erb
- app/views/user_search/index.html.erb
- test/integration/root_overview_test.rb
- test/integration/user_search_test.rb
- test/integration_test_helper.rb
While doing discovery on migrating publisher formats to the new
world of publishing-api it became clear it'd be nice to filter the
index to show only one specific format.  Mostly for when we want
to find an example of a format.  This might be useful for others.
Only poked this a bit on dev, not sure if it needs to be more robust in the face of other controllers that share this functionality.
> Allow filtering by format in the edition list index

- config/initializers/gds_api.rb
- config/initializers/gds_api_adapters.rb
- lib/tagging/link_set.rb
- test/integration/tagging_test.rb
The gds_api.rb initializer is overwritten on deploy by [files from alphagov-deployment](https://github.gds/gds/alphagov-deployment/blob/master/publisher/initializers_by_organisation/integration/gds_api.rb)
These files in alphagov-deployment don't have the `always_raise_for_not_found`
configuration set.  This means that it's only used in dev.  I recently tried
to create a new `Artefact` in Panopticon in dev (which worked), but I was
subsequently unable to edit the created `Edition` in Publisher as Publishing-api
returned a 404 for `Services.publishing_api.get_links` on it.
Production environments are currently unaffected, but if we fix the
alphagov-deployment files to also have this configuration before this fix is
merged we'll be unable to edit `Editions` on newly created `Artefacts`.
The …
> Really use GdsApi.config.always_raise_for_not_found

- Gemfile
- Gemfile.lock
- app/helpers/edition_activity_buttons_helper.rb
- app/views/noisy_workflow/_skip_review.text.erb
- app/views/shared/_workflow_buttons.html.erb
- lib/enhancements/edition.rb
- test/integration/skip_review_test.rb
Part of https://trello.com/c/r7YfHVzG/282-add-force-publish-to-mainstream-medium
Mainstream content in review can be transitioned to ready by users with the correct signon permissions for the purposes of publishing an urgent update to content where normal 2i workflow is not practical or expedient.
This effectively allows a permitted user to publish their own content without review.
Skip review button presented to permitted users:
Skip review comment dialogue:
> Add 'skip review' workflow

- app/helpers/edition_activity_buttons_helper.rb
- app/views/shared/_review.html.erb
- test/integration/skip_review_test.rb
https://trello.com/c/r7YfHVzG/282-add-force-publish-to-mainstream-medium
The original story for this feature mentioned placing the button within
the review buttons visible when viewing another editor's work when in
review. The skip review feature should mean that an author with the correct
permissions can skip the review stage of their own work which means the
relevant button needs to appear when the user is viewing their own work.
> Skip review button should be available permitted authors of content

- Gemfile
- Gemfile.lock
https://github.com/alphagov/govuk_content_models/pull/400 fixes an issue that prevented the worker process from starting up in development mode.  
This updates to the new content models patch version that contains the fix.
> Update govuk_content_models to 4.1.1

- Gemfile
- Gemfile.lock
- config/initializers/gds_api_adapters.rb
- lib/tasks/send_content_ids_for_needs_to_publishingapi.rake
- Bump GDS API Adapters to v38.0.0 to use the new Need API adapter to
return content_ids for needs. It complained at the lack of
`GdsApi.config`, because the config option has been removed because
now the behaviour it was referring to is the default, so remove the
file.
Trello: https://trello.com/c/jywEoQ1M/8-import-existing-need-information-from-publisher-into-publishing-api
> Send need_ids as content_ids to the Publishing API in the links hash

- lib/tasks/send_content_ids_for_needs_to_publishingapi.rake
- We were instantitating a new one without a token and it was working
fine in dev, but it failed on Integration, so use the already set up
`Services.publishing_api` for it, adjusting the timeout option as before.
> Fix the needs Rake task authenticating with the Publishing API

- app/presenters/published_edition_presenter.rb
- test/unit/published_edition_presenter_test.rb
Language is set on the artefact by Panopticon, and we should use it for
the content item instead of saying everything is English.
https://trello.com/c/KoJ833G9/591-fix-locale-welsh-publisher-content-in-publishing-api
> Set locale correctly in content item

- app/presenters/published_edition_presenter.rb
- test/unit/published_edition_presenter_test.rb
Reverts alphagov/publisher#521
Unfortunately the way that Publisher currently saves items causes Publishing API to be unable to republish items as it sees them in a 'draft' state. Further work needs to be done to rectify this.
> Revert "Set locale correctly in content item"

- app/presenters/published_edition_presenter.rb
- test/unit/published_edition_presenter_test.rb
- Send the right routes to the publishing api.
[Trello card](https://trello.com/c/sZyeX2Ul/570-preparatory-work-fix-content-item-routes-for-publisher-formats-3)
> Send the right routes to the publishing API

- app/views/campaigns/_image_upload.html.erb
GDS API Adapters returns a hash response, however the image upload view accessed this as if it were an OpenStruct, and so editing campaigns would break. This fixes the view.
Trello: https://trello.com/c/dhivh7TF/593-fix-campaigns-in-publisher
> Fix image upload view to handle GDS API Adapters response

- Gemfile
- Gemfile.lock
- test/integration/campaign_edit_test.rb
GDS API Adapters now returns a hash response.  This updates the campaign edit tests to reflect this.
We also bump govuk_content_models to the latest version.
> Update campaign edit tests to refect GDS API Adapters response

- app/controllers/editions_controller.rb
- app/views/shared/_related_external_links.html.erb
When the related external links were first moved from panopticon into this application, the sidebars on the site were populated from the content-api. This has been changed to the content store.
This means that the "save" action on the related external links tab will no longer have an immediate effect. Instead, the user has to republish the edition to make it visible on the site.
This adds two notes to the UI to make this clear.
https://trello.com/c/71hfUPZA
> Clarify when external related links are published

- app/workers/publishing_api_publisher.rb
- test/unit/publishing_api_publisher_test.rb
This is necessary when publishing Welsh content (ie with locale 'cy') via the PublishingAPI. The publish command defaults to using the 'en' locale so we set it here explicitely
Tested successfully on Integration with Welsh and English content
> Set locale when publishing with PublishingAPI

- app/helpers/publications_helper.rb
- app/views/shared/_metadata.html.erb
The current user journey to add or edit related links was sending users
through Panopticon and then they would see the functionality had moved
to Content Tagger.
This commit aims to be easier for users to identify where they need to
go and send them directly to the place they need.
Trello: https://trello.com/c/1PBuV84e/418-link-to-content-tagger-from-mainstream-publisher
> Improve UI for edition metadata

- app/controllers/editions_controller.rb
- app/helpers/tabs_helper.rb
- app/models/routable_artefact.rb
- app/services/remove_from_search.rb
- app/services/unpublish_service.rb
- app/views/root/index.html.erb
- app/views/shared/_unpublish.html.erb
- config/routes.rb
- test/integration/unpublish_test.rb
- test/support/tab_test_helpers.rb
- test/test_helper.rb
- test/unit/remove_from_search_test.rb
- test/unit/routable_artefact_test.rb
- test/unit/services/unpublish_service_test.rb
- test/unit/tabs_helper_test.rb
This adds unpublish (fomerly know as 'withdraw') functionality to Publisher.  This functionality is copied from Panopticon, where it is soon to be deleted.
It's 'old world' publishing platform, in that it expects to be managing routes and
Rummager content itself, rather than letting the publishing-api manage them.
When we move the mainstream formats to a new Schema (soon!) we will need to revisit
this to stop it from speaking to the router-api and rummager directly.
Trello: https://trello.com/c/xM4HRRYt/574-preparatory-work-moving-withdrawing-functionality-into-publisher-5
Paired with @whoojemaflip
> Add Unpublish tab to the edition editor

- app/controllers/application_controller.rb
- app/controllers/editions_controller.rb
- app/controllers/publications_controller.rb
- lib/enhancements/edition.rb
- test/functional/editions_controller_test.rb
- test/functional/publications_controller_test.rb
- test/integration/request_tracing_test.rb
- test/unit/edition_test.rb
This commit aims to solve the following problems:
- Publisher creating a draft content item in PublishingAPI after making a 'publish' request to PublishingAPI
- Publisher sending the wrong content to PublishingAPI before a 'publish' request
- Publisher sending multiple redundant 'put_content' requests as part of its Edition-related workflow
Before this commit, the Edition model had an after_save hook that would make a 'put_content' request to PublishingAPI each time an Edition was saved. This would happen multiple times per state change for an edition (see workflow.rb) due to the state machine and extra calls to record users (see denormalize users). Since in the PublishingAPI we do not yet model the Publisher workflow, doing a put_content for these state changes is redundant, however it …
> Move publishing api calls to controllers

- app/controllers/artefacts_controller.rb
- app/views/artefacts/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_edition_header.html.erb
- app/views/shared/_metadata.html.erb
- app/views/shared/_unpublish.html.erb
- config/routes.rb
- lib/enhancements/artefact.rb
- test/integration/add_artefact_test.rb
- test/integration/edit_artefact_test.rb
This is functionality that is being deprecated from Panopticon.
It adds a new task to the main menu 'Add Artefact', as well as providing
a view to edit (draft) artefact parameters.
> Add the ability to create and edit Artefacts

- app/presenters/search_payload_presenter.rb
- test/unit/search_indexer_test.rb
This change will also publish the Content Store Document Type to Rummager, so that we can filter by Document Type in searches.
Trello: https://trello.com/c/M1cXENeB/341-add-content-store-document-type-to-all-guidance-content-in-rummager
> Register content store document type with Rummager

- app/presenters/published_edition_presenter.rb
- lib/enhancements/artefact.rb
- lib/enhancements/edition.rb
- lib/tasks/publishing_api.rake
- test/unit/published_edition_presenter_test.rb
The first of the Publisher owned formats to have their routes managed by
content-store. This changes the published schema of the help pages from
'placeholder' to 'generic_with_external_related_links'.
In addition, we make it so that Publisher does not attempt to manage
routes or rummager for this content.
> Change the schema of Help Pages so the routes are managed by Publishing-API

- lib/enhancements/artefact.rb
- lib/tasks/router_data.rake
There's a bug in the publishing platform that means all multi-part documents are incorrectly redirected upon archival.
As a short-term workaround, here we have a tool to create a router-data compatible CSV file with the redirects of all archived multi-part content. 
The resultant CSV will need to be integrated into router-data, independently.
Trello:
https://trello.com/c/jWVgYcxQ/618-investigate-unpublishing-parted-formats-with-redirects
> Add router-data compatible export tool for archived multipart content

- app/views/shared/_govspeak_help.html.erb
The current URL links to our old wiki:
https://sites.google.com/a/digital.cabinet-office.gov.uk/wiki/projects-and-processes/processes/editorial/govspeak
Which links to the Wiki on alphagov/govspeak:
https://github.com/alphagov/govspeak/wiki/Using-govspeak-on-GOV.UK
Which recommends a link to the new Govspeak Guide:
http://govspeak-guide.herokuapp.com/
This updates the URL to save the user two clicks.
> Fix link to Govspeak Guide

- Jenkinsfile
- test/integration/root_overview_test.rb
Schema tests were building against the wrong `govuk-content-schemas` branch when being started from `govuk-content-schemas` branch CI. This updates the Jenkinsfile to use the specified schema.
Whilst trying to get this to build a couple of flakey tests popped up so I've tried to fix those too.
> Fix Jenkinsfile

- lib/sync_checker.rb
- lib/tasks/publishing_api.rake
- lib/tasks/sync_checks.rake
- test/unit/lib/sync_checker_test.rb
- test/unit/tasks/local_transactions_rake_test.rb
- test/unit/tasks/republish_content_test.rb
In order to check that we have migrated the help pages correctly this rake task will check certain fields have not changed after the format has been republished using the new schema.
https://trello.com/c/1zlDYRH8/625-migrate-help-page-format-to-rendered-1-3-3
> Add help page sync checker rake task

- app/workers/publishing_api_publisher.rb
- test/unit/publishing_api_publisher_test.rb
Previously in Publisher we were sending the update_type as "minor" for
every publish. This resulted in the publishing-api never knowing about
"major" updates.
We now send nil as the default update_type as we can allow
publishing-api to make the decision to use the editions update type as
seen here:
https://docs.publishing.service.gov.uk/apis/publishing-api/api.html#post-v2-content-content-id-publish
> Fix update type when publishing content

- app/services/unpublish_service.rb
- test/unit/services/unpublish_service_test.rb
Previously we were not sending the locale when unpublishing, which meant that Welsh content would not be unpublished properly against the publishing api.
For https://trello.com/c/WfsT2KM6/634-fix-unpublishing-welsh-content-bug-in-publisher
> Send locale when unpublishing

- lib/tasks/router_data.rake
Publisher currently allows segment redirects within its' GUI. For our temporary task to export multipart redirects to router-data we will be removing all segment redirects and only redirect to the top of the page.
https://trello.com/c/4TxuwEgo/636-fix-publisher-multipart-csv-export-task
> Remove segments from mulitpart redirects

- test/unit/presenters/formats/generic_edition_presenter_test.rb
Content-Schemas is failing CI because of a default Artefact `kind` being set in the content-models factory. This override should ensure we don't run into this problem again during migration.
> Fix schema type clash in upstream project CI

- app/services/unpublish_service.rb
- test/unit/services/unpublish_service_test.rb
Some artefacts don’t exist in Rummager, causing an `HTTPNotFound`
error. This stops the unpublishing process from reaching Publishing
API. Instead we should swallow the exception.
> Continue to unpublish if Rummager 404s

- app/helpers/paths_helper.rb
- app/presenters/formats/edition_format_presenter.rb
- app/views/noisy_workflow/request_fact_check.text.erb
- config/application.rb
- lib/enhancements/edition.rb
- test/unit/edition_test.rb
- test/unit/helpers/admin/paths_helper_test.rb
- test/unit/presenters/formats/help_page_presenter_test.rb
Using [JWT](https://trello.com/c/rROSYwYF/95-allow-token-based-access-to-preview-for-fact-checking-3) we can allow unauthenticated users to view specific pages in the draft
stack.
This change adds the JWT token to the generated URL in the fact-check
invitation emails. It will allow anyone with that URL to access the
specific draft edition it refers to. The URL will cease to work once
the edition has been published, and won't work for future editions.
https://trello.com/c/510Jc9Cl/628-migrate-help-page-fact-check-without-signon-account-3-3-8
> Draft stack auth bypass for fact-checkers

- app/presenters/formats/edition_format_presenter.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
- test/unit/presenters/formats/help_page_presenter_test.rb
Documents returned from the content-store have inconsistant date formats. Some use the trailing modifier `Z` to signify UTC, whereas others are represented using the `+00:00` time zone offset.
For consistency, and because the publishing-platform has standardised on the latter, this changes datetime strings in rendered JSON to use the `rfc3339` standard.
> Fix ISO 8601 timezone format in downstream documents

- Jenkinsfile
There were CI failures against upstream govuk-content-schema branches
because of the configuration of the linter in this Jenkinsfile which was
running against the diff of deployed-to-production and origin/master.
There's really no need for the linter to run when we're testing schema
compatibility, so we skip it in this case.
> Improve CI when running as a downstream schema tests

- config/environments/test.rb
- lib/enhancements/artefact.rb
- test/unit/edition_test.rb
For preview purposes, the `Artefact.migrated_format?` method must include `answer`
> Add answer to list of migrated formats

- lib/enhancements/artefact.rb
- lib/enhancements/edition.rb
- lib/sync_checker.rb
- lib/tasks/sync_checks.rake
- test/unit/edition_test.rb
We discovered an error when republishing Answer content. Namely,
our assumption that Artefact#kind will always equal the Edition type
was wrong. When an Edition changes format, the Artefact#kind doesn't
change with the edition.
> Update meaning of migrated

- app/presenters/formats/local_transaction_presenter.rb
- app/services/edition_presenter_factory.rb
- test/unit/presenters/formats/local_transaction_presenter_test.rb
Add presenter and sync checks for LocalTransaction format
CI won't pass until https://github.com/alphagov/govuk-content-schemas/pull/516 gets merged (and deployed)
> Local transaction schema

- app/presenters/formats/edition_format_presenter.rb
- lib/tasks/sync_checks.rake
- test/unit/presenters/formats/edition_format_presenter_test.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
Previously this was determined by the 'kind' attribute on the edition's artefact. However when an edition was converted into another type (eg from Answer to Guide), the artefact's 'kind' would not updated. When sending this information to the publishing api, it could end up being misleading to have differening schema_name and document_type (to my knowledge, the two different attributes can be used define specialisations), so we prefer to send the document type as directly determined by the edition.
> Send document_type based on edition type

- app/presenters/formats/local_transaction_presenter.rb
- test/unit/presenters/formats/local_transaction_presenter_test.rb
The fields `introduction`, `more_information`, `need_to_know` and `lgil_override` are not required in the schema for local transactions. Therefore when these are nil, we don't send them at all (rather than sending nil which will fail schema validation or sending an empty string which is less explicit)
> Do not present nil values for local transactions

- lib/tasks/publishing_api.rake
Adds a rake task to republish draft editions by format
In conjunction with : https://trello.com/c/LTxUDSbU/661-enable-preview-links-for-external-users-for-draft-content
> Add republish_drafts_by_format rake task

- app/helpers/paths_helper.rb
- app/views/noisy_workflow/request_fact_check.text.erb
- lib/enhancements/edition.rb
- test/unit/edition_test.rb
- test/unit/helpers/admin/paths_helper_test.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
Users of Publisher want to provide access to the draft content, even
when its not in the fact check state. Therefore, add the fact check
token to the Preview button link.
As the preview link now includes the token, remove the
fact_check_edition_path function and changes uses of it to use
preview_edition_path.
Alter the model to allow for the generation of the fact check id
regardless of the state.
Note that the Publishing API currently strips the access limited
information when sending published content to the draft content
store. This means that the token won't have any effect, therefore to
avoid confusion, don't include the token if this is the case.
https://trello.com/c/LTxUDSbU/661-enable-preview-links-for-external-users-for-draft-content
> Add fact check token to preview link for preludial states

- app/presenters/formats/answer_presenter.rb
- app/presenters/formats/edition_format_presenter.rb
- app/presenters/formats/generic_edition_presenter.rb
- app/presenters/formats/guide_presenter.rb
- app/presenters/formats/help_page_presenter.rb
- app/presenters/formats/local_transaction_presenter.rb
- app/presenters/formats/simple_smart_answer_presenter.rb
- app/presenters/search_payload_presenter.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
- test/unit/services/search_indexer_test.rb
- Use the artefact "kind" as document type. For non-migrated editions we're currently sending the schema name (`generic_with_external_related_links`) to the content store as document type. This is affecting the analytics gathering, which uses document type.
This separates the two concepts by having a separate method for the type. This will make sure we won't confuse the two anymore.
As noted in #566, `@artefact.kind` isn't always the correct type (the kind doesn't change
if the format changes). This will be solved by migrating all the documents. In the meantime, the `kind` is preferable to `generic_with_external_related_links`.
- Send the same data to rummager as content-store. This makes sure that the rendering_app, publishing_app and content_store_document_type are the same in rummager …
> Fix document types for content store & rummager

- app/helpers/paths_helper.rb
We should also ignore content which has been archived when generating the JWT tokens.
> Ignore archived state for token generation

- Gemfile
- Gemfile.lock
- app/presenters/formats/completed_transaction_presenter.rb
- app/presenters/formats/local_transaction_presenter.rb
- app/services/edition_presenter_factory.rb
- lib/enhancements/edition.rb
- test/unit/edition_test.rb
- test/unit/presenters/formats/completed_transaction_presenter_test.rb
- test/unit/services/edition_presenter_factory_test.rb
Migrate the Completed Transaction format
https://trello.com/c/unTNbCHi/658-migrate-completed-transaction-format-to-rendered
Note: tests will not pass until https://github.com/alphagov/govuk-content-schemas/pull/538 is merged.
Mobbed with @emmabeynon @whoojemaflip @binaryberry
> Migrate Completed Transaction to rendered

- app/helpers/edition_activity_buttons_helper.rb
- app/views/root/_publication.html.erb
- app/views/shared/_history.html.erb
- test/integration/edition_history_test.rb
- test/integration/edition_workflow_test.rb
- It makes no sense for users to be directed to draft-origin to view
already published editions, so link them to "View this on the GOV.UK
website" corresponding to the environment they're in.
Trello: https://trello.com/c/5d86KxiY/685-make-ui-changes-in-publisher-for-previewing-published-and-archived-editions-2
Before:
After:
> View published editions on origin production, not draft

- lib/tasks/schema_tests.rake
This rake task only runs tests that have the word "schema" in them. We can run this task instead of the full test (which takes 8 minutes) when testing as a downstream build from govuk-content-schemas.
Having "schema" in the test file is obviously going to cause false positives, but hopefully no false negatives - which would be worse.
This test run takes 10s to complete.
> Add a test:schemas rake task

- Gemfile
- Gemfile.lock
This allows to run a single test easily by specifying the line number, using
`bundle exec mtest -I test path_to_test_file.rb:56` to run the test that is on
line 56.
Full list of features: https://github.com/grosser/maxitest#features
> Add maxitest gem

- app/views/root/_publication.html.erb
- app/views/shared/_history.html.erb
- test/integration/edition_history_test.rb
- test/integration/root_overview_test.rb
- I made a mistake in #587 - `link_to` didn't have enough arguments, so it was showing the entire URL as link text.
Before:
After:
> Fix the `link_to` parameters for viewing published editions on GOV.UK

- Gemfile
- Gemfile.lock
- app/helpers/edition_activity_buttons_helper.rb
- app/views/root/_publication.html.erb
- app/views/shared/_history.html.erb
- test/integration/edition_history_test.rb
- test/integration/edition_workflow_test.rb
- For archived content, Publisher shouldn't link to the draft content
store because it might be inaccurate (and show a published edition).
So, disable the preview button, remove the link on the slug on the
index page, and remove the preview link on the history and notes page.
- This relies on a change in content_models to the `GuideEdition` and
`Edition` `safe_to_preview?` method to make it false for archived
content.
https://trello.com/c/5d86KxiY/685-make-ui-changes-in-publisher-for-previewing-published-and-archived-editions-2
Before:
After:
> Don't let users preview archived editions

- app/presenters/formats/edition_format_presenter.rb
- test/unit/presenters/formats/answer_presenter_test.rb
- test/unit/presenters/formats/completed_transaction_presenter_test.rb
- test/unit/presenters/formats/edition_format_presenter_test.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
- test/unit/presenters/formats/guide_presenter_test.rb
- test/unit/presenters/formats/help_page_presenter_test.rb
- test/unit/presenters/formats/licence_presenter_test.rb
- test/unit/presenters/formats/local_transaction_presenter_test.rb
- test/unit/presenters/formats/place_presenter_test.rb
- test/unit/presenters/formats/simple_smart_answer_presenter_test.rb
- test/unit/presenters/formats/transaction_presenter_test.rb
Frontend's JSON API is being retired (see
https://github.com/alphagov/frontend/pull/1180) so we remove code that sends
JSON to Frontend as part of the routes payload.
Trello: https://trello.com/c/7IRxAVoJ/688-retire-frontend-s-json-api
> Stop sending JSON as part of routes payload

- lib/tasks/bulk_unpublish_placeholder_content.rake
Update this one-shot task to account for the ~50 documents in publishing-api with the `placeholder` schema that currently 404 in router.
> Remove Vanished content from publishing-api

- app/helpers/paths_helper.rb
- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/_approve_fact_check.text.erb
- app/views/noisy_workflow/_approve_review.text.erb
- app/views/noisy_workflow/_assign.text.erb
- app/views/noisy_workflow/_cancel_scheduled_publishing.text.erb
- app/views/noisy_workflow/_create.text.erb
- app/views/noisy_workflow/_new_version.text.erb
- app/views/noisy_workflow/_publish.text.erb
- app/views/noisy_workflow/_receive_fact_check.text.erb
- app/views/noisy_workflow/_request_amendments.text.erb
- app/views/noisy_workflow/_request_review.text.erb
- app/views/noisy_workflow/_schedule_for_publishing.text.erb
- app/views/noisy_workflow/_send_fact_check.text.erb
- app/views/noisy_workflow/_skip_fact_check.text.erb
- app/views/noisy_workflow/_skip_review.text.erb
- app/views/noisy_workflow/_start_work.text.erb
- test/unit/helpers/admin/paths_helper_test.rb
Private Frontend is being turned off, and many of the NoisyWorkflow partials had preview links to it, so we update them to point to draft origin instead.
[Trello](https://trello.com/c/JYT9roQm/709-turn-off-private-frontend)
After speaking to the content team we discovered that emails have not been sent using NoisyWorkflow since 2014, but it is functionality that they would like to have.  There is a card in the backlog for that piece of work, so we have decided to leave the code in place for whoever picks that up in future.
> Update NoisyWorkflow partials preview URL

- app/workers/downtime_scheduler.rb
- According to http://stackoverflow.com/a/17277093, this is the fix for
the Errbit errors we've been seeing (https://errbit.publishing.service.gov.uk/apps/5304e0520da11511b0000011/problems/58d536ee65786370a1900000).
- I'm doing this `.to_s` directly here, because I think this is the only
place in the file where the `downtime_id` parameter isn't previously
stringified. The other `downtime_id` parameters are used from other
methods (`self.schedule_publish_and_expiry`, for example) which have
already had the `downtime.id.to_s` treatment, but `perform` isn't
called from any of these. I did try to trace this through the
workers/controllers/models to see where `perform` was being called
directly, but I couldn't - I presume it's a purely Sidekiq thing.
> Convert the `downtime_id` to be a string for the `perform` worker action

- app/views/noisy_workflow/request_fact_check.text.erb
- lib/enhancements/edition.rb
- test/unit/edition_test.rb
- test/unit/helpers/admin/paths_helper_test.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
All publisher formats will have been migrated, so this code is no longer
necessary.
> Remove references to migrated formats

- Rakefile
- app/presenters/search_index_presenter.rb
- lib/tasks/lint.rake
- test/unit/presenters/search_index_presenter_test.rb
Rummager doesn't care about paths and prefixes so there's little point in
continuing to send them.  We still send the `link`.
Any fields that are not part of [the schema for the type][1] we're sending [will be silently ignored][2]
Also adding the linter to the default rake task so that we pick up silly things that stop us merging PRs more quickly.
[1]: https://github.com/alphagov/rummager/blob/master/config/schema/base_elasticsearch_type.json
[2]: https://github.com/alphagov/rummager/blob/master/docs/documents.md#post-indexdocuments
> Stop sending paths/prefixes to Rummager

- app/services/publishing_api_workflow_bypass_publisher.rb
- test/unit/services/publishing_api_workflow_bypass_publisher_test.rb
`%w(published, archived)` produces: 
`["published, ", "archived"]` rather than the expected:
`["published", "archived"]`
* Use `%w(published archived)`
We should have some rubocop protection against using `,` within `%w`
This fix prevents unnecessary calls to `discard_draft` which were throwing an error because no draft existed. This error stopped the downtime message from being published:
https://github.com/alphagov/publisher/blob/fix-downtime/app/services/publishing_api_workflow_bypass_publisher.rb#L14
Error that was being thrown:
```
Response body: {"error":{"code":422,"message":"There is not a draft
edition of this document to discard"}} Request body: {}
```
This error was also masked by the way `discard_draft` was being stubbed on an instance of publishing_api. Removing the stub …
> Fix bug with downtime messages not being published when no draft present

- app/services/unpublish_service.rb
- test/unit/services/unpublish_service_test.rb
Archived editions are probably unpublished in the Publishing API, but
unpublishing them again is useful to update the way which they were
unpublished to change the page they redirect to.
> Don't silently fail to unpublish archived editions

- Gemfile
- Gemfile.lock
- test/integration/unpublish_test.rb
This removes validation from redirect_url, which means that Publisher
can now unpublish content and use a redirect_url that didn't match the
previous validation criteria, but is now valid for either the
Publishing API or GOV.UK Content Schemas, e.g. redirecting to
a *.gov.uk subdomain.
> Update govuk_content_models 44.3.0 -> 44.4.0

- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/request_fact_check.text.erb
Trello: https://trello.com/c/VsZrR0D0/143-updating-the-fact-check-email-work
Currently missing the `[current date + 5 business days]` functionality - this will come as a later piece of work.
> Alter the text and subject of the fact checking email

- app/presenters/formats/answer_presenter.rb
- app/presenters/formats/edition_format_presenter.rb
- lib/tasks/publishing_api.rake
- test/unit/presenters/formats/answer_presenter_test.rb
this is part of the work to consolidate applications and moves
the answers format to government frontend. the frontend work
has been done for this.
> Add ability to switch the rendering app depending on format

- app/models/area.rb
This commit removes the reference to the `business-support-api` which has now been retired.
> Remove reference to business-support-api

- app/presenters/search_payload_presenter.rb
- test/unit/services/search_indexer_test.rb
For licences only, we should index the following fields:
- `licence_identifier`;
- `licence_short_description`.
This is so we can replace calls to the Content API with calls to Rummager.
Trello: https://trello.com/c/vlqSHmTZ/76-make-licence-finder-use-something-else-to-fetch-licenses
Dependencies:
> Add licence identifier to Rummager

- lib/tasks/calculators.rake
Move the start page for the child tax benefit calculator from calculators to Publisher/Frontend.
Part of https://trello.com/c/rz7jFckZ/
This will allow content designers to make changes to the content and will make the page consistent with other start pages.
* The path needs to be claimed so that Publisher can publish to it
(this will stop Calculators from publishing to that path too)
* Draft a start page with content that's currently live
* Delete any old artefact owned by calculators so new artefact can be created
* Maintain Need IDs
* Use existing content_id so that content doesn't need to be unpublished
(which would risk users not seeing the page)
Steps to switch the start page:
* Merge and deploy: https://github.com/alphagov/calculators/pull/185
* Run `claim` rake task
* Run `draft` …
> Add rake tasks for claiming & drafting calculator start page (a transaction)

- db/migrate/20170508130537_remove_whitehall_content_from_shared_db.rb
Whitehall artefacts were sent to the shared database for tagging in Panopticon.
Panopticon has been retired, so this data is not needed anymore.
This reduces the count in the 'artefacts' collection in the shared database from 208586 to 4922.
I've checked that that this data can be removed with a few people, but please shout if you see any problems with this. The original data is still in Whitehall, and tagging has migrated from Panopticon to Content Tagger.
Also wasn't sure whether Publisher was the best place to add this migration, but seemed like the best access to the shared database.
Related to https://github.com/alphagov/govuk_content_models/pull/435
> Add migration to remove Whitehall data

- app/models/edition.rb
When loading `Edition`, the classes in the `EXACT_ROUTE_EDITION_CLASSES` array
were also loaded. Because `Edition` hadn't finished loading, it was loaded as
these classes inherit from it.  And so on.
I'm not sure how this isn't a problem in production, but it seems OK at the
moment.
I think this is a result of a slightly different loading order in Edition given that the exact
route logic used to be in a `lib/enhancements/edition.rb` file, but has now been 
subsumed into the model after the govuk_content_models retirement.
> Fix circular dependency in dev?

- app/views/simple_smart_answers/_fields.html.erb
- test/integration/simple_smart_answers_test.rb
Based on our findings in Benchmarking Q1, we want to add "Find contact details" to the "Start button text" drop down options. This is to improve the success rate of users entering the "contact DVLA" service.
https://trello.com/c/WLEWKO6W/190-publish-deploy-final-dvla-changes
> Add new Simple Smart Answer button text

- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/request_fact_check.text.erb
`format.text` should use `render :plain` not `render :html`
Before:
```
&lt;strong&gt;HTML&lt;/strong&gt; Hi,
We need you to check the factual accuracy of changes made to &#39;Student finance: how to apply&#39; before it’s published on GOV.UK.
```
After:
```
Hi,
We need you to check the factual accuracy of changes made to 'Student finance: how to apply' before it’s published on GOV.UK.
```
Fixes https://govuk.zendesk.com/agent/tickets/2296781
> Send fact check emails as text not HTML

- app/controllers/editions_controller.rb
- app/models/transaction_edition.rb
- app/presenters/formats/transaction_presenter.rb
- app/views/transactions/_fields.html.erb
- test/integration/transaction_create_edit_test.rb
- test/unit/presenters/formats/transaction_presenter_test.rb
This change allows publishers to choose the text that appears in the
green “start” button on a Transaction. This behaviour is basically a
direct read-across from the similar functionality in Simple Smart
Answers.
Publishers will be able to select from a drop-down, which only contains
two choices:
- “Start now”
- “Sign in”
“Start now” is the text that is currently displayed, and remains the
default.
“Sign in” is the new copy requested specifically for the Universal
Credit Sign In page.
We use a drop-down to restrict the choices. Copy will need to go through
approval to be included in the drop-down, and having a list of these
items will help to keep consistency across GOV.UK (for example, we will
not have variations like “Sign in”, “Signin”, “Log in”, etc.).
> Enable editing of Transaction Start button text

- app/views/simple_smart_answers/_fields.html.erb
- app/views/transactions/_fields.html.erb
- test/integration/simple_smart_answers_test.rb
- test/integration/transaction_create_edit_test.rb
Trello: https://trello.com/c/2JyPdctt/727-2-change-publisher-start-button-text-select-to-radio-buttons
According to [our guidance](https://paper.dropbox.com/doc/Select-boxes-v7PWDvPDV2tmc9pzDbm3s), we should avoid `select` elements where possible.
We should then use radio buttons instead of dropdowns on the "Start Button Text" fields for both Transactions and Simple Smart Answers.
> Substitute select tags with radio buttons

- app/presenters/organisation_content_presenter.rb
- config/environments/development.rb
- lib/csv_report_generator.rb
- test/unit/organisation_content_presenter_test.rb
For: https://trello.com/c/5oeDn5Xy
This commit brings back the organisation content report that was
removed before. A few of the columns are no longer stored in
the publisher app, but have been moved to the publishing_api.
As such, calls are made to the publishing_api to retrieve the
missing information.
> Add organisation content report

- app/presenters/organisation_content_presenter.rb
Changes dig to fetch when searching through the hash that is returned from publishing_api in organisation_content_presenter.rb. This allows us to give the value a default empty hash if it can't find it, whereas dig returns nil if the key is not present, and map cannot be called on a nil object.
> Change dig to fetch when searching through hash

- app/models/edition.rb
- db/migrate/20171009143335_synchronise_artefact_kinds_with_latest_edition_formats.rb
- lib/edition_duplicator.rb
- test/support/factories.rb
- test/unit/edition_duplicator_test.rb
Tangentially for: https://trello.com/c/RRJOTFQo/252-remove-business-support-code-that-still-exist-in-publisher
While exploring how best to remove and properly redirect business finance support editions from publisher I noticed that artefacts did not always have the a `kind` that matched up with the `format` of their `latest_edition`.  Since #428 we've allowed users to create a new edition of a published document with a new type, but we never made sure the artefact kind and edition format synced up.
It's unlikely to cause any real problems, but it felt strange to me so I thought I'd attempt to fix it.  There are notes on each commit, so worth reading them one-by-one.
> Change artefact kind when we change edition format

- config/fact_check.yml
- config/initializers/email_groups.rb
- config/initializers/fact_check.rb
- config/initializers/gds-sso.rb
- config/initializers/gds_api.rb
- config/schedule.rb
- lib/mail_fetcher_config.rb
- test/unit/mail_fetcher_config_test.rb
This sets up environment variable conditionals for the various configurations set up in [alphagov-deployment](https://github.com/alphagov/alphagov-deployment/tree/master/publisher) to make way for it's removal.
More details on individual commits.
> Set up application for removal of alphagov-deployment

- app/models/artefact.rb
- app/services/unpublish_service.rb
- db/migrate/20171012124313_republish_business_support_editions_as_publishing_api_redirects_or_gones.rb
- test/models/artefact_test.rb
- test/unit/services/unpublish_service_test.rb
For: https://trello.com/c/RRJOTFQo/252-remove-business-support-code-that-still-exist-in-publisher
This is part 1 of the work for this card to remove business support code and data from publisher and make sure they're all redirected properly in publishing-api instead of router-data.  Part 2 actually deletes the code and edition data (see: #649), part 3 removes the entries from router-data (see: alphagov/router-data#5), and part 4 removes the schema from content-schemas (see: alphagov/govuk-content-schemas#653).
This is a migration that works through all the business_support artefacts in the publisher database and decides what to do with them.  Ultimately we unpublish with a redirect, create a new redirect content item, create a new gone content item, or destroy the artefact.  The choices …
> Republish business support editions as publishing api redirects or gones

- db/migrate/20171012124313_republish_business_support_editions_as_publishing_api_redirects_or_gones.rb
We had `=` instead of `==` when detecting the
`jobcentre-plus-vacancy-filling-system-uk` artefact which means we picked
the wrong artefact to check the redirect against.  Unluckily for us this
artefact's routes had the same conditions as the
`jobcentre-plus-vacancy-filling-system-uk` one so picking the wrong
artefact didn't cause an exception to be raised.  Ultimately what this
does is mean we filtered this artefact out of the list of live ones to
process and don't redirect it properly.  Replacing the `=` with `==`
means we pick the correct artefact for
`jobcentre-plus-vacancy-filling-system-uk` and only filter it out.
> Fix equality typo in republishing business_support migration

- lib/tasks/publish_start_page_ab_test_pages.rake
For [Trello](https://trello.com/c/zfJiG9v8/145-sa-a-b-test-make-changes-to-government-frontend)
This adds two rake tasks to publish content for the upcoming Start Pages A/B test in Government Frontend.  These pages don't use a standard publishing format and the content will be hardcoded in Government Frontend, so we can't use the standard Publisher UI workflow to create them.  Instead we create rake tasks to send the necessary information to the Publishing API and subsequently to Content Store in order to create a content item that Government Frontend can read from.  The content created by these tasks are:
1) An interstitial page for displaying login options to a user
2) A 'create an account' page for users who don't already have a Verify or Government Gateway account
Note, we intend to …
> Add rake tasks to publish Start Page A/B test pages

- lib/tasks/publish_start_page_ab_test_pages.rake
For [Trello](https://trello.com/c/zfJiG9v8/145-sa-a-b-test-make-changes-to-government-frontend)
This adds a rake tasks to publish a "Lost account details" page for the upcoming Start Pages A/B test in Government Frontend.  This page doesn't use a standard publishing format and the content will be hardcoded in Government Frontend, so we can't use the standard Publisher UI workflow to create it.  Instead we create a rake task to send the necessary information to the Publishing API and subsequently to Content Store in order to create a content item that Government Frontend can read from. 
Note, we intend to remove these rake tasks once the A/B test has concluded see [Trello](https://trello.com/c/xdmgIGIO/163-tear-down-a-b-test).
> Add rake task to publish "Lost account details" page

- app/assets/javascripts/modules/collapsible_group.js
- app/views/shared/_history.html.erb
- spec/javascripts/spec/collapsible_group.spec.js
For: https://trello.com/c/E0AkfL26/299-publisher-edition-notes-expand-all-option
We want to introduce expand all / collapse all to the history & notes tab.  Luckily it uses bootstrap collapse, and we already have our own collapsible-group module to provide a expand/collapse all toggle so we can use that.
One downside is that the behaviour of this is to always collapse if any item in the group is open, and only expand if all are closed.  We start with the first item open and would probably expect that the toggle would open the rest of them, but it will instead close the first one and then change to an expand all option.
I'm checking to see if that's ok, or if we should change the collapsible-group behaviour to always expand if none are closed, and only collapse if all are open.  I don't …
> Collapse all edition history

- lib/tasks/unpublish_start_page_ab_test_pages.rake
Trello: https://trello.com/c/xdmgIGIO
Add a rake task to unpublish the three pages we added as part of the
Self Assessment A/B test. That test finished on 17/11/2017 and these
particular pages are no longer needed.
> Unpublish pages added for Self Assessment A/B test

- lib/service_sign_in/example.yaml
Trello card: https://trello.com/c/bvVMGlvn
We are creating a new "service_sign_in" document type (see PR https://github.com/alphagov/govuk-content-schemas/pull/667) that displays a set of pages to the user to allow them to choose how to sign on or to create an account.
These pages will be rendered in government-frontend. For the MVP, we are not building the Publisher workflow. Instead, we are going to read the content from a YAML file and publish the content item to publishing api via a rake task and a new presenter that we will create in a later PR.
In order to create a service_sign_in content item, we will need content designers to fill out a YAML file with the required content data.  We create an example YAML file to help guide content designers with this task.
> Add example service_signin YAML file

- Dockerfile
This resolves an issue we see with the main PhantomJS package being rate
limited and returning 429s from bitbucket which results in failing
builds.
> Update PhantomJS to use prebuilt version

- Jenkinsfile
Hey :wave: !
This PR will enable a set of [end-to-end tests](https://github.com/alphagov/publishing-e2e-tests) to run every time a commit is made to this repo. :boom:
You can read through the scenarios at a [high level](https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1AUYU4n4GN_XGdqUJdONN2pbQnVEC5o8s--59IipeFjY/edit?usp=sharing), and the capybara [here](https://github.com/alphagov/publishing-e2e-tests/tree/master/spec/publisher).
Look at the merge box below and you'll see a new check performed against this PR.
Enabling these tests will give increased confidence when making changes to this repo that the change doesn't break the publisher in an end-to-end environment.   Downside is that running these tests takes time, with build times between 6 - 11 minutes currently.
> Run the end to end tests which go through the publisher app

- app/presenters/formats/service_sign_in_presenter.rb
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
For [Trello](https://trello.com/c/obBGmd3o/244-create-a-presenter-for-servicesignin-pages-in-publisher-3)
Paired with @leenagupte 
Due to time restrictions in Q3, we are not creating a UI for content designers to create "Service Sign In" pages themselves so we decided to import content item data from a YAML file (see https://github.com/alphagov/publisher/pull/664).  For these reasons we also decided not to create a "ServiceSignIn" model to persist the YAML data to a database and instead decided to follow the Specialist Publisher model of sending the data directly to the Publishing API.
We now create a presenter that reads the content of a given YAML file and constructs a payload that can be sent to the Publishing API and is valid against the `service_sign_in` content schema.
> Add service_sign in_presenter

- app/services/service_sign_in_publish_service.rb
- lib/tasks/service_sign_in.rake
- test/unit/services/service_sign_in_publish_service_test.rb
For [Trello](https://trello.com/c/yuhxNVMY/254-create-a-rake-task-to-publish-servicesignin-pages)
Currently content designers aren't able to create "Service Sign In" content in
the Publisher UI. This adds a rake task which will take a YAML file containing
content for a "Service Sign In" page and publish to the Publishing API using
`ServiceSignInPublishService`.
> Add rake task to publish Service Sign In pages

- app/presenters/formats/service_sign_in_presenter.rb
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
For [Trello](https://trello.com/c/ydt46bDm/276-make-the-create-new-account-page-optional-in-the-schema)
`create_new_account` is now an optional field for the `service_sign_in` schema (see [commit](https://github.com/alphagov/govuk-content-schemas/pull/689/commits/24019d2e980ae0d003103e0d4b46d0704d71069d)),
so we update the `ServiceSignInPresenter` to handle this.
> Handle optional create_new_account in Service Sign In Presenter

- Gemfile.lock
This is needed by the E2E tests to run signon in mock mode while the applications run in production.
> Upgrade gds-sso to latest version

- app/presenters/formats/service_sign_in_presenter.rb
- app/services/service_sign_in_publish_service.rb
- test/unit/services/service_sign_in_publish_service_test.rb
Related to PR #668 
Publishing-api assumes that the locale is "en" if you do not
explicitly pass the locale in the publish call. As we are also
publishing Welsh content, we should always pass the locale of the
content item.
We have to pass the update_type too now because of the order that
publishing-api expects to see the params.
> Pass "locale" to service_sign_in publish call

- Dockerfile
- config/environments/production.rb
- config/initializers/session_store.rb
Hey :wave:,
The publishing-e2e-tests are being built in production mode now, and as part of that initial work we need to disable secure cookie due to not using SSL and sending emails due to no mail server.
The Dockerfile ARG allows us to only compile the assets when we require allowing for easy switching back to development mode and not slowing down any existing usage of this Docker image.
> Add conditionals to allow running publisher in production on E2E tests

- lib/service_sign_in_yaml_validator.rb
- test/fixtures/service_sign_in/invalid_start_page_slug.yaml
- test/fixtures/service_sign_in/missing_choose_sign_in_fields.yaml
- test/fixtures/service_sign_in/missing_choose_sign_in_option_fields.yaml
- test/fixtures/service_sign_in/missing_create_new_account_fields.yaml
- test/fixtures/service_sign_in/missing_top_level_fields.yaml
- test/fixtures/service_sign_in/no_choose_sign_in_fields.yaml
- test/fixtures/service_sign_in/no_choose_sign_in_option_fields.yaml
- test/unit/lib/service_sign_in_yaml_validator_test.rb
For [Trello](https://trello.com/c/UHPwDcmd/273-validate-the-contents-of-the-yaml-file)
In https://github.com/alphagov/publisher/pull/668 we created a rake task that takes the contents of a YAML file and prepares a payload in order to publish "Service Sign In" content to the Publishing API.  In this PR we create a validator to ensure that the required content is present in the YAML file in order to perform this task successfully.  After merging this PR we will update the rake task to use this validator.
> Add Service Sign In YAML validator

- lib/service_sign_in/check-update-company-car-tax.en.yaml
The Govspeak passed to the body param was not indented properly.
We've updated the guidance to reflect this.
> Fix invalid YAML indentation

- lib/tasks/service_sign_in.rake
For [Trello](https://trello.com/c/axBb1P1R/295-add-service-sign-in-yaml-validator-to-the-rake-task)
Now we have a `ServiceSignInValidator` (see [PR](https://github.com/alphagov/publisher/pull/674)) to check that the contents of a service_sign_in YAML file are valid, we update `service_sign_in:publish` rake task to call it before we prepare a suitable payload to
send to the Publishing API.
This PR also adds a rake task to validate the YAML file independently of the publish task.
> Add YAML validator to service sign in rake task

- lib/service_sign_in/check-update-company-car-tax.en.yaml
We remove the empty `description` field from
`check-update-company-car-tax.en.yaml` as the `service_sign_in` schema is
expecting a string if `description` is present.
> Remove empty description from YAML file

- app/presenters/formats/service_sign_in_presenter.rb
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
The `service_sign_in` format considers `choose_sign_in` `description` to be an
optional field.  We found a bug in the Service Sign In Presenter where
`choose_sign_in` `description` is always included in the payload regardless of
whether it is provided in a service_sign_in YAML file, causing the
`service_sign_in` schema validation to fail when `description` is not provided.
This makes the inclusion of `choose_sign_in` `description` in the payload
dependent on its presence in the YAML file.
> Fix Service Sign In Presenter bug

- README.md
- lib/service_sign_in/README.md
This documentation was written alongside the process with Tom Hughes one of our Content Designers.
We can then link this README to the [developer docs](https://github.com/alphagov/govuk-developer-docs/search?utf8=%E2%9C%93&q=ExternalDoc&type=)
As part of https://trello.com/c/yIvCgbxI/233-document-how-to-add-a-new-interstitial-page-for-a-service-for-developers
> Add docs for how to publish service sign-in pages

- app/helpers/edition_activity_buttons_helper.rb
- app/mailers/noisy_workflow.rb
- app/models/action.rb
- app/models/edition.rb
- app/models/workflow.rb
- app/views/noisy_workflow/_resend_fact_check.text.erb
- app/views/shared/_edition_activity_fields.html.erb
- app/views/shared/_fact_check.html.erb
- lib/govuk_content_models/action_processors.rb
- lib/govuk_content_models/action_processors/base_processor.rb
- lib/govuk_content_models/action_processors/resend_fact_check_processor.rb
- test/functional/noisy_workflow_test.rb
- test/integration/edition_workflow_test.rb
- test/models/workflow_test.rb
- test/support/action_processor_helpers.rb
For: https://trello.com/c/nmcSC29S/300-make-it-easier-to-re-send-a-fact-check
We add an action that presents the previous fact check details and allows the user to re-send it.  We don't send any details though, we just look it up in the db once we're asked to perform this action and re-use that previous fact check action to send it's email again.
The "Resend fact check email" button only appears when the edition is in the "fact check" state (e.g. you've sent a fact check email, but not received a response).
Pressing the button represents the fact check email details to you so you can check what you're about to send.  
If the details are very long you have to scroll the modal to get to the button to actually send the email.
The fact check being resent is recorded in the history and notes.
> Add UI for resending fact check emails

- app/services/service_sign_in_unpublish_service.rb
- lib/tasks/service_sign_in.rake
- test/unit/services/service_sign_in_unpublish_service_test.rb
Trello: https://trello.com/c/HewVN7nP/237-create-a-rake-task-to-unpublish-service-sign-in-pages
As `service_sign_in` content cannot be published through the UI, we create rake tasks to unpublish it with the `gone` and `redirect` unpublishing types.  We've decided not to unpublish `service_sign_in` as a withdrawal as having the withdrawal notice above the radio buttons could be confusing to users.  We expect that `redirect` and `gone` will be most commonly used.
We've also found that when redirecting `service_sign_in` content, the redirect does work but the last slug is retained in the path e.g. `/check-income-tax-current-year/sign-in/prove-identity` => `/national-minimum-wage-rates/prove-identity`.  This is consistent with what occurs when redirecting guides so it seems reasonable to …
> Add service sign in unpublish tasks

- db/migrate/20180103150147_update_default_edition_start_button_text.rb
Ensure that all unarchived editions in the DB have a value for the start button text, which is a required field.
This field already had a default value (see https://github.com/alphagov/publisher/pull/638) which means that the correct button text was displayed even for older editions which were created before the field was added. But because the default value was missing in the DB, it caused validation errors when unpublishing an old edition: https://govuk.zendesk.com/agent/tickets/2544691
Paired with @Davidslv 
cc @tuzz
> Add missing default value for start button text

- app/models/edition.rb
- app/models/link.rb
- app/models/link_check_report.rb
- test/models/edition_test.rb
- test/models/link_check_report_test.rb
- test/models/link_test.rb
- test/support/factories.rb
This PR adds the models required for the integration of the Link Checker API into publisher.
Its the first in a series of PR to add link checking. In future PRs we will add;
- A callback endpoint for the Link Checker API to callback to
- Controller action to create link checks for editions
- A frontend UI to trigger a checker
> Add Link and LinkCheckReport models

- lib/service_sign_in/README.md
This updates the Service Sign In README to give instructions about how to update existing service sign in content and how to unpublish it.
> Update Service Sign In README

- app/controllers/link_checker_api_controller.rb
- app/services/link_check_report_updater.rb
- config/routes.rb
- config/secrets.yml
- test/functional/link_checker_api_controller_test.rb
- test/support/factories.rb
- test/unit/services/link_check_report_updater_test.rb
This PR adds an endpoint for the `link-checker-api` to POST the result of checks back to.
> Add an Link Checker API callback endpoint

- app/lib/services.rb
- app/services/edition_link_extractor.rb
- app/services/link_check_report_creator.rb
- test/support/factories.rb
- test/unit/services/edition_link_extractor_test.rb
- test/unit/services/link_check_report_creator_test.rb
This PR adds two service classes, one [`LinkCheckReportCreator`] to call the `link-checker-api` to create reports, and another [`EditionLinkExtractor`] to extract links from various subclasses of `Edition`
> Add Link Report Creator Service

- README.md
- doc/arch/adr-001-service-sign-in-pages-not-linked-to-with-content-id.md
- doc/arch/adr-002-service-sign-in-new-format.md
- doc/arch/adr-003-using-rake-to-create-service-sign-in-pages.md
- doc/arch/adr-004-rendering-service-sign-in-from-government-frontend.md
- doc/arch/adr-005-forking-frontend-components-from-govuk-frontend.md
For https://trello.com/c/9XVir0Ug/235-document-our-architectural-decisions
This adds our architectural decisions for the development of the Service Sign In format.
> Add Service Sign In Architectural Decisions

- test/unit/services/link_check_report_creator_test.rb
This PR improves the `LinkCheckReportCreatorTest` by not hiding the creation of an instance variable
> Improve LinkCheckReportCreatorTest

- app/services/edition_link_extractor.rb
- test/unit/services/edition_link_extractor_test.rb
This PR converts absolute paths to URLs before sending them to be checked by the link checker API.
Not doing this would cause false positives.
> Convert paths to urls before sending to link checker

- lib/service_sign_in/file_self_assessment.en.yaml
Trello: https://trello.com/c/LpCQ6MvS/1330-register-for-self-assessment-correct-factual-inaccuracy-on-sign-in-page
Zendesk: https://govuk.zendesk.com/agent/tickets/2549507
CHANGED
Once you’ve registered, you need to ‘activate’ your Government Gateway account by linking it with your Unique Taxpayer Reference (UTR). You’ll get a letter that tells you how to do this.
You can [create a Government Gateway account](https://www.tax.service.gov.uk/government-gateway-registration-frontend/route?continue=%2Faccount&origin=unknown) if you don't have one.
^Don’t create a new account if you’ve activated one before. You can only link your UTR to one Government Gateway account.
TO
Once you've registered, you'll get a letter that tells you what to do next. It will include your Unique Taxpayer Reference …
> Corrected 'If you're already registered'

- Gemfile
- Gemfile.lock
- app/controllers/editions_controller.rb
- app/views/shared/_edition_activity_fields.html.erb
- app/views/shared/_unpublish.html.erb
- lib/edition_progressor.rb
- test/integration/edition_workflow_test.rb
- test/unit/edition_progressor_test.rb
For: https://trello.com/c/ZCCftdjb/301-sending-factcheck-requests-from-publisher-to-multiple-emails
Our goal is to make it clearer that you can add multiple emails to fact check if you comma separate them, and to make sure we provide errors to the user if the emails they provide can't be parsed.
> Validate fact check emails

- lib/service_sign_in/file_self_assessment.cy.yaml
Trello: https://trello.com/c/UEZQhqgh/976-urgent-english-done-welsh-to-do-register-for-self-assessment-correct-factual-inaccuracy
Zendesk: https://govuk.zendesk.com/agent/tickets/2549507
CHANGE
Unwaith y byddwch chi wedi cofrestru, bydd angen i chi roi eich cyfrif Porth y Llywodraeth ar waith drwy ei gysylltu â’ch Cyfeirnod Trethdalwr Unigryw (UTR). Fe gewch chi lythyr a fydd yn dweud wrthych chi sut mae gwneud hyn.
Gallwch [greu cyfrif Porth y Llywodraeth](https://www.tax.service.gov.uk/government-gateway-registration-frontend/route?continue=%2Faccount&origin=unknown) os nad oes gennych chi un.
^Peidiwch â chreu cyfrif newydd os ydych chi wedi rhoi un ar waith yn barod. Gallwch gysylltu eich UTR ag un cyfrif Porth y Llywodraeth yn unig.^
TO
Unwaith eich bod wedi cofrestru, byddwch yn …
> Correct 'If you're already registered'

- app/services/edition_link_extractor.rb
This PR removes the convert_paths_to_urls as we've moved it into Govspeak
> Remove convert_paths_to_urls as its in Govspeak now

- app/assets/stylesheets/broken_links_report.scss
For browser windows below 992px, the link check box would cause the
form fields to get squashed into the left hand side of the well and
become unusable. For breakpoints below 992px (`md` in Bootstrap terms),
disable the float and force the box to appear above the form.
This is possibly not the best design decision, but it’s causing issues
at present for one of our partially sighted users.
Before:
After:
And above 992px:
> Make the link check box work in smaller browser windows

- app/assets/javascripts/modules/related_content_items_select.js
- app/assets/stylesheets/forms.scss
- app/controllers/editions_controller.rb
- app/controllers/publishing_api_proxy_controller.rb
- app/views/shared/_metadata.html.erb
- app/views/shared/_tagging.html.erb
- config/routes.rb
- lib/tagging/link_set.rb
- lib/tagging/linkables.rb
- lib/tagging/tagging_update_form.rb
- test/integration/tagging_test.rb
- test/support/tag_test_helpers.rb
The metadata tab of the Editions page in Publisher had a link to Content Tagger where the user could manage the links/user needs. However, for non-English pages, Content Tagger is unable to edit these taggings. In this PR, we've removed the link to Content Tagger and have moved similar functionality to the taggings tab of an Edition:
Trello: https://trello.com/c/oJ2L4qyt/89-make-it-possible-to-edit-welsh-language-content-in-content-tagger
> Modify ordered related items and user needs from Editions tagging tab

- app/controllers/application_controller.rb
- app/controllers/link_checker_api_controller.rb
This is now enforced by Signon instead. The ApplicationController
still calls authenticate_user!, so users are still required to sign
in.
> Remove require_signin_permission!

- lib/service_sign_in/personal-tax-account.en.yaml
Jira card: HUB-73: https://govukverify.atlassian.net/browse/HUB-73
Added personal-tax-account.yml file to service_sign_in folder so that the changes made to the personal tax account service can be released to staging for approval.
The wireframe for the changes to the  https://www.gov.uk/personal-tax-account page can be seen here:
https://draft-origin.publishing.service.gov.uk/personal-tax-account?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYzk1YmYzNC0xMWI2LTRkNTMtYjU0Mi05YjNmY2VkOGM5NDkifQ.f7rRcYNbTVEnVLgnHsWWRW8xFy5tOMpWXSqHze1XZtY
As part of the requirements for this story we need to move the personal tax account service over to use the new start page/interstitial page/create account pattern deployed in Q3 for Self Assessment, Company Car Tax and Check This Year's Tax. The …
> HUB-73: Roll out new service sign in in page for the personal tax account service

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/file_self_assessment.en.yaml
We're changing the wording on the sign-in pages to make the distinction between sign-in and sign-up more clear to the users.
This change is proposed by the Verify team.
Co-authored-by: Jakub Miarka <jakub.miarka@digital.cabinet-office.gov.uk>
> HUB-77: Change wording on the service sign-in pages to be more sign-in focused

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
Clearer call to actions on the Create Account page
Small change to the create account pages for Personal Tax account, Company Car tax and Check Income tax pages in the service sigin in pages to turn the links to gateway and verify services into buttons in the hopes of making them stand out more to users.
Due to Verify devs not having the same dev set up as govUK devs I have not been able to run this locally but will add the design page to the PR. There should be no copy change or functional changes, just the links representing as buttons.
Solo: @rachelthecodesmith
> HUB-91: https://govukverify.atlassian.net/browse/HUB-91

- app/views/shared/_common_edition_attributes.html.erb
- config/locales/en.yml
Remove elements that come up in searches for `'t` in the interface so it's easier for content designers to find negative contractions in body text.
> Remove contractions from interface

- lib/service_sign_in/check-update-company-car-tax.en.yaml
- This service is being onboarded to Secure Credentials Platform.
- Change of URL link requested by Sophie Davies, Zendesk ticket #2744164 (https://govuk.zendesk.com/agent/tickets/2744164)
> Change link for 'Sign in with Government Gateway' for company car tax

- app/views/layouts/application.html.erb
I previously broke this by responding a bit too aggressively to a
warning emitted from many of the tests:
```
DEPRECATION WARNING: The asset "favicon.png" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
```
Turns out the asset was in the pipeline but it couldn't be found easily.
This can be resolved by amending the path to include
`govuk_admin_template/`.
> Fix favicon not showing

- app/presenters/formats/completed_transaction_presenter.rb
- app/views/completed_transactions/_fields.html.erb
- lib/presentation_toggles.rb
- test/integration/completed_transactions_create_edit_test.rb
- test/models/completed_transaction_edition_test.rb
There is a department request to add another promotion option 'MOT reminders' to the `completed transaction` format.
It works in the same way as the `organ_donor` option, where you can select it to be the promotion for any `completed transaction` done page (for example https://www.gov.uk/done/vehicle-tax)
Available `promotion_choice` options:
- none
- organ_donor
- register_to_vote
- mot_reminder
Related PRs:
https://github.com/alphagov/govuk-content-schemas/pull/747
https://github.com/alphagov/frontend/pull/1488
Trello card: [Request for new option in Completed Transaction 'promotion' slot](https://trello.com/c/fQQYxNIK/70-request-for-new-option-in-completed-transaction-promotion-slot)
Before:
After:
> Add new Completed Transaction "promotion" option

- app/services/publish_service.rb
- test/unit/services/publish_service_test.rb
GDS is responsible for everything published through publisher.
This uses link-set links for consistency with other publishing
apps (https://docs.publishing.service.gov.uk/apis/publishing-api/link-expansion.html#patch-link-set---link-set-links)
In publisher, other kinds of links are set through a separate form, so we need
to add in another call to make sure the primary org gets set.
Trello: https://trello.com/c/Z6nv4TjA/313-set-primary-org-in-mainstream-publisher
> Set primary publishing organisation on publish

- lib/service_sign_in/check-update-company-car-tax.en.yaml
Replaces https://github.com/alphagov/publisher/pull/853
Update link to 'create account' so it will work with the Government Gateway replacement when it's added to this service.
(Note: the link to the sign in to this service has already been updated.)
> Update link for Government Gateway replacement

- lib/service_sign_in/check-update-company-car-tax.cy.yaml
https://trello.com/c/NzkPq091/166-4-content-prs
Replaces #852 
Updated the 'login with' and 'create account' links to Government Gateway so they will work with the Government Gateway replacement when it is added to this service.
> Updated links for Government Gateway replacement

- lib/service_sign_in/check-update-company-car-tax.cy.yaml
Update the 'login with' and 'create account' links to Government Gateway so they will work with the Government Gateway replacement when it is added to this service.
> Update links for Government Gateway replacement

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
Change text on service sign in pages for company-car-tax, personal-tax-account and check-income-tax.
No changes made to the file-self-assessment service sign in page due to the difference in user journey options.
No change to layout or functionality of the page, just content changes to make the journey consistent.
https://govukverify.atlassian.net/browse/HUB-131
The change required is to update the copy on the following service interstitial pages:
Personal Tax Account - https://www.gov.uk/personal-tax-account/sign-in/prove-identity
Check This Year’s Tax Estimate - https://www.gov.uk/check-income-tax-current-year/sign-in/prove-identity
Check Company Car Tax - https://www.gov.uk/update-company-car-details/sign-in/prove-identity
No change to self-assessment due to the difference in user …
> HUB-131: Amend copy on service sign in pages for consistency.

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/file_self_assessment.en.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
Add a description paragraph that will be displayed under the title on each of the 4 services using the service sign in pattern, each description includes the service specific text. This "description" is already present in the example yaml, the schema and on the page template on government-frontend but was hitherto unused. Should this prove to be a good pattern according to the base line test we will add a description to the welsh pages as well.
https://govukverify.atlassian.net/browse/HUB-143
solo: @rachelthecodesmith
> HUB-143: Add description to service sign in pages

- lib/fact_check_email_handler.rb
- lib/mail_fetcher_config.rb
- test/integration/fact_check_email_test.rb
- test/unit/mail_fetcher_config_test.rb
https://trello.com/c/MjhoqAug/168-investigate-how-mainstream-publisher-should-be-checking-for-emails-on-integration-2
The environment var `RUN_FACT_CHECK_FETCHER` is set per environment to control processing of fact check emails.
The [previous implementation used this var to determine whether or not to set the
imap details](https://github.com/alphagov/publisher/blob/master/lib/mail_fetcher_config.rb#L9) but not to prevent attempts to process the emails on the server.
So `Mail#all` would attempt to retrieve mail based on defaults and this would result in a [connection refused error on localhost:110](https://sentry.io/govuk/app-publisher/issues/523285917/?query=environment:integration-blue-aws).
The PR alters the behaviour to a no-op if the env var is not set.
> Process mail based on env var

- app/controllers/editions_controller.rb
- app/services/republish_service.rb
- app/services/update_service.rb
- app/workers/update_worker.rb
- test/functional/editions_controller_test.rb
- test/unit/services/republish_service_test.rb
- test/unit/workers/update_worker_test.rb
Trello: https://trello.com/c/bIF8U0cL/184-last-updated-timestamp-not-updating-on-helppage-format-2
We've seen issues with the publishing process from Publisher to Publishing API which can cause the last update to a document to arrive after it has been published - this ends up publishing a document that isn't what the publisher specified and creating an unexpected draft of the full data.
To prevent this we've updated the update and publish process to run a single asynchronous job. This can perform both steps rather than creating two jobs and is no longer vulnerable to ordering issues.
> Stop running update and publish asynchronously

- lib/service_sign_in/check-update-company-car-tax.cy.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/personal-tax-account.cy.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
This fixes the URLs for the personal tax account and check car tax service sign in pages as requested by HMRC.
[Trello Card](https://trello.com/c/NHOsioPD/416-30-maygovernment-gateway-url-changes)
> Update Government Gateway URLs for various pages

- app/assets/stylesheets/bootstrap_and_overrides.scss
https://trello.com/c/KIZW45MY/191-modals-on-the-edition-form-in-publisher-only-work-on-the-edit-tab
Modal forms are embedded in the edit tab, when this tab is hidden with
`display: none`  they can't be displayed as any child elements cannot override this rule.
Using visibility modifier instead allows a parent to be hidden and a child to be shown.
> Use visibility modifier to reveal modal forms

- app/services/knowledge_api.rb
- app/services/knowledge_api.yml
- lib/tasks/publishing_api.rake
- test/unit/services/knowledge_api_test.rb
Running this rake task creates a new content item at https://www.gov.uk/api/content/knowledge-alpha. It is currently populated with the content of a number of high-profile guides in a structured format.
- Minimum wage rates from https://www.gov.uk/national-minimum-wage-rates
- Income Tax rates and bands from https://www.gov.uk/income-tax-rates
- Self Assessment tax return deadlines from https://www.gov.uk/self-assessment-tax-returns/deadlines
This is part of an experiment. We're currently working with one of the voice providers (starts with an A) to see if we can get GOV.UK facts directly into the knowledge engine that underpins the service. We've checked this data format with them, and they said that they would be able to consume this.
Obviously this isn't a very scalable solution - the …
> Create experimental "knowledge API"

- app/models/artefact.rb
- app/views/shared/_metadata.html.erb
- test/models/artefact_test.rb
This restriction on editing slugs comes from https://github.com/alphagov/govuk_content_models/commit/2f82275027300fc78924f5227ae1dce6fb3e0a5c, copied into this repository when that was retired, and the original commit message from 2012 justifies the change by reference to Panopticon, which has since been retired.
I tried it on integration, and it seemed to work with a guide, even the subpages.  I suspect there's no reason to keep the restriction any more.
This will allow publishers to self-serve on slug changes in publisher from now on.
---
Related to this [Trello card](https://trello.com/c/6ZHEUpB9/228-change-slug-of-uk-residence-for-eu-citizens-guide)
> Allow editing artefact slugs

- db/migrate/20180712141700_fix_gss_codes_for_some_councils_in_existing_support_schemes.rb
Following on from https://github.com/alphagov/mapit/commit/6df21ef1632ab11e29a5188d0591602137c06db9, two councils (Fife and Perth & Kinross) have recently changed their borders.
As well as updating in MapIt, the data also need updating here in Publisher to reflect the new codes.
https://trello.com/c/dql5PCnX/283-update-mapit-data
> Fix GSS codes for two councils in Scotland with recent border changes

- app/models/edition.rb
To determine the `public_updated_at` of an edition, we find the latest major update of the artefact and use the `updated_at` of that date. Unfortunately, the query is missing editions in the archived state, meaning that they were once published but have since been superseeded. We need to include these in the query to make sure that we find the most recently `updated_at`, at the moment it will miss any archived editions (which will be all the previous editions) and always get the `updated_at` from the first published edition.
> Include archived editions in major updates query

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
Remove description text from personal tax account, update company car
tax and check income tax pages. This text was added as part of a
baseline test (HUB-143) and has made no improvement. This commit removes
the text. Note, no changes have been made to the self assessment page as
this page has always had description text and follows a slightly
different pattern.
solo: @rachelthecodesmith
> HUB-209: Remove description text from service sign in pages

- Jenkinsfile
- app/controllers/publications_controller.rb
- config/brakeman.ignore
- lib/licence_content_importer.rb
- lib/licence_identifier_migrator.rb
This enables Brakeman to allow us to automatically check for security vulnerabilities.
It also fixes a few existing warnings, more detail about each one in the respective commit.
[Trello Card](https://trello.com/c/JyrOAef3/363-fix-sql-injection-vulnerabilities-in-govuk-applications)
> Enable Brakeman

- app/assets/stylesheets/sortable_table.scss
This commit changes the sortable table stylesheet to correctly use the Rails asset pipeline for images.
> Fix location of assets

- app/controllers/editions_controller.rb
- app/models/guide_edition.rb
- app/presenters/formats/guide_presenter.rb
- app/views/guides/_fields.html.erb
- test/integration/guide_create_edit_test.rb
- test/unit/presenters/formats/guide_presenter_test.rb
Supercedes #914.
On some guides that occur within a step by step navigation, the guide navigation elements are conflicting with the step navigation, or needlessly duplicating them. This adds an option to publisher to allow content managers the ability to hide the guide navigation elements if that part is inside a step by step navigation.
Example of a guide part currently:
The same page but with this option turned on:
What this looks like in publisher:
**This PR is a work in progress**. Also I've not made a change to publisher before, so any suggestions welcome.
Related change to content schemas: https://github.com/alphagov/govuk-content-schemas/pull/802
Trello card: https://trello.com/c/RNsA7E4Q/763-hide-chapter-navigation-on-mainstream-guides
> Add hide chapter navigation option to guides

- app/presenters/formats/service_sign_in_presenter.rb
- lib/service_sign_in/check-state-pension.en.yaml
- test/support/factories.rb
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
Adds GA tracking id to specific service sign in pages so that traffic flow between GOV.UK and Verify can be analysed.
Depends on https://github.com/alphagov/govuk-puppet/pull/8125
> Add ga tracking code to check state pension signin

- lib/service_sign_in/file_self_assessment.cy.yaml
The old slug redirects to this new one, so the rake task to publish this content is failing.
> Change Welsh start page for self-assessment

- app/presenters/formats/service_sign_in_presenter.rb
- lib/service_sign_in/check-state-pension.en.yaml
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
Enable cross domain tracking for DWP's GA property from CySP pages.
> Configure dwp xdomain params

- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
These values are used by forms containing radio groups to enable cross domain tracking.
* Also adds cross domain tracking for buttons in Welsh translation of create-account page
> Add tracking code and name to choose sign in forms

- app/presenters/formats/service_sign_in_presenter.rb
- lib/service_sign_in/example.en.yaml
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
Missed in https://github.com/alphagov/publisher/pull/955 this presents the new fields to the publishing API.
> Include tracking_code and tracking_name in service sign in payload

- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
Govspeak doesn't support the additional `data-tracking-track-page-view` attribute which can be used to disable sending pageviews and enable sending events to the cross domain tracker.
As we're currently only using this functionality for one sign in page it's not worth extending govspeak.
> Use native HTML for check-state-pension create account buttons

- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
Depends on https://github.com/alphagov/static/pull/1554
Instead of being explicit about sending page views, use an updated data attribute name to be explicit about sending an event (for cross domain tracking).
> Use event tracking data attr for check-state-pension

- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
... via newly added property. (See https://github.com/alphagov/govuk-content-schemas/pull/823)
Instead of using the tracking domain from the option url, we'll set it directly on the tracking form.
> Configure tracking domain for check-state-pension

- lib/service_sign_in/check-income-tax.cy.yaml
This adds a new sign in page in Welsh to support a translated version
of https://www.gov.uk/check-income-tax-current-year that will appear
at https://www.gov.uk/gwirioch-treth-incwm-ar-gyfer-y-flwyddyn-bresennol
https://govuk.zendesk.com/agent/tickets/3423986
> Add Welsh sign in page

- app/assets/javascripts/modules/ajax_save_with_parts.js
- app/controllers/editions_controller.rb
- app/helpers/editions_helper.rb
- app/models/edition.rb
- app/models/transaction_edition.rb
- app/models/variant.rb
- app/models/varianted.rb
- app/presenters/formats/transaction_presenter.rb
- app/views/shared/_transaction_variant.html.erb
- app/views/transactions/_fields.html.erb
- test/integration/adding_variants_to_transactions_test.rb
- test/integration_test_helper.rb
- test/models/artefact_test.rb
- test/models/varianted_test.rb
- test/support/factories.rb
- test/unit/presenters/formats/transaction_presenter_test.rb
This commit adds a new concept named "variants" to transaction pages. Variants are technically similar to "parts", which are used for guides and other document types.
For transaction pages, variants allow transaction pages to respond to URLs of the form www.gov.uk/transaction/variant and display different page text and button targets based on the slug.
The primary use of this will initially be to allow GOV.UK Verify journeys which lead directly to a single IDP.
RFC: https://github.com/alphagov/govuk-rfcs/pull/97
> Allow variants of transaction pages

- lib/service_sign_in/check-income-tax.cy.yaml
- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- lib/service_sign_in/check-update-company-car-tax.cy.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/file_self_assessment.cy.yaml
- lib/service_sign_in/file_self_assessment.en.yaml
- lib/service_sign_in/personal-tax-account.cy.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
The Verify Hub supports journey hints to redirect users to the right journey flows
(registration, sign-in or eIDAS). However, the required hints are not being
implemented/passed by the services. We have developed a mechanism which
allows us to record the hint value (the option they selected on the GOV.UK
sign-in pages) by 'bouncing' the user via Verify first.
> HUB-378: Update Verify redirect links

- app/lib/services.rb
Trello: https://trello.com/c/2IdzHdtp
Related to: 
* https://github.com/alphagov/govuk-puppet/pull/8488
* https://github.com/alphagov/link-checker-api/pull/227
Passes the bearer token needed to authenticate with link-checker-api using signon.
> Add bearer tokens for link-checker-api authentication

- Gemfile
- Gemfile.lock
- app/assets/javascripts/modules/ajax_save.js
- app/assets/javascripts/modules/ajax_save_with_parts.js
- spec/javascripts/spec/ajax_save.spec.js
- spec/javascripts/spec/ajax_save_with_parts.spec.js
This upgrades Jasmine to the latest version, requiring a few changes to the specs.
-  a new callback spy to prevent a form submission from attempting to navigate to a non-exsistant path.
- stubs jQuery with a `collapse` function from Bootstrap, to prevent order-dependent failures if Bootstrap has not already been loaded by Jasmine.
- renames a custom jQuery `error` event to `errors`. This mitigates an issue where jQuery does not correctly resolve the handler by not setting `event.result` to `false` and therefore not calling `preventDefault`. 
```
handle = ontype && cur[ ontype ];
if ( handle && handle.apply && acceptData( cur ) ) {
event.result = handle.apply( cur, data );
if ( event.result === false ) {
event.preventDefault();
...
```
This ultimately results in Jasmine presenting the …
> Upgrade Jasmine 2.5.2 => 3.3.0

- lib/service_sign_in/claim-rural-payments.en.yaml
Rural Payments expressed their interest in using the standard
GOV.UK sign-in page for their service. They currently offer two login options:
1. using their Customer Reference Number (CRN)
2. using GOV.UK Verify
This adds the new schema for that page. They do not have a welsh version and
the Create account page links to an external page (compared to other sign-in pages)
NOTE: I'm having issues running this locally so I'd ask if someone could verify the schema doesn't require the create account bit and works as expected?
> ZD-3566774: Add sign-in page for Rural Payments

- lib/service_sign_in/check-income-tax.cy.yaml
- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- lib/service_sign_in/check-update-company-car-tax.cy.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/claim-rural-payments.en.yaml
- lib/service_sign_in/file_self_assessment.cy.yaml
- lib/service_sign_in/file_self_assessment.en.yaml
- lib/service_sign_in/personal-tax-account.cy.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
As of 1st March, they will no longer be acting as identity providers for Verify.
See https://trello.com/c/vi7RV11M
> Remove Royal Mail and Citizensafe

- test/integration/adding_parts_to_guides_test.rb
- test/integration/adding_variants_to_transactions_test.rb
- test/integration/edition_history_test.rb
- test/integration/edition_major_change_test.rb
- test/integration/edition_workflow_test.rb
- test/integration/mark_edition_in_beta_test.rb
- test/integration/root_overview_test.rb
- test/integration/user_search_test.rb
- test/integration_test_helper.rb
Swaps the intent of tests so that we don't invoke capybara's wait time unless it's desired.  
For example, if we don't want to see a selector, then we should use `assert page.has_no_css?` rather than `refute page.has_css?`.  The latter will cause capybara to wait until the `default_max_wait_time`.
Also removes a couple of duplicate tests
Should speed builds up from ~13 mins to ~8 mins
https://ci.integration.publishing.service.gov.uk/job/publisher/job/speed-up-tests/buildTimeTrend
> Speed up tests

- lib/tasks/publishing_api.rake
If there is a problem talking to the publishing-api, it may be necessary to manually republish an edition to the publishing-api.
[Trello Card](https://trello.com/c/gnK6FhQb/828-gather-current-convenience-scripts-rake-tasks-that-might-help-during-brexit-publishing)
> Add a Rake task for republishing a specific edition

- app/services/knowledge_api.yml
These values have been updated to match the content here: https://www.gov.uk/national-minimum-wage-rates#current-rates
The knowledge_api is used to tell Alexa about important values on GOV.UK so we should keep this up to date. (Check it out at https://www.gov.uk/api/content/knowledge-alpha)
We'll need to republish the content item on 1st April by running:
```
rake publishing_api:publish_knowledge
```
against publisher on a backend box.
> Update knowledge api minimum wage rates

- app/assets/stylesheets/forms.scss
- app/controllers/editions_controller.rb
- app/presenters/formats/completed_transaction_presenter.rb
- app/views/completed_transactions/_fields.html.erb
- lib/presentation_toggles.rb
- test/models/completed_transaction_edition_test.rb
- test/unit/presenters/formats/completed_transaction_presenter_test.rb
The content of this promotion page will be changing to include two URLs, an opt in and an opt out URL.
At the moment the old URL is still allowed as a parameter until all the pages have converted to use only the opt in and opt out URLs.
This depends on alphagov/govuk-content-schemas#910.
[Trello Card](https://trello.com/c/HFsNGxTy/1088-investigate-organ-donation-promos-on-done-pages)
> Add opt in and opt out URLs for completed transactions

- app/models/artefact.rb
As it can occur when there is no draft to discard.
> Catch GdsApi::HTTPUnprocessableEntity when discarding drafts

- app/controllers/editions_controller.rb
- config/brakeman.ignore
- config/initializers/cookies_serializer.rb
- test/integration/downtime_integration_test.rb
When a user enters url in an invalid format (eg ‘redirect-to’, ‘www.gov.uk/redirect-to', ‘gov.uk/redirect-to') “Something went wrong” error was displayed, the Edition status was set to “Archived” but the page was available to view and no redirect was created.
This makes the `make_govuk_url_relative` more resilient and makes it handle input such as ‘www.gov.uk/redirect-to', ‘gov.uk/redirect-to'.
A validations is also added to ensure that `make_govuk_url_relative` returns url in a correct format.
When a user enters a string that cannot be correctly formatted, a message will be displayed.
 
**Related Zendesk tickets**
- https://govuk.zendesk.com/agent/tickets/3782482
- https://govuk.zendesk.com/agent/tickets/3769569
> Update regex and add validation for redirect_url

- Gemfile
- Gemfile.lock
- app/models/artefact.rb
- app/models/artefact_external_link.rb
- app/models/campaign_edition.rb
- app/models/guide_edition.rb
- app/models/transaction_edition.rb
- app/models/variant.rb
- app/models/video_edition.rb
- test/models/artefact_external_link_test.rb
- test/models/artefact_test.rb
- test/models/campaign_edition_test.rb
- test/models/transaction_edition_test.rb
- test/models/video_edition_test.rb
- test/unit/guide_edition_test.rb
If a content designer enters a URL with whitespace, this gets sent to the Publishing API, which refuses the request. Publisher doesn't surface this error to the content designer, so it appears as though the document has published correctly when actually it hasn't.
[Trello Card](https://trello.com/c/vZXmbYWH/1290-3-remove-trailing-space-from-urls-in-publisher)
> Trim whitespace from URLs

- app/presenters/primary_listing_presenter.rb
- app/views/root/index.html.erb
- test/integration/root_overview_test.rb
This adds a link above the list of publications informing content designers that step by steps awaiting review can be found in Collections Publisher.
Not to be merged until the 2i process is fully implemented in Collections Publisher.
Trello card: https://trello.com/c/4TBohVzN/34-add-link-for-sbs-review-queue-to-mainstream-publisher
> Add link to Collections Publisher for step by step reviews

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/file_self_assessment.en.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
Once there was only Germany connected, then there was Italy too.  Now there are many countries and the message needs to be more generic.
The existing Welsh translation is the generic message we're using so no change is required there.
> EID-1753 Be more generic when refering to European identity schemes.

- app/views/completed_transactions/_fields.html.erb
- lib/presentation_toggles.rb
- The government has a goal to reach zero carbon emissions by 2050, and
electric cars are part of that.
- Content designers can now select "electric vehicles" as their promo of
choice.
- While this only needs to be on `/done/vehicle-tax` and
`/done/check-vehicle-tax` pages, the easiest way given that none of
these pages are harcoded in `frontend` anymore, is a Publisher
toggleable promo selection.
TODO:
Relevant `govuk-content-schemas` PR: https://github.com/alphagov/govuk-content-schemas/pull/929.
https://trello.com/c/FmE5xU1p/1478-3-add-new-bespoke-message-to-specific-completed-transaction-pages
> Add a new done page promo choice for electric vehicles

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/editions_controller.rb
- app/decorators/user_search_edition_decorator.rb
- app/helpers/application_helper.rb
- app/models/workflow.rb
- app/traits/attachable.rb
- app/traits/recordable_actions.rb
- config/environments/development.rb
- config/initializers/current_release_sha.rb
- config/initializers/email_groups.rb
- config/initializers/fact_check.rb
- config/initializers/mapit.rb
- config/initializers/new_framework_defaults.rb
- config/initializers/session_store.rb
- config/routes.rb
- lib/fact_check_mail.rb
- lib/tasks/licence_finder.rake
- lib/tasks/lint.rake
- test/unit/content_workflow_presenter_test.rb
- test/unit/fact_check_message_processor_test.rb
Docs: https://docs.publishing.service.gov.uk/manual/migrate-from-govuk-lint.html
Trello: https://trello.com/c/Z8J455zg/1579-migrate-from-govuk-lint
In some cases, some of the rubocop cops have been disabled, rather than
addressing the issues.
This is not the right time to address these issues more extensively. We
had a conversation about this in the Platform Heath team and we agreed
that refactoring this code is not a priority right now, but there is a
Trello card to capture this:
https://trello.com/c/VNiRPVTP/1385-solve-publisher-linting-issues
> Migrate from govuk-lint to rubocop-govuk

- app/models/artefact.rb
- app/models/edition.rb
- test/integration/delete_edition_test.rb
Previously Publisher only deleted a draft from publishing-api when it was
the first edition of an Artefact and didn't have any previous editions
as this callback fired when deleting the parent Artefact.
The commit changes the code so whenever a draft is deleted then the
draft is also deleted from publishing-api, this is the correct behaviour
as previously it meant old drafts would linger in publishing-api when
they've been removed from Publisher leading to strange errors when the
new draft and deleted draft didn't match in pub-api. An error seen
recently was due to mismatched URL's between old (deleted)
and new draft. I assume this just works and overwrites the deleted draft
when the url isn't altered for a new draft.
This code also allows the deletion of other publisher specific states, …
> Delete drafts from pub-api on deletion

- app/assets/javascripts/modules/ajax_save_with_parts.js
- spec/javascripts/spec/ajax_save_with_parts.spec.js
When editing an edition, updates are made via an ajax request. Upon deleting a part, the part is hidden in the DOM. Although marked as "destroyed" in the DOM and successfully deleted from the database, subsequent update requests include the part details in the params. This caused a database error as the part no longer exists, resulting in a "Something gone's wrong" message. The user would have to refresh their page and lose any edits made since a deletion.
This PR ensures that, after a successful update, any deleted parts are not just hidden but removed from the DOM, to prevent their details being included in request params.
[trello](https://trello.com/c/ibsbiyZ4/1716-5-investigate-and-fix-the-bug-that-deletes-parts-in-publisher)
> Remove deleted parts from the DOM after successful AJAX requests

- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- button class (from toolkit via static) is being deprecated)
- a [recent change to the components gem](https://github.com/alphagov/govuk_publishing_components/pull/1282) allows this class swapping to work, otherwise would have left the button with illegible blue text
These buttons are used on e.g. https://www.gov.uk/check-state-pension/sign-in/create-account
Trello card: https://trello.com/c/d8D7JTJE/203-remove-design-patterns-buttons-from-static
> Replace button class

- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/skip_review.text.erb
- app/views/shared/_edition_activity_fields.html.erb
- config/initializers/email_groups.rb
- lib/govuk_content_models/action_processors/base_processor.rb
- test/functional/noisy_workflow_test.rb
To reduce the possibility of force publishing without anyone noticing we have added:
- Warning text to the skip review dialog box
- An email to be sent out when review is skipped
Trello card: Trello card: https://trello.com/c/d8D7JTJE/203-remove-design-patterns-buttons-from-static
> Alert users when skipping review

- app/views/noisy_workflow/skip_review.text.erb
Changing who the email is signed off from from Winston to the GOV.UK publisher app to be more clear about where the email has come from.
Trello card: https://trello.com/c/jUuJwRLW
> Remove mention of Winston from skip review emails

- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/skip_review.text.erb
The url in the skip review email was using the mailer default url (which is gov.uk) this corrects it by using plek to get the publisher url to use as the host.
https://trello.com/c/jUuJwRLW
> Fix url in skip review emails

- test/functional/link_check_reports_controller_test.rb
- test/integration/edition_link_check_test.rb
- test/integration/edition_workflow_test.rb
- test/integration/tagging_test.rb
- test/support/holidays_test_helpers.rb
- test/support/tag_test_helpers.rb
- test/unit/lib/service_sign_in_yaml_validator_test.rb
- test/unit/lib/sync_checker_test.rb
- test/unit/lib/working_days_calculator_test.rb
- test/unit/organisation_content_presenter_test.rb
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
- test/unit/services/link_check_report_creator_test.rb
Fixing many warnings about deprecated methods including:
- link_checker_api_create_batch
- calendars_has_a_bank_holiday_on
- calendars_has_no_bank_holidays
- publishing_api_has_lookups
- publishing_api_has_linkables
- content_store_has_item
- content_store_does_not_have_item
> Fix deprecation warnings in tests

- app/mailers/multi_noisy_workflow.rb
- app/mailers/noisy_workflow.rb
- lib/govuk_content_models/action_processors/base_processor.rb
- test/functional/multi_noisy_workflow_test.rb
- test/functional/noisy_workflow_test.rb
- test/integration/edition_workflow_test.rb
- test/integration/local_transaction_create_edit_test.rb
Method based on https://github.com/alphagov/short-url-manager/pull/451
WIP: I still need to add new tests including some to replace those made obsolete by this change.
https://trello.com/c/QYkWTpbv/1889-publisher-send-one-email-per-recipient
> Add MultiNoisyWorkflow to loop over addresses and instantiate NoisyWorkflows for each

- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/request_fact_check.text.erb
- config/application.rb
- config/environments/production.rb
- config/secrets.yml
- test/functional/multi_noisy_workflow_test.rb
- test/functional/noisy_workflow_test.rb
- test/unit/edition_clone_test.rb
- test/unit/guide_edition_test.rb
Reverts alphagov/publisher#1238
Unfortunately we have to revert this until we've set up the Google Group for sending emails in integration and staging.
> Revert "Use mail-notify gem to deliver via GOV.UK Notify"

- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/request_fact_check.text.erb
- config/application.rb
- config/environments/production.rb
- config/secrets.yml
- test/functional/multi_noisy_workflow_test.rb
- test/functional/noisy_workflow_test.rb
- test/unit/edition_clone_test.rb
- test/unit/guide_edition_test.rb
Reverts alphagov/publisher#1246 which was a reversion of alphagov/publisher#1238.
https://trello.com/c/72QJ9IBL/1877-publisher-use-notify-instead-of-ses
> Use mail-notify gem to deliver via GOV.UK Notify

- app/mailers/noisy_workflow.rb
- test/functional/noisy_workflow_test.rb
Notify doesn't allow setting the from address, and the Notify gem uses a different parameter name for setting the reply-to address, so both of these were being lost when we migrated. Removed the superfluous `from` and renamed `reply_to` to `reply_to_id`.
https://trello.com/c/MR3jrlX2/1878-5-publisher-replace-ses-in-email-receipt-workflow-%F0%9F%8D%90
> Use correct parameter name for reply-to address

- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/request_fact_check.text.erb
- config/application.rb
- config/environments/production.rb
- config/secrets.yml
- test/functional/multi_noisy_workflow_test.rb
- test/functional/noisy_workflow_test.rb
- test/unit/edition_clone_test.rb
- test/unit/guide_edition_test.rb
We've spotted a problem where the reply-to address sent via Notify isn't working correctly, so we have to revert this for now until we decide how best to proceed.
> Revert to send emails using SES

- app/mailers/noisy_workflow.rb
- config/fact_check.yml
- config/initializers/fact_check.rb
- lib/fact_check_config.rb
- lib/fact_check_email_handler.rb
- test/integration/edition_workflow_test.rb
- test/integration/fact_check_email_test.rb
- test/unit/fact_check_config_test.rb
This is in addition to checking the `to` address and in preference to it, in order to support Notify which doesn't allow setting unique reply-to addresses.
https://trello.com/c/MR3jrlX2/1878-5-publisher-replace-ses-in-email-receipt-workflow-%F0%9F%8D%90
> Look for ID in subject field of fact check replies

- app/mailers/noisy_workflow.rb
- config/fact_check.yml
- config/initializers/fact_check.rb
- lib/fact_check_config.rb
- test/unit/fact_check_config_test.rb
This is expected to be configured by Puppet.
The current code uses an email address pattern in which the environment    (production/staging/integration) is embedded, and uses this both to    parse incoming emails and generate outgoing emails (the environment is    part of an opaque string as far as the app is concerned).
However, here I've made the prefix configurable but not the subject as a    whole: partly because the subject was already defined in code and not    configurable through Puppet, and partly because trying to both parse and    generate from the same string is needlessly complex.
The prefix can be left blank (e.g., in production).
https://trello.com/c/MR3jrlX2/1878-5-publisher-replace-ses-in-email-receipt-workflow-%F0%9F%8D%90
> Make the ID prefix in the subject configurable

- app/models/edition.rb
- test/models/edition_test.rb
A pain point we experienced with publisher was that the in_beta flag is
not persisted onto new editions. This meant that it was easy to lose the
beta status.
I'm assuming that the omission of this field just represents a simple
oversight rather than any concious decision to exclude this.
> Copy in_beta field when cloning editions

- data/local_services.csv
Trello: [Set up new service in local links manager for local authority covid pages](https://trello.com/c/n5l5Ahwp/356-set-up-new-service-in-llm-for-local-authority-covid-pages)
Allow Covid-19 outbreak related local links to be added.
Coronavirus has been coded as "Current emergency situation - health".
See https://standards.esd.org.uk/?uri=service%2F1287 for more details.
> Add Coronavirus Service

- lib/fact_check_config.rb
- test/unit/fact_check_config_test.rb
Previously the regex would look for an exact match based on what was sent, pinned to the end of the string but not the start (to allow for 'Re:' and similar prefixes). However, it seems that in some cases there can also be text added to the end of the string (e.g., an ID added by the other party's own ticketing system) or even a complete modification of the subject, in which case all we can do is ask the user not to remove the ID.
I've made a few guesses as to what is an appropriate level of cautiousness: for example, this looks for any hexadecimal string surrounded by square brackes (and prefixed with an environment, if one is set); however, I've considered it to be an error if there's more than one match (because we can't be sure we'll pick the right one).
We could also try multiple …
> Improve regex for parsing an edition ID from a subject header

- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/request_fact_check.text.erb
- test/integration/edition_workflow_test.rb
This was failing to be included before due to some odd variable scoping issue (instance variables defined in `noisy_workflow.rb` weren't readable from the template). This way isn't perfect but should be clear enough — there won't be a prefix on the ID in the email body, but this would be in production and it's only intended to be human-readable anyway.
https://trello.com/c/EgwMYcXj/1987-3-update-publisher-interface-and-email-text-to-match-new-fact-check-workflow
> Ensure email body correctly includes message ID

- app/models/edition.rb
- app/views/shared/_history.html.erb
- config/fact_check.yml
- config/initializers/fact_check.rb
- lib/fact_check_config.rb
- test/integration/fact_check_email_test.rb
- test/unit/fact_check_config_test.rb
This allows us to stop showing the ID in the reply-to address we're giving to users, without actually yet disabling it for incoming messages.
The caveat is, though, that it should be compatible with both the `address_format` (at least, compatible with the existing gmail filters that assume that address format) and matching the address that the `reply_to_id` refers to. Neither of these is guaranteed to break things if they're different, but inconsistency is likely to complicate things and it's difficult or impossible to reliably ensure that they're compatible.
https://trello.com/c/EgwMYcXj/1987-3-update-publisher-interface-and-email-text-to-match-new-fact-check-workflow
> Read reply-to address from a separate environment variable

- app/mailers/noisy_workflow.rb
- app/views/noisy_workflow/skip_review.text.erb
Inserts name of the user who skipped review, and their reason, into the body of the email that is sent to admins.
[Trello](https://trello.com/c/IjmdeY7H/2002-2-iterate-skipreview-alert-email-in-publisher)
> Amend review skipped email content

- app/views/noisy_workflow/request_fact_check.text.erb
- test/integration/edition_workflow_test.rb
This is so that HMRC can manually set the reply address, as their system ignores the reply-to header.
https://trello.com/c/jCpYumNF/2009-include-reply-to-address-in-body-of-publisher-fact-check-emails
> Add the reply-to address to the body of the fact-check email and test it

- doc/fact-checking.md
- test/integration/edition_workflow_test.rb
We've been working in this area recently (and even had an incident) and having this documentation at the beginning would have been very helpful.
It's doesn't go into too much detail in terms of individual lines of code as I wanted to make sure this documentation remains accurate even if the code itself is refactored or changed.
[Trello Card](https://trello.com/c/IspoUGnj/1971-5-enable-fact-check-emails-in-integration-and-staging)
> Add some documentation on the fact check process

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
- Updated eligibility criteria for Gateway and Verify 
- Added examples of the most popular other services you can use each account for 
- Edited headings and buttons to make it clearer that users need to choose between two options
This is part of work on GOV.UK Verify user journeys, being done by the hub/eIDAS team. The new page content has been approved by HMRC.
[Jira ticket is here. ](https://govukverify.atlassian.net/browse/HUB-660?atlOrigin=eyJpIjoiMTkxNzU0MzY5YTc1NDc0Yzg5ZGE4NDQ3ZjlkMjAxMjUiLCJwIjoiaiJ9)
> Update create account page content

- lib/service_sign_in/personal-tax-account.en.yaml
'You'll need:' was being treated as a new YAML property instead
of part of the 'body:' YAML property.
Follow-on from #1300. 
Trello: https://trello.com/c/nP2Y2ztz/2043-content-pr-update-content-on-the-service-sign-in-pages
> Fix formatting

- .github/config.yml
In accordance with [RFC 126], we're configuring Dependabot to only
raise Pull Requests for the following three categories:
1. Security updates
2. Internal libraries
3. Framework libraries
Things have moved on slightly since the RFC; we're now using
[GitHub native] configs rather than the legacy `.dependabot`
approach. The syntax is slightly different to the example config
provided in the RFC but most of it is easily transferable.
For (1), there is no longer a config option, as
[security updates are configured in the GitHub repository][security]
'security' settings tab itself.
We've handled (2) and (3) in config, and have set it to only raise
PRs for direct updates, i.e. updates to subdependencies of the
named dependencies will not raise PRs. Unfortunately the
[default behaviour would be …
> Add Dependabot configuration

- app/helpers/paths_helper.rb
- app/models/edition.rb
- app/presenters/formats/edition_format_presenter.rb
- lib/tasks/set_auth_bypass_id.rake
- test/unit/edition_test.rb
- test/unit/helpers/admin/paths_helper_test.rb
- test/unit/presenters/formats/edition_format_presenter_test.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
Currently the auth bypass token is based off the ID of the edition, this means it's not possible to invalidate old tokens, if they were leaked for example. To support this, I've create a Rake task that populates the new field based on the existing method so existing editions will continue to work, but from now onwards, the tokens will be generated from a random UUID. See commits for more details.
[Trello Card](https://trello.com/c/oqQD7nOl/2053-5-improve-draft-access-mechanism-for-mainstream-publisher)
> Generate an auth bypass token for each edition

- lib/tasks/set_auth_bypass_id.rake
The `update` method performs validation, some editions are failing validation (mostly archived ones where they're not allowed to be edited). Although it shouldn't matter as `auth_bypass_id` only matters for draft editions, I would prefer that all editions have one so we can be confident the value won't ever be `nil`.
This follows on from #1313.
[Trello Card](https://trello.com/c/oqQD7nOl/2053-5-improve-draft-access-mechanism-for-mainstream-publisher)
> Use update_attribute in Rake task

- lib/tasks/set_auth_bypass_id.rake
In #1315 I changed the code to use `update_attribute` so it ignores the validation, but still runs the callback. Unfortunately there's a callback set up which performs validation which means this solution
doesn't work: https://github.com/alphagov/publisher/blob/35c2756693990798de7a6e3b0d15721c682a5b30/app/models/edition.rb#L391-L403
Instead we can use `set` which performs a single atomic operation on the database. See https://docs.mongodb.com/mongoid/current/tutorials/mongoid-persistence/#atomic for more details.
The task also takes only 2 minutes to run using `set` compared to 10 minutes with `update`.
> Use set in a Rake task

- app/helpers/paths_helper.rb
- app/models/edition.rb
- app/presenters/formats/edition_format_presenter.rb
- lib/tasks/set_auth_bypass_id.rake
- test/unit/edition_test.rb
- test/unit/helpers/admin/paths_helper_test.rb
- test/unit/presenters/formats/edition_format_presenter_test.rb
- test/unit/presenters/formats/generic_edition_presenter_test.rb
This follows on from #1313 to make various improvements to the auth bypass token. Specifically it adds a `content_id` field to the token for auditing and adds an expiration date of one month to the token. See individual commits for more details.
[Trello Card](https://trello.com/c/oqQD7nOl/2053-5-improve-draft-access-mechanism-for-mainstream-publisher)
> Improvements to the auth bypass token

- app/mailers/noisy_workflow.rb
- config/initializers/email_groups.rb
- lib/fact_check_email_handler.rb
- script/mail_fetcher
https://trello.com/c/uTeN3PfS/921-fact-check-emails-not-processed
Previously we used to collect fact check processing errors and send
them to an email address. The code for this appeared to be broken
(it wasn't sending an email), and in any case, we should be sending
all errors to Sentry, so they're in one place.
> Alert when fact check emails cannot be processed

- lib/fact_check_config.rb
- test/support/factories.rb
- test/unit/fact_check_config_test.rb
https://trello.com/c/uTeN3PfS/921-fact-check-emails-not-processed
In 568c72d8c98641977285fc6aa7b7909cfaaa1795, the regex for subject matching was changed. This has an unintended effect of blocking fact check responses being processed where the subject contained any other numbers in square brackets.
Therefore requiring the pattern to be exactly 24 characters, in order to improve matching of the string we are interested in.
> Scan for only the edition ID in fact check response subject

- config/fact_check.yml
- config/initializers/fact_check.rb
- lib/fact_check_config.rb
- lib/fact_check_email_handler.rb
- test/unit/fact_check_config_test.rb
Publisher used to link an email fact check to an edition via an edition
ID provided in the email address.
[This was replaced by instead preferring to match the edition ID from the subject
line](https://github.com/alphagov/publisher/pull/1256), which was a requirement of moving to GOVUK Notify as our e-mail service
Now that this preferred solution is in use, the old code can now be removed.
[trello](https://trello.com/c/D8NuPoX8/2078-2-remove-support-for-edition-ids-in-address-in-publisher)
> Remove support for email fact check reading edition ID from address

- Gemfile.lock
This resolves
[CVE-2020-14001](https://github.com/advisories/GHSA-mqm2-cgpr-p4m6)
[Trello](https://trello.com/c/H49ZOsu1/972-update-all-govspeak-depenendencies-in-govuk-apps)
> Bump govspeak to 6.5.6

- app/controllers/application_controller.rb
https://trello.com/c/AB5sPEMm/2121-5-handle-not-in-team-notify-error-in-mainstream-publisher
> Rescue bad request error and display a message

- app/controllers/artefacts_controller.rb
- app/views/shared/_metadata.html.erb
This should help when content is incorrectly marked as english, but
isn't actually english. I see no reason to restrict this in the
interface, I'm guessing it just wasn't considered when trying to merge
Panopticon in to Publisher.
> Enable updating the language of artefacts

- doc/fact-checking.md
Adds a link to the documentation for the relevant alert, to tie the documentation together.
> Adds link to relevant alert documentation

- .simplecov
- Gemfile
- Gemfile.lock
- test/test_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
Previously this used to require visiting the generated, static
webpage, and was surprisingly configured in a '.simplecov' file.
> Print coverage after running tests

- app/lib/fact_check_config.rb
- app/lib/fact_check_email_handler.rb
- test/unit/fact_check_config_test.rb
https://trello.com/c/R9ZJGaZR/2147-investigate-how-to-reduce-fact-check-email-alerts-caused-by-edition-id-being-manually-removed
> Look for item ID in body as well as subject of factcheck emails

- app/views/answers/_fields.html.erb
- app/views/campaigns/_fields.html.erb
- app/views/completed_transactions/_fields.html.erb
- app/views/help_pages/_fields.html.erb
- app/views/licences/_fields.html.erb
- app/views/places/_fields.html.erb
- app/views/shared/_transaction_variant.html.erb
- app/views/transactions/_fields.html.erb
- app/views/videos/_fields.html.erb
The formtastic gem adds a default rows value of 20 to textarea tags so add that back in after removal of the gem in 23fe204.
> Fix textarea heights after formtastic removal

- app/lib/fact_check_email_handler.rb
- test/integration/fact_check_email_test.rb
https://trello.com/c/R9ZJGaZR/2147-investigate-how-to-reduce-fact-check-email-alerts-caused-by-edition-id-being-manually-removed
> Fix type error in fact-check email handling

- config/routes.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
This ensures we correctly report this app as unhealthy if it cannot
connect to its database, which can happen on single instances [1].
While this may be incidentally covered by Smoke tests, it's clearer
if we call it out explicitly.
[1]: https://docs.google.com/document/d/1q0dmaRaK1pnoKK_EGikdstUOtBEiaCaswMYS9ITFbL0/edit
- Check your branch is being deployed in the [Release …
> Add additional healthcheck for MongoDB

- lib/tasks/local_transactions.rake
- test/unit/tasks/local_transactions_rake_test.rb
Change of LocalServiceImporter method from update to run missed in
local_transactions:update_services rake task.
> Correct local service importer method name

- app/controllers/reports_controller.rb
This file is in the `lib` directory which does not get auto loaded by Rails, so it needs to be required explicitly.
This was missed in https://github.com/alphagov/publisher/commit/4eba5eb381b6e243c88962a5bf9d84da3b12d7bd.
> Add missing require statement

- app/controllers/editions_controller.rb
- app/helpers/tabs_helper.rb
- app/lib/govuk_content_models/action_processors/approve_fact_check_processor.rb
- app/lib/govuk_content_models/action_processors/assign_processor.rb
- app/lib/govuk_content_models/action_processors/resend_fact_check_processor.rb
- app/lib/govuk_content_models/action_processors/send_fact_check_processor.rb
- app/lib/govuk_content_models/action_processors/skip_fact_check_processor.rb
- app/models/user.rb
- app/views/editions/show.html.erb
- app/views/shared/_common_edition_attributes.html.erb
- app/views/shared/_fact_check.html.erb
- app/views/shared/_fact_check_received.html.erb
- app/views/shared/_ready.html.erb
- test/functional/editions_controller_test.rb
- test/integration/edition_workflow_test.rb
- test/models/edition_test.rb
- test/support/factories.rb
- test/unit/tabs_helper_test.rb
This PR adds further functionality for users with `welsh_editor` permissions, following https://github.com/alphagov/publisher/pull/1360
Users must have correct permissions to:
*  assign other users to an edition. The assigned user must also have correct permissions. This option is hidden without correct permissions.
* destroy an edition.
* view an edition's admin page.
* see fact-check workflow buttons (the requests these buttons submit have already been addressed in the above PR)
[Trello](https://trello.com/c/Hq2qgwiI/2155-8-give-permission-in-publisher-for-welsh-teams-in-departments-to-update-only-welsh-content)
> Add restrictions for user with `welsh_editor` permissions

- app/controllers/application_controller.rb
- test/integration/edition_workflow_test.rb
The NotifyBadRequest error will only appear in non-Production environments where there are AllowLists for our Notify accounts to prevent sending e-mails to unverified addresses.
This PR aims to help content design colleagues better understand the error, and add confidence it will not effect users on the live site.
[Trello](https://trello.com/c/qWcOV9Y7/2261-improve-factcheck-email-error-message)
> Expand Notify Bad Request error message

- lib/service_sign_in/check-income-tax.cy.yaml
- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- lib/service_sign_in/check-update-company-car-tax.cy.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/file_self_assessment.cy.yaml
- lib/service_sign_in/file_self_assessment.en.yaml
- lib/service_sign_in/personal-tax-account.cy.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
Remove the option to sign into Verify with an eID from a connected European country
Due to EU Exit transition
Searched for the `?journey_hint=eidas_sign_in` url parameter, which routes a user to the Verify country picker page.
Deleted these entries.
I was unable to get the test suite to run locally, which is why this is in draft.
> Remove option to sign into Verify with a European ID

- app/services/unpublish_service.rb
- test/unit/services/unpublish_service_test.rb
https://govuk.zendesk.com/agent/tickets/4408343
Depends on: https://github.com/alphagov/publishing-e2e-tests/pull/405
Previously we defaulted to preserving sub-paths when redirecting a
part of an unpublishing, multi-part document. Example:
https://www.gov.uk/starting-to-import/moving-goods-from-eu-countries ->
https://www.gov.uk/import-goods-into-uk/moving-goods-from-eu-countries
because
www.gov.uk/starting-to-import ->
www.gov.uk/import-goods-into-uk
This switches to ignoring sub-paths and redirecting to the intended
destination, since the redirect destination is unlikely to have an
equivalent set of sub-paths, for the original multi-part document.
Note that this was actually the original behaviour [1], but seems to
have gotten lost in the transition to use Publishing API. Note also
that …
> Redirect to parent for multi-part documents

- app/views/local_transactions/_fields.html.erb
This field used to be a textarea and was mistakenly changed to a
text input on 25th September:
https://github.com/alphagov/publisher/commit/23fe2046ce136622e61083f4d67f9cf6e1ec4c86#diff-97ba2ccb37be2e3c9677e06479c533b447f523435d7a4ba056d743ebc94555e4R34-R49
It was clearly not intentional as the commit states:
> There should be no cosmetic change to the forms, as the relevant bootstrap classnames has been added to the HTML
However, the change has caused an issue whereby it is impossible
to write markdown across multiple lines. For example, beginning
with a heading `## If you live in Northern Ireland`, followed by
a section of content.
This is interfering with publishers' ability to publish updated
content. It is also not a one-off; see the 'More information'
field in …
> Make "More information" section a textarea

- app/models/edition.rb
- test/models/edition_test.rb
We have found some editions contain a `\u2028` (line separator) character when the content has been copy-and-pasted from certain applications. This gets rendered in different ways in different browsers (e.g. an extra space, or sometimes a square box containing "L SEP").
This removes those characters when an edition is saved, so they never get published.
Trello card: https://trello.com/c/YQFCDuP8
> Remove \u2028 (line separator) characters on save

- data/local_services.csv
Add a LocalService with an LGSL code 1827.
The service was created using a dummy LGSL code (100001).  We now have
a real LGSL code for this service (1827) and would like to use it
instead of the dummy code.
For safety and to ensure there is no interruption to the service we need
to add the 1827 service - leaving the 100001 service in-place - until
the switch is complete. At that point we can remove the 100001 service.
[Trello](https://trello.com/c/MRGj9keG/210-local-lookup-lateral-mass-test-apply-the-proper-assigned-service-code-1827-agreed-with-local-government-authority)
> Update LocalService LGSL code

- lib/service_sign_in/check-income-tax.cy.yaml
- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-state-pension.cy.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- lib/service_sign_in/check-update-company-car-tax.cy.yaml
- lib/service_sign_in/check-update-company-car-tax.en.yaml
- lib/service_sign_in/claim-rural-payments.en.yaml
- lib/service_sign_in/file_self_assessment.cy.yaml
- lib/service_sign_in/file_self_assessment.en.yaml
- lib/service_sign_in/personal-tax-account.cy.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
Experian, SecureIdentity and Barclays are disconnecting from Verify on
March 23rd 2021. This content needs to be deployed in synch with their
disconnection.
> HUB-815: Remove disconnecting Verify IDPs

- lib/tasks/local_service.rake
- test/lib/tasks/local_service_test.rb
What
Add a rake task to change the LGSL code on a LocalService and all of its Editions.
Why
We want to be able to change an existing LocalService's LGSL code.
[Trello](https://trello.com/c/MRGj9keG/210-local-lookup-lateral-mass-test-apply-the-proper-assigned-service-code-1827-agreed-with-local-government-authority)
> Add a rake task to change a LocalService LGSL code

- data/local_services.csv
What
Remove the service 100001 from data/local_service.csv.
Why
That service no longer exists.  It is now 1827.
[Trello](https://trello.com/c/MRGj9keG/210-local-lookup-lateral-mass-test-apply-the-proper-assigned-service-code-agreed-with-local-government-authority)
> Remove service 100001 from data/local_services.csv

- app/models/edition.rb
- test/models/edition_test.rb
Quick addition to the validation for publisher documents that means
documents without 'parts' that just have a 'body' are also
caught by the validation.
Related: https://trello.com/c/TGUvoJsP/2432-3-remove-l-sep-characters-from-already-published-publisher-content
Original PR: https://github.com/alphagov/publisher/pull/1416
> Modify publisher L-sep validation

- lib/tasks/remove_lsep_char_temp.rake
Temporary rake task to replace all "\u2028" characters for published editions
Trello: https://trello.com/c/TGUvoJsP/2432-3-remove-l-sep-characters-from-already-published-publisher-content
Co-authored-by: Callum Knights <callum.knights@digital.cabinet-office.gov.uk>
> Remove "\u2028" temporary rake rask

- app/controllers/healthcheck_controller.rb
- app/models/healthcheck/scheduled_publishing.rb
- config/routes.rb
- test/integration/healthcheck_test.rb
Once govuk-puppet has been updated, the old endpoint can be removed.
See the RFC for more details.
---
[Trello card](https://trello.com/c/tl6RV1el/723-improve-govuk-healthchecks)
> Separate out scheduled publishing check & add RFC 141 healthcheck endpoints

- config/application.rb
Currently, assets are served by [nginx](https://github.com/alphagov/govuk-puppet/blob/9da822c3bb38e6565e7835e66ecadc43cb35f025/modules/govuk/manifests/apps/publisher.pp#L154)
in EC2 while in ECS we'll serve assets using the same [`CloudFront and S3`](alphagov/govuk-infrastructure#192)
infrastructure across all the Rails apps.
Being able to set `config.asset_host` will allow the Publisher app to
point requests to its assets to the `CloudFront and S3` infrastructure.
While setting `config.assets.prefix`, will allow differentiation of assets
from different apps based on path in the same S3 bucket.
This change should be a no-op in the current platform because the
defaults for both of these config values is nil, and we won't set
these env vars with Puppet.
Ref:
1. [trello …
> Modify config to allow custom assets host and location

- Dockerfile
Following on from #1435 where we introduced the ability to configure
the ASSETS_PREFIX by environment variable, there is a need to build
the docker images with the ASSETS_PREFIX=/assets/publisher so that
publisher directs client to this prefix path for its assets which
are stored in a S3 bucket.
Ref:
1. [trello card](https://trello.com/c/XwlrmXRJ/458-enable-other-rails-app-to-serve-assets-the-new-way-ie-cloudfront-s3)
2. [govuk-infrastructure pr](alphagov/govuk-infrastructure#221)
> Precompile assets with prefix /assets/publisher

- app/controllers/sitemap_controller.rb
- app/models/edition.rb
- app/views/sitemap/index.xml.erb
- config/routes.rb
- test/functional/sitemap_controller_test.rb
- test/models/edition_test.rb
This adds a controller which renders a [sitemap.xml](https://en.wikipedia.org/wiki/Sitemaps) file containing just the URLs for pages published by this app. It's going to be given to a product called Siteimprove which the content team are using to run analysis on their pages.
I've intentionally not used the standard `/sitemap.xml` route, as it's not a sitemap of the Publisher app, it's a sitemap of the pages published by the app.
It's open to the public so that Siteimprove can access it, but we may need to re-think this in the future if it's starts getting indexed by other search engines. The work with Siteimprove is only going to be running for a year, so we might be able to remove it after that.
[Trello Card](https://trello.com/c/KmIPDJUQ/2540-5-publish-an-xml-feed-of-mainstream-urls)
> Add a sitemap.xml

- app/models/devolved_administration_availability.rb
- app/models/local_transaction_edition.rb
- app/presenters/formats/local_transaction_presenter.rb
- test/models/devolved_administration_availability_test.rb
- test/support/factories.rb
- test/unit/presenters/formats/local_transaction_presenter_test.rb
[Trello](https://trello.com/c/Kgr3I4Tz/401-store-devolved-administration-local-transaction-data-in-model-and-govuk-content-schema)
This work is part of a task to enable publishers to specify devolved administration (DA) service availability for local transactions. This PR models the data and was created as a result of a [spike implementation in Publisher](https://github.com/alphagov/publisher/pull/1451). 
[A related content schema has also been added](https://github.com/alphagov/govuk-content-schemas/pull/1060). This PR should NOT be merged until after the content-schema PR has been merged.
Makes use of Mongoid’s `embeds_one`. This allows data to be stored within a hash. It can then be queried from the parent object.
```
l = LocalTransactionEdition.new
l.scotland_availability
=> …
```
> Devolved administration availability modelling

- app/models/local_transaction_edition.rb
- test/models/local_transaction_edition_test.rb
[Trello](https://trello.com/c/TsRhfzNb/448-duplicate-devolved-administration-availability-values-when-new-editions-are-created)
Draft PR at the moment... i'll create a proper PR after testing the branch out on integration tomorrow (16/06) but feel free to start reviewing.
Devolved administration availability modelling was added in a [previous PR](https://github.com/alphagov/publisher/pull/1456).
A bug was discovered, in that the embedded fields in `DevolvedAdministrationAvailability` were not being copied when a new edition was created.
The reason for this is the `scotland_availability`, `wales_availability` and `northern_ireland` availability fields were not included in the array returned by the [type_specific_field_keys](https://github.com/alphagov/publisher/blob/main/app/models/edition. …
> Duplicate DA values for new editions

- app/controllers/reports_controller.rb
- app/presenters/all_urls_presenter.rb
- app/views/reports/index.html.erb
- config/routes.rb
- lib/csv_report_generator.rb
- test/unit/all_urls_presenter_test.rb
Generate a CSV report containing all URLs, not only top-level ones. This is based on an existing report, but with an extra iteration step to account for multi-part publications.
https://trello.com/c/fhtbsEgu/2528-create-a-mainstream-url-report-which-shows-all-urls
> Add all-urls report

- lib/tasks/temp_remove_landlord_immigration_check.rake
StartPages are now published in SmartAnswers, and this example is
leftover from before they were moved from Publisher.
There is now a need for Publisher to re-use the `landlord-immigration-check`
slug, and this new Artefact cannot be created while the slug is associated
with the old StartPage.
[trello](https://trello.com/c/4mogKZrw/2584-temporarily-take-down-check-if-someone-can-rent-your-residential-property-remove-the-start-page-button-replace-the-start-page-te)
> Add Temporary Rake task to remove old Artefact

- lib/tasks/temp_remove_landlord_immigration_check.rake
This temporary task has now been run in Production and so can be removed
Reverts alphagov/publisher#1474
> Revert "Add Temporary Rake task to remove old Artefact"

- app/assets/stylesheets/forms.scss
- app/controllers/editions_controller.rb
- app/models/local_transaction_edition.rb
- app/views/local_transactions/_fields.html.erb
In a [previous PR](https://github.com/alphagov/publisher/pull/1456/) we have adapted the [`LocalTransactionEdition`](https://github.com/alphagov/publisher/blob/3e083c9998692847cbb7325c0e9234684dc1be35/app/models/local_transaction_edition.rb) and [`DevolvedAdministrationAvailability`](https://github.com/alphagov/publisher/blob/3e083c9998692847cbb7325c0e9234684dc1be35/app/models/devolved_administration_availability.rb) models so that each `LocalTransactionEdition` has a 1:1 relationship with a Scotland, Wales & Northern Ireland `DevolvedAdministrationAvailability` instance.
We now need to update the user interface so that these devolved administration availability entries can be created & maintained.
We want to provide publishers with the means to specify whether a Local Transaction is only …
> Update the user interface to store, validate and retrieve the devolved administration data

- app/assets/javascripts/modules/ajax_save.js
- app/assets/stylesheets/forms.scss
- app/helpers/form_helper.rb
- app/models/local_transaction_edition.rb
- app/views/editions/_reviewer_field.html.erb
- app/views/licences/_fields.html.erb
- app/views/local_transactions/_devolved_administrations.html.erb
- app/views/local_transactions/_fields.html.erb
- app/views/shared/_common_edition_attributes.html.erb
- app/views/simple_smart_answers/_node.html.erb
- app/views/transactions/_fields.html.erb
- spec/javascripts/spec/ajax_save.spec.js
- test/functional/editions_controller_test.rb
- test/integration/edition_major_change_test.rb
- test/integration/edition_workflow_test.rb
- test/integration_test_helper.rb
- test/unit/helpers/form_helper_test.rb
Model validation error messages in user interface are currently not being displayed to users.
We should make sure that - whether the user has JavaScript enabled or not - all model validation error messages are shown to the user and the appropriate field and field label are highlighted. 
Tests should exist that catch any change in the desired behaviour.
The current user experience is sub-optimal. The user might experience a record that fails to save for example, but no error is shown and no indication is given as to which field generated the error. This gives a somewhat "trial and error" experience for the user and is generally disappointing for them.
Error messaging should be made consistent across the …
> Validation errors not being displayed in the user interface

- app/assets/stylesheets/smart_answer_builder.css
- app/views/simple_smart_answers/_node.html.erb
Model validation error messages in Publisher are currently not being displayed to users.
We should make sure that - whether the user has JavaScript enabled or not - all model validation error messages are shown to the user and the appropriate field and field label are highlighted. 
This PR improves the `SimpleSmartAnswer` format's `Node` UI by showing model validation error messaging, and fixing style/formatting issues with `Options`. 
[Trello](https://trello.com/c/HTrLSx0G/549-fix-simplesmartanswer-ui-issues-in-publisher)
> Fix SimpleSmartAnswer UI issues in Publisher

- app/views/shared/_part.html.erb
Model validation error messages in Publisher are currently not being displayed to users.
We should make sure that - whether the user has JavaScript enabled or not - all model validation error messages are shown to the user and the appropriate field and field label are highlighted. 
This PR re-enables the model validation messages for the GuildeEdition format - Part child records.
[Trello](https://trello.com/c/SvOnnXeB/530-update-parts-and-variants-validation-errors-in-publisher)
Co-authored-by: Alex Newton <@GDSNewt>
> Update Part model validation errors

- app/views/shared/_transaction_variant.html.erb
Model validation error messages in Publisher are currently not being displayed to users.
We should make sure that - whether the user has JavaScript enabled or not - all model validation error messages are shown to the user and the appropriate field and field label are highlighted. 
This PR re-enables the model validation messages for the TransactionEdition format - Variant child records.
[Trello](https://trello.com/c/SvOnnXeB/530-update-parts-and-variants-validation-errors-in-publisher)
Co-authored-by: Alex Newton <@GDSNewt>
> Update Variant model validation errors

- app/models/part.rb
- app/models/simple_smart_answer_edition/node/option.rb
- app/models/variant.rb
- test/integration/adding_parts_to_guides_test.rb
- test/integration/adding_variants_to_transactions_test.rb
- test/models/parted_test.rb
- test/models/varianted_test.rb
Currently, the messaging around invalid slug's for GuideEdition, TransactionEdition, and SimpleSmartAnswerEdition simply states that the slug `is invalid`. This does not help the user understand why the slug is invalid, so diagnosing the issue takes longer than it would if a more meaningful message were output, and correcting the issue is a somewhat trial-and-error experience - especially for the novice user.
This pull request adds more helpful and specific messages when the user experiences an invalid slug.
[Trello](https://trello.com/c/SvOnnXeB/530-update-parts-and-variants-validation-errors-in-publisher) …
> Improve invalid slug validation messages

- app/views/answers/_fields.html.erb
- app/views/artefacts/new.html.erb
- app/views/completed_transactions/_fields.html.erb
- app/views/downtimes/_form.html.erb
- app/views/editions/_major_change_fields.html.erb
- app/views/help_pages/_fields.html.erb
- app/views/licences/_fields.html.erb
- app/views/licences/new.html.erb
- app/views/local_transactions/_fields.html.erb
- app/views/local_transactions/new.html.erb
- app/views/places/_fields.html.erb
- app/views/shared/_common_edition_attributes.html.erb
- app/views/shared/_metadata.html.erb
- app/views/shared/_transaction_variant.html.erb
- app/views/simple_smart_answers/_fields.html.erb
- app/views/transactions/_fields.html.erb
A `FormHelper` module was introduced into Publisher via [this PR](https://github.com/alphagov/publisher/pull/1478).
This helper creates a consistent HTML structure, classes, help and error blocks etc for input fields (see example below). But it has so far only been applied to fields that can generate model validation errors.
Ideally, we want a consistent approach and structure across as many fields as possible - wether or not they generate model validation errors.
This change converts all fields - where it is sensible and possible to do so - to use the `FormHelper` module. 
We ignore the following - retired - formats:
- CampaignEdition
- ProgrammeEdition
- VideoEdition
This `FormHelper` entry...
```ruby
form_group(f, :field_id, label: "Custom field label", help: "Some helpful text") do …
```
> Convert input fields to use FormHelper in Publisher

- app/assets/javascripts/modules/ajax_save.js
- app/assets/javascripts/modules/ajax_save_with_parts.js
- app/assets/javascripts/modules/parts.js
- app/views/shared/_transaction_variant.html.erb
- spec/javascripts/spec/ajax_save.spec.js
- spec/javascripts/spec/ajax_save_with_parts.spec.js
- spec/javascripts/spec/parts_spec.js
- test/integration/adding_parts_to_guides_test.rb
- test/integration/adding_variants_to_transactions_test.rb
The js-error CSS class is appended to elements when model validation error messages are returned from an Ajax POST/Update request on an Edition.
The has-error CSS class is appended to elements when model validation errors messages are returned from a standard Rails HTTP form POST request on an Edition.
It is somewhat unnecessary to have two different classes which do the same thing so we are just going to utilise the 'has-error’ class included with bootstrap to meet our requirements.
There was some debate as to whether we should define our own CSS for error messaging; the rationale being that it would not be affected by future updates to bootstrap. We decided against doing that for now.
In addition to replacing 'js-error' we have removed some redundant code in the tests and made one test …
> Remove js-error CSS class

- data/local_services.csv
Trello: https://trello.com/c/WwdltWkO
Removes service 1827: "Find a COVID-19 rapid lateral flow test site" as this service has been replaced by one on the NHS.UK: https://maps.test-and-trace.nhs.uk/
> Remove service 1827

- data/local_services.csv
Trello: https://trello.com/c/3YVLHZM2
Removes service 1113 as most of the links for the service are broken and users are now being redirected to static content.
> Remove service 1113

- data/local_services.csv
Trello: https://trello.com/c/gZBD3k3A
Removes service 1287, "Get coronavirus help from your local council".
The "Get coronavirus help from your local council" is being retired as:
1. Numerous local councils no longer offer the help listed in the start
page, making the start page of the look up misleading and out-of-date.
2. Less than 50% of users find it useful
3. User feedback states that local council pages are broken, incorrect
or unhelpful
4. Nobody is updating links or following up with local councils on this.
5. Its proposition is confusing and unclear
> Remove service 1287

- lib/tasks/temporary_data_hygiene.rake
The document `/disposal-of-dredged-material-at-sea` was unpublished in 2018 and redirected to `/guidance/do-i-need-a-marine-licence#disposing-of-dredged-material-at-sea`.  However, as the redirect is implemented with segment mode (i.e. everything after the original slug is forwarded with the redirect), router rejected the redirect as the URL contains a fragment, which is incompatible with segment mode.
This meant the document was never unpublished and has remained in place since then. An [error is logged by Content Store](https://sentry.io/organizations/govuk/issues/2661224471/), as the downstream request to router fails.
Everytime a page that is linked gets updated, the link expansion process attempts to re-unpublish this page, which fails and another error is logged.
By updating the URL …
> Add temporary rake task to fix redirect on a document

- lib/working_days_calculator.rb
Publisher uses the public bank holidays API rather than the internal endpoint.
Using internal APIs is preferred - we won't need to give publisher credentials for this API in environments where this is necessary, and requests that stay in the VPC may be faster too.
> Use internal Frontend API

- app/controllers/application_controller.rb
SENTRY_CURRENT_ENV is set to integration-blue-aws in
integration whereas GOVUK_ENVIRONMENT_NAME is set to
integration.
> Use GOVUK_ENVIRONMENT_NAME in place of SENTRY_CURRENT_ENV

- lib/working_days_calculator.rb
After discussing with @kevindew we have decided to continue consuming these APIs via the public endpoint rather than using an internal endpoint.
The reasoning is that we prefer all requests to frontend applications to go through Fastly and router. This is particularly useful because Fastly caches requests to the APIs, and we have seen an incident in the past where these APIs could not handle high volumes of requests (and so require caching). We believe these APIs should probably not be served by frontend apps, and instead should be served by a different backend service, but this is out of scope of the replatforming project.
Reverts alphagov/publisher#1552
> Revert "Use internal Frontend API"

- lib/service_sign_in/check-income-tax.en.yaml
- lib/service_sign_in/check-state-pension.en.yaml
- lib/service_sign_in/personal-tax-account.en.yaml
HMRC services are coming off Verify from 1 April.
Users creating new accounts can choose between creating an account using Verify or Government Gateway. HMRC want to give users a warning at the point when they're making a decision of which to use, that Verify will no longer be available from 1 April.
Trello: https://trello.com/c/up9pFpBz
> Add callout to sign in pages for HMRC journeys

- app/assets/javascripts/modules/related_content_items_select.js
- app/assets/stylesheets/bootstrap_and_overrides.scss
- app/views/answers/_fields.html.erb
- app/views/artefacts/new.html.erb
- app/views/completed_transactions/_fields.html.erb
- app/views/downtimes/index.html.erb
- app/views/guides/_fields.html.erb
- app/views/help_pages/_fields.html.erb
- app/views/licences/_fields.html.erb
- app/views/local_transactions/_fields.html.erb
- app/views/places/_fields.html.erb
- app/views/root/_publication.html.erb
- app/views/shared/_admin.html.erb
- app/views/shared/_clone_buttons.html.erb
- app/views/shared/_edition_history.html.erb
- app/views/shared/_history.html.erb
- app/views/shared/_metadata.html.erb
- app/views/shared/_related_external_links.html.erb
- app/views/shared/_tagging.html.erb
- app/views/shared/_unpublish.html.erb
- app/views/simple_smart_answers/_fields.html.erb
- app/views/simple_smart_answers/_node.html.erb
- app/views/transactions/_fields.html.erb
- test/functional/downtimes_controller_test.rb
- test/integration/simple_smart_answers_test.rb
I've worked through each page of the application and have fixed issues flagged by Wave. This is largely fairly straightforward fixes for things like:
- adding legends/headings to fieldsets
- putting radio buttons in fieldsets
- adding missing labels
- linking labels to inputs
- ensuring headings are sequential
- replacing placeholders with hint text
A lot of these changes are not visible, but effect how screen readers interact with the page. However, there are quite a few visible changes.
While this makes the page accessible it doesn't look great. Maybe it should be a filter off to the side like in specialist? Maybe it's fine as is. Open to suggestions.
|Before|After|
|------------|------------|
|<img width="709" alt="image" src="https://user-images.githubusercontent.com/42515961/157008853 …
> Fix issue flagged by Wave Accessibility Tool 

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
This does the bare minimum work to use the skip link component from the GOV.UK Design system.
It simply adds the design system and renders the component in the application view.
If we want to use further components, we will likely have to add in more configuration.
https://trello.com/c/1lMcyxjF/245-fix-accessibility-issues-mainstream
> Add skip link component from GOV.UK Design System

- app/views/layouts/application.html.erb
Move skip link component to :body_start in the layout
This fixes a bug in a test that is currently failing on main. Moving the skip link component within the body starts ensures that the component is loaded within the document.
This was the hmtl output before 
And after being moved inside the :body_start block
> Move skip link component to :body_start in the layout

- app/assets/stylesheets/downtime.scss
- app/views/downtimes/_form.html.erb
This is part of the work to make our applications more accessible.
The `date_select` and `time_select` methods do not allow you to pass a label in as on option. This means that the fields are inaccessible for screen readers. I've used it to use more granular select fields (date, month, year etc.) and added labels.
|Before|After|
|---------------|---------------|
|<img width="545" alt="image" src="https://user-images.githubusercontent.com/42515961/155137274-4ffd950c-e73b-4cb0-bc4d-b93132f32485.png">|<img width="607" alt="image" src="https://user-images.githubusercontent.com/42515961/155137063-28cd83d1-8f99-4452-b7c6-f359df9438cd.png">|
https://trello.com/c/1lMcyxjF/245-upgrade-orphaned-labels-mainstream …
> Update downtime message inputs to include labels

- app/assets/javascripts/modules/ajax_save.js
- app/assets/javascripts/modules/ajax_save_with_parts.js
- spec/javascripts/spec/ajax_save.spec.js
- spec/javascripts/spec/ajax_save_with_parts.spec.js
- test/integration/edition_workflow_test.rb
- test/integration_test_helper.rb
At the moment, with the exception of Smart Answers, the Edit Publication uses JS for progressive enhancement. All error handling takes place  within the `ajaxSave` and `ajaxSaveWithParts` modules.
This PR adds the error summary component/banner dynamically with the same design used on the non-JS pages. This banner links the user to the relevant input. 
Add error summary component when JS is on for the edit publication page
|Before|After|
|------------|------------|
|<img width="755" alt="image" src="https://user-images.githubusercontent.com/42515961/158408714-a74ff499-522c-4ab0-96c6-f55d54d3b4b7.png">|<img width="779" alt="image" src="https://user-images.githubusercontent.com/42515961/158409286-bf58ad48-1224-430b-a142-23d0a1e3d540.png">|
I'm pretty inexperienced with JS so if i'm not …
> Add error summary to js pages

- data/local_services.csv
What
Remove the [`test-and-trace-support-payment`](www.gov.uk/test-and-trace-support-payment) - LGSL code `1826`.
Why
The service is being retired.
[Trello](https://trello.com/c/x43TzxRn/774-placeholder-retire-test-and-trace-lookup-tech-work-on-7th-april)
> Remove the `test-and-trace-support-payment service`

- app/views/shared/_tagging.html.erb
- test/integration/tagging_test.rb
The copy is updated as per this document: https://docs.google.com/spreadsheets/d/1OLw4B46ZqTgsuo762Kjxb-M6_rfX_dW23qp8bNhZrMo/edit#gid=1822139600
Clear consistent language in the publishing apps will help publishers tag
content better, and understand the implications of this. Better tagging will
make their content more findable.
https://trello.com/c/9pwM0OA9/929-publisher-update-copy-based-on-jenns-doc
---
> Use consistent language to describe tagging and topic pages

- config/initializers/gds_api.rb
- config/sidekiq.yml
All of our logs need to go to stdout/stderr when running on Kubernetes.
- Honour the `RAILS_LOG_TO_STDOUT` environment variable for GdsApi client logs.
- Have Sidekiq log to stdout by default and make the config forward-compatible with Sidekiq 6.
See commit messages for details.
https://trello.com/c/Jef1t4xU
Pair: @nsabri1
> Honour `RAILS_LOG_TO_STDOUT` for Sidekiq and GdsApi client logs.

- config/application.rb
There should have been enough time for the SHA1 cookies to have been 
rotated to SHA256 so we are reverting the commit were the rotator is 
added.
Trello card: https://trello.com/c/J5QIICTi/342-upgrade-publisher-from-rails-61x-to-70x
> Revert 'Rotate SHA1 encrypted cookies to SHA256'

- Dockerfile
- app/assets/javascripts/modules/paste_html_to_govspeak.js
- app/views/answers/_fields.html.erb
- app/views/help_pages/_fields.html.erb
- app/views/licences/_fields.html.erb
- app/views/local_transactions/_fields.html.erb
- app/views/places/_fields.html.erb
- app/views/shared/_part.html.erb
- app/views/simple_smart_answers/_fields.html.erb
- app/views/simple_smart_answers/_node.html.erb
- app/views/transactions/_fields.html.erb
- config/initializers/assets.rb
- lib/tasks/assets.rake
- package.json
- spec/javascripts/spec/admin/modules/paste_html_to_govspeak.spec.js
- yarn.lock
Converts pasted formatted content to GovSpeak
This work will reduce the effort and time for publishers to create new content, including HTML attachments and as a result, increase interest in creating HTML attachments by default
https://trello.com/c/20l0GFJl/440-add-paste-html-to-govspeak-to-mainstream-publisher
> Add paste html to govspeak

- app/assets/javascripts/modules/parts.js
- app/assets/javascripts/smart-answers.js
- app/models/edition.rb
- app/views/editions/show.html.erb
- app/views/guides/_fields.html.erb
- app/views/programmes/_fields.html.erb
- app/views/shared/_part.html.erb
- spec/javascripts/spec/parts_spec.js
We've done some work to allow paste to govspeak. As part of this work we've updated the govspeak guidance. However, currently, it's only rendered on Guides and Programmes.
We should expose it on any edition type that has fields that can use govspeak.
Additionally, it is not working for fields that are dynamically created using JavaScript. A list of the affected fields are:
- The body fields for Parts (GuidEdition)
- The body fields for nodes (questions and answers for  SimpleSmartAnswerEdition)
https://trello.com/c/20l0GFJl/440-add-paste-html-to-govspeak-to-mainstream-publisher
> Render govspeak help for editions with fields that can use it and ensure it works on dynamically added fields

- package.json
- yarn.lock
Currently, the Paste to Govspeak converter (paste-html-to-govspeak) in the publishing applications automatically converts any H4s, H5s and H6s to a H3 - see https://github.com/alphagov/paste-html-to-govspeak/blob/main/src/html-to-govspeak.js#L88:L89.
We want to remove this functionality and allow H4s, H5s and H6s without them being converted to H3s.
Although GOV.UK doesn't style H4s and below (in non-HTML attachments), it's important for users using assistive technology get the correct heading structure.
https://trello.com/c/aWGmHS2s/573-allow-h4s-to-h6s-with-paste-to-govspeak-converter
> Bump paste html to govspeak v0.3 

- app/lib/fact_check_message_processor.rb
- test/fixtures/fact_check_emails/html.txt
- test/unit/fact_check_message_processor_test.rb
Character encoding needs to be handled before decoding the HTML, otherwise potentially fails on unexpectedly-encoded messages.
Also now using a real email rather than a synthetic one to test with, as the previous PR assumed no charset errors. (I'm not really sure why the previous version didn't trigger the same error but this is the easiest way to be sure.)
This means potentially decoding twice which isn't quite ideal but restructuring it seemed like it would create further complexity — however might be worth attempting to find a better way anyway.
> Fix HTML email conversion

- app/lib/fact_check_message_processor.rb
- test/fixtures/fact_check_emails/html-unicode.txt
- test/unit/fact_check_message_processor_test.rb
It appears that `@message.body.charset` is always ASCII even when another encoding is used; `@message.charset` on the other hand appears to contain the correct value. Using this correctly flags the body as UTF-8 and avoids trying to decode it twice and mangling non-ASCII Unicode characters; the second pass through `try_decode` for an HTML-only message is therefore a no-op.
> Avoid double-decoding unicode

- Jenkinsfile
This application uses MongoDB 3.6 in production (via AWS DocumentDB) so it makes sense to test it against the same version. This change is necessary to use the MongoDB Ruby Driver from versions 2.16 and up.
> Use MongoDB 3.6 in CI

- app/mailers/event_mailer.rb
- app/validators/safe_html.rb
- config/environments/staging.rb
- config/environments/test.rb
- config/fact_check.yml
- script/mail_fetcher
- test/fixtures/fact_check_emails/base64.txt
- test/fixtures/fact_check_emails/hidden_nasty.txt
- test/fixtures/fact_check_emails/pound_symbol.txt
- test/unit/fact_check_message_processor_test.rb
This removes the references to alphagov.co.uk principally as a way to indicate that it isn't used as part of the email fact-checking process. This was done to resolve confusion as to whether there is still a need for the Google account that powered this fact-checking process.
alphagov.co.uk was the original hostname that GOV.UK launched on before moving to alpha.gov.uk and finally www.gov.uk.
> Remove references to alphagov.co.uk

- Dockerfile
This only affects Replatforming and publishing-e2e-tests. It should also reduce build times by at least few seconds.
> Base the container image on govuk-ruby-base.

- config/brakeman.ignore
- lib/csv_report_generator.rb
- script/mail_fetcher
Redis.current will be deprecated in Redis 5.0.
As Redis.current ultimately calls Redis.new we can migrate this method now to pave the way for future upgrades.
From Redis changelog from [5.0][1]:
‘Removed Redis.current. You shouldn't assume there is a single global Redis connection, use a connection pool instead, and libaries using Redis should accept a Redis instance (or connection pool) as a config. E.g. MyLibrary.redis = Redis.new(…).’
[Redis.current][2] just calls Redis.new so should just be able to swap methods.
[trello](https://trello.com/c/oGFWhrCO/1551-migrate-away-from-deprecated-redis-method)
> Use Redis.new rather than Redis.current

- app/controllers/editions_controller.rb
- app/helpers/edition_activity_buttons_helper.rb
- app/models/edition.rb
- app/views/editions/_major_change_fields.html.erb
- app/views/shared/_edition_activity_fields.html.erb
- app/views/shared/_history.html.erb
- app/views/shared/_metadata.html.erb
- app/views/shared/_review.html.erb
- test/functional/editions_controller_test.rb
- test/integration/delete_edition_test.rb
- test/integration/edition_history_test.rb
- test/integration/edition_workflow_test.rb
This PR includes several commits updating content in Mainstream Publisher to make actions and steps in the workflow clearer for content designers using the application.
> Update application content

- .dockerignore
The mail-fetcher cronjob was failing because it needs `script/mail_fetcher`.
This only affects the container image; no change to the EC2/Puppet deployment.
> Include necessary scripts in the container image.

- .github/workflows/minitest.yml
The concept of the "deployed-to-production" branch no longer exists in GOV.UK infrastructure since we switched to a Kubernetes platform. Thus this branch is stale and no-longer represents the deployed version of Publishing API.
Switching this to "main" means that we will be testing against the version of Publishing API that is expected to be deployed - as Publishing API is continuously deployed.
> Run schema tests against "main" branch of Publishing API

- Gemfile
- Gemfile.lock
- app/controllers/reports_controller.rb
- app/models/report.rb
- config/brakeman.ignore
- lib/csv_report_generator.rb
- test/functional/reports_controller_test.rb
- test/models/report_test.rb
- test/unit/csv_report_generator_test.rb
Since moving to container based hosting whereby the file system is readonly, the reports functional has broken. This is because the CSVs for reports were written and served from the local filesystem.
This replaces the local filesystem with S3. The hour rake task that generates the CSV report now uploads them to S3. The reports page then redirects users to a signed link valid for 5 mins to download the reports.
PR for Terraform to create bucket:
https://github.com/alphagov/govuk-infrastructure/pull/857
PR to set env var:
https://github.com/alphagov/govuk-helm-charts/pull/1075
> Upload and serve reports from S3

- lib/csv_report_generator.rb
- script/mail_fetcher
Adds a second lock inside the current lock in the CsvReportGenerator#run! method and inside the mail_fetcher script.
This is a first step to cleaning up a little tech debt. We want to remove the environment from the lock name (not necessary because all environments have their own redis anyway, and undesirable because it requires a brakeman ignore).
However, these scripts are run by cron jobs (the mail_fetcher script is run every 5 minutes, and the reports:generate task - which uses CsvReportGenerator - is run on the hour), so it's not necessarily possible to ensure that the job won't be running when the app is deployed. This means if we just change the lock name there's a possibility two instances will try to run the task, one with the old lock, one with the new one. So here we require …
> Add double-locks

- config/brakeman.ignore
- lib/csv_report_generator.rb
- script/mail_fetcher
Removes the original lock, moving us to the simplified lock name added here: https://github.com/alphagov/publisher/pull/1815
Can be merged once a safe period of time has passed (min 2 hours after original pull merged, so any time on Friday 19th May or later would be reasonable)
https://trello.com/c/84yWQ0NJ/1662-ps-15-clean-up-brakeman-errors-following-on-from-rediscurrent-redisnew-updates
> Remove original lock now a safe time has passed

- app/presenters/formats/completed_transaction_presenter.rb
- test/unit/presenters/formats/completed_transaction_presenter_test.rb
[Trello](https://trello.com/c/VHZ1R1zY/262-no-form-validation-on-service-feedback-forms-l)
This needs to be deployed along with two other PRS in [Feedback](https://github.com/alphagov/feedback/pull/1601) and [Frontend](https://github.com/alphagov/frontend/pull/3534).
This changes the rendering app for completed transactions from Frontend to Feedback. For more information about this change, [see this PR](https://github.com/alphagov/feedback/pull/1601).
When the various PRs are deployed, the completed transactions will need to be republished. Hence do not merge as things will need to happen in a set order!
Follow …
> Change completed_transactions rendering app

- app/helpers/tabs_helper.rb
- app/views/shared/_related_external_links.html.erb
- app/views/shared/_tagging.html.erb
- app/views/shared/_workflow_buttons.html.erb
- test/unit/tabs_helper_test.rb
Previously, retiring a document only disabled creating a brand new
edition and creating a new edition of an existing document. However,
there were a number of POST actions that a user could perform, like
update tagging, change format + saving the document.
If we mark the document type as 'retired' then we don't expect the
inidvidual documents to be modified. All the documents data can be
displayed but not edited + internal notes + unpublish feature (incase a
document needs unpublishing).
Trello:
https://trello.com/c/85Kl4zO7/2092-disable-editing-of-tags-when-marking-publisher-licences-as-retired
Follow [these …
> Disable document actions after marked as retired

- lib/tasks/once_off/unpublish_licences.rake
Licences are to be migrated to Specialist Publisher. The import will be handled from that side. After import and after confirmation that everything has been carried across successfully, it will be necessary to archive/unpublish/redirect the licences.
This rake task uses a copy of the code from UnpublishService (slightly modified to allow a named task as the user) to perform this task for each published licence, although there are a list of licences for which the redirect is unnecessary (in this case they will just be archived and unpublished).
https://trello.com/c/9qWrtRto/2038-create-migration-to-archive-and-redirect-old-licences
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own …
> Add task to archive and unpublish licences after migration

- lib/tasks/once_off/unpublish_licence_finder.rake
- redirects to the new licence finder at /find-licences
This rake task uses a copy of the code from UnpublishService (slightly modified to allow a named task as the user) to perform the unpublish task task.
https://trello.com/c/Wkj80QfI/2062-create-temp-rake-task-to-redirect-the-old-licence-finder
> Add task to unpublish licence finder

- app/helpers/tabs_helper.rb
- test/unit/tabs_helper_test.rb
This was originally removed as you can change document format from this tab but the tab also houses the delete draft feature which we need.
> Readd admin tab to retired documents

- app/controllers/editions_controller.rb
- test/functional/editions_controller_test.rb
- when a request is sent without an assigned_to param to update an edition, an error was being thrown as the update_assignment function expected a value to always be passed
> fix(editions) prevent calling method on nil

- app/models/workflow.rb
- test/models/workflow_test.rb
Seeing several issues where an edition has gotten into an incorrect state because of errors raised _after_publish_ breaking, but once the state has been moved to "published" then it is unable to rerun that code without manually changing the status.
> fix(workflow) update artefact before 'publishing' edition state

- app/controllers/reports_controller.rb
- app/presenters/all_content_workflow_presenter.rb
- app/presenters/all_edition_churn_presenter.rb
- app/views/reports/index.html.erb
- config/brakeman.ignore
- config/routes.rb
- lib/csv_report_generator.rb
- test/unit/csv_report_generator_test.rb
- also with additional time and date created fields split from editioned_at to allow for easier data parsing
Making these changes based on a request by the content improvement team to better understand the rate of change of editions in publisher - they need the historical data, not just that of all current editions, so I'm adding in a couple of extra reports for them.
> add all edition reports for content workflow and edition churn

- app/views/reports/index.html.erb
> fix: correct ordering of content workflow reports and link text

- app/lib/fact_check_email_handler.rb
- test/unit/lib/fact_check_email_handler_test.rb
Occasionally, there is an error when connecting to the mailbox in production. It seems a very transient error, and since the job is run every few minutes isn't really a problem, but if the exception is left unhandled a Sentry alert is raised. Log the error and move on.
We can't determine whether there are any unprocessed emails if we couldn't connect to the mailbox, so don't send any stats to Graphite.
[Trello card](https://trello.com/c/E6NTvtxY)
> Handle errors connecting to fact check mailbox

- Dockerfile
> Adding dockerfile update that I missed from 3.2.2 pr

- Gemfile
- Gemfile.lock
- config/environments/production.rb
Uglifier does not support ES6, and Terser is the recommended replacement in the Uglifier README (and is the default option for Rails apps these days).
[Trello card](https://trello.com/c/5Tkk0Ewf)
> Replace Uglifier with Terser for JS compression

- app/controllers/editions_controller.rb
- app/models/edition.rb
- test/models/edition_test.rb
Previously, a publisher would need to manually assign themselves as the
assignee when creating an edition. We now assign the user that
created the edition as the assignee. This can be still be modified from
the UI if the assignee is different from the creator, but for the
majority of cases this should be the expected behaviour.
Feature verified in integration by Keith Emmerson.
Trello:
https://trello.com/c/3zzF4dKj/37-auto-assign-ownership-in-mainstream-publisher
> Use current user as assignee

- app/views/simple_smart_answers/_fields.html.erb
Change the numbers of rows in the "Body" textarea of the Smart Answer edit view.
It was shorter than all the other textareas.
[Relevant Trello Card](https://trello.com/c/tUoohEu2/592-window-for-editing-simple-smart-answer-start-page-body-text-not-large-enough)
> Increase rows of Body Textarea in Smart Answer Edit

- app/views/shared/_history.html.erb
Change the numbers of rows in the change note textarea modal.
The edition note box is not big enough, meaning Content Designers cannot easily compose or work with the note in Publisher.
[Relevant Trello Card](https://trello.com/c/cExM15Xj/593-edition-notes-box-size)
> Add extra rows to Edition notes textarea

- app/controllers/editions_controller.rb
- test/functional/editions_controller_test.rb
Fix exception case when a user tries to claim 2i whilst an edition is scheduled for publishing
[Trello ticket](https://trello.com/c/YMXeGdlK/585-handle-validation-errors-when-assigning-a-reviewer-to-an-edition)
> Bug fix for claiming 2i on scheduled publication

- app/assets/stylesheets/bootstrap_and_overrides.scss
- app/views/shared/_history.html.erb
Add new modifier class that can be used to make the length of the modal wider on Desktop screen sizes. Add new class to the modal that is used for specifying the change note.
It was requested that the change note modal be increased in width.
The modal will (likely) eventually be removed in the change to Design System, so this is a temporary measure until the move has been made.
> Make the Change Note Modal wider

- Gemfile
- Gemfile.lock
- app/constraints/feature_constraint.rb
- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- config/features.rb
- config/routes.rb
- test/unit/constraints/feature_constraint_test.rb
Add the Flipflop gem to enable feature-toggling within the publisher app.
The dashboard (available at `/flipflop`) provided is not secured in any
way (but since we will be using the "Cookie" strategy, users will only
be able to toggle features on/off for themselves). This could be added
later, if desired.
Also provides a `FeatureConstraint` class to enable dynamic routing to
be set up based on the value of the feature toggles.
[Trello ticket](https://trello.com/c/hBy0ITYW/605-create-wip-toggle-structure-for-page)
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a …
> Add Flipflop gem for feature-toggling

- app/controllers/legacy_reports_controller.rb
- app/views/legacy_reports/index.html.erb
- config/brakeman.ignore
- config/features.rb
- config/routes.rb
- test/functional/legacy_reports_controller_test.rb
- test/integration/routes_test.rb
Add a feature toggle for toggling on/off the ability to see either the
existing, bootstrap-based reports page, or the new design-system based
one.
Currently the new one is a duplicate of the old one (and so is still
bootstrap-based). Future commits will replace the new view with a
design-system based one.
[Trello ticket](https://trello.com/c/hBy0ITYW/605-create-wip-toggle-structure-for-page)
> Add feature-toggling for reports page transition

- app/assets/config/manifest.js
- app/assets/javascripts/application.js
- app/assets/javascripts/legacy-application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/legacy-application.scss
- app/controllers/application_controller.rb
- app/controllers/reports_controller.rb
- app/helpers/navigation_items_helper.rb
- app/views/layouts/design_system.html.erb
- app/views/layouts/legacy_application.html.erb
- spec/support/jasmine-browser.json
- test/unit/helpers/navigation_items_helper_test.rb
[Relevant Trello Card](https://trello.com/c/FDWSNsdX/606-transition-the-navbar-and-footer)
- Rename `application.js` and `application.scss` to `legacy-application.scss` and `legacy-application.js` in preparation to use the `layout_for_admin` component from the govuk_publishing_components gem. Update the configuration manifest and point `application.html.erb` to the new legacy asset files. Rename `application.html.erb`
to `legacy_application.html.erb` and set layout in ApplicationController to the renamed layout.
- Create `design_system.html.erb` layout. Make the` ReportsController` use the new layout. Create a helper, `NavigationItemsHelper`, to build the navigation link structure for the navbar. Write tests for the `NavigationItemsHelper`.
As part of the work to transition publisher to …
> Create Design System Layout

- app/assets/stylesheets/application.scss
Increase the size of `$govuk-page-width` to `1140px` on appplication.scss, the stylesheet used by the `design_system.html.erb` layout for the pages transitioning to the Design System.
Request from designer, based on feedback from Whitehall transition. As part of the work to transition to the Design System. [Relevant Trello Card](https://trello.com/c/FDWSNsdX/606-transition-the-navbar-and-footer).
> Add `$govuk-page-width` to application.scss

- test/integration/large_SA_mermaid_code.txt
- test/integration/simple_smart_answers_test.rb
As described in ticket [#600](https://trello.com/c/0iriT8Ow/600-bug-ssa-visualization-fails-with-mermaid-upgrade), it was identified that when mermaid.js released version [10.6.0](https://github.com/mermaid-js/mermaid/releases/tag/v10.6.0), they added a limitation to the max number of of edges (i.e number of lines and arrows between nodes) a diagram can have(280). 
This was only picked up manually when looking at the ["Work out your VAT fuel scale charge"](https://publisher.publishing.service.gov.uk/editions/6450cb324aa60b000d4172d6/diagram) smart-answer, as it failed to load. 
To avoid future instances of this happening tests have been added, to check that both small and large smart answers flowcharts are render successfully.
> Improve testing of simple smart answer flowchart rendering 

- app/controllers/reports_controller.rb
- app/views/layouts/design_system.html.erb
- app/views/reports/index.html.erb
- test/functional/reports_controller_test.rb
Transitions the content of the reports page to the GOV.UK Design System.
- Adds use of the [Page Title](https://components.publishing.service.gov.uk/component-guide/title) component to `app/views/layouts/design_system.html.erb` to ensure transitioned pages use consistent formatting for the page title.
- Updates the reports index view to use the [Document List](https://components.publishing.service.gov.uk/component-guide/document_list) component.
- Improves the test coverage around the reports controller.
Since the transitioned design splits the generated message into two separate pieces of metadata (one for the time and one for the date), there will now be twice the calls to S3 to fetch that data. This could be optimised if it becomes a problem, but this page is not used much so that is …
> Migrate the Reports page to GOV.UK Design System

- app/controllers/downtimes_controller.rb
- app/views/downtimes/_form.html.erb
- app/views/downtimes/_time_input.html.erb
- app/views/downtimes/new.html.erb
- app/views/layouts/design_system.html.erb
- test/integration/routes_test.rb
Transition the look and feel of the "Add Downtime" page to the GOV.UK Design System.
Does not include validations/error messages/flash messages.
This breaks the functionality, which will be fixed in a subsequent PR.
Part of the transition of Mainstream Publisher to the GOV.UK Design System.
### Before
> Transition add downtime page

- app/controllers/downtimes_controller.rb
- app/views/downtimes/index.html.erb
- app/views/layouts/design_system.html.erb
- config/features.rb
- config/routes.rb
- test/functional/downtimes_controller_test.rb
- test/integration/legacy_downtime_integration_test.rb
- test/integration/routes_test.rb
- Add new feature `design_system_downtime_pages` to the FlipFlop config.
- Update the routes with new constraint.
- Duplicate the controllers, views and test of Downtimes and append the `legacy_` prefix to them.
- Add new test in the routes integration test for the new feature.
- Add new test for legacy views in integration for Downtimes.
- Make the new Downtimes index page use the Design System layout.
- Add flash back to the Design System layout for integration tests (and also for future work to flash success/failure messages).
As part of the work to transition Publisher to the Design System from Bootstrap.
[Relevant Trello Card](https://trello.com/c/c1023Flb/620-transition-downtime-hub) …
> Initial work for Downtime Index page transition to Design System

- app/helpers/downtimes_helper.rb
- app/views/downtimes/index.html.erb
- app/views/layouts/design_system.html.erb
- app/views/shared/_flash.html.erb
- test/functional/downtimes_controller_test.rb
- test/integration/downtime_integration_test.rb
- test/unit/helpers/downtimes_helper_test.rb
- Use the Table component on the Downtime index page
- Create new helper function to generate entries for the Downtime index table
- Add test for new helper function
- Add flash to design_system.html.erb
- Update existing tests with new changes
As part of the work to transition Publisher to the Design System from Bootstrap.
[Relevant Trello Card](https://trello.com/c/c1023Flb/620-transition-downtime-hub). https://github.com/alphagov/publisher/pull/2027 Needs to be merged first
> Transition Downtime Index to the Design System

- config/features.rb
[Trello card](https://trello.com/c/erOwzh02/607-transition-reports-page-to-the-govuk-design-system)
This will make the reports page use the design system by default.
> Set feature toggle for reports page to true

- app/views/downtimes/_form.html.erb
- Avoid the use of nested fieldsets and rename the remaining fieldsets to "From date"/"From time" and "To date"/To time". This should work better with assistive technologies; update the legend size to "m".
- Customise the date and time input names so that we can differentiate between the two sets.
> Add downtime update view

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/downtimes.scss
- app/helpers/downtimes_helper.rb
- app/views/downtimes/index.html.erb
- test/unit/helpers/downtimes_helper_test.rb
- Create new stylesheet for Downtimes
- Add max width to the title of the service in the Downtimes index page table
- Add max width to the state of the service in the Downtimes index page table
- Prevent the links from breaking to multiple lines (on Desktop screen sizes)
Make the table resemble more closely what it looks like in the design.
> Changes to Downtimes table

- test/integration/legacy_downtime_integration_test.rb
- test/integration/legacy_downtime_with_invalid_dates_test.rb
- Add feature toggle to downtime_with_invalid_dates_test
- Create new legacy_downtimes_with_invalid_dates_test
- Add feature toggle to legacy_downtime_integration_test
- Update downtime_with_invalid_dates_test link name
Prevent randomly failing test.
> Fix randomly failing Downtime integration test

- app/assets/javascripts/application.js
- app/assets/javascripts/legacy_modules/legacy_downtime_message.js
- app/assets/javascripts/modules/downtime_message.js
- app/views/legacy_downtimes/edit.html.erb
- app/views/legacy_downtimes/new.html.erb
- spec/javascripts/spec/downtime_message.spec.js
- spec/javascripts/spec/legacy_downtime_message.spec.js
Create a new Javascript module that generates the downtime message when adding/editing downtime for a publication, that works with the new add/edit downtime form components.
The old page used dropdown lists for selecting the date components, whereas the transitioned page uses text inputs.
The old code disabled the form, which is not accessible, so the new code does not do this.
Furthermore, the old code generated two messages that appeared in slightly different places on the form, whereas the new page only has one message to display.
[Trello card](https://trello.com/c/0J3X18AA).
Follow [these …
> Transition downtime message Javascript

- app/views/downtimes/_form.html.erb
- app/views/downtimes/new.html.erb
- app/views/layouts/design_system.html.erb
- app/views/shared/_error_summary.html.erb
Replace the use of the legacy error summary on the "Add downtime" view with one from the design system layout.
Add ids to relevant form inputs so that the links in the error summary link to the expected input.
The new error summary partial is a like-for-like replacement of the legacy one, just making use of the `error_summary` component from the GOV.UK Design System. This means that the title, error message text and link generation is exactly the same.
This is part of the transition of Mainstream Publisher to the GOV.UK Design System.
## Trello
Follow [these …
> Add an error summary to the design system layout

- app/controllers/downtimes_controller.rb
- app/helpers/errors_helper.rb
- app/models/downtime.rb
- app/views/downtimes/_datetime_fields.html.erb
- app/views/downtimes/_form.html.erb
- app/views/legacy_downtimes/_form.html.erb
- app/views/legacy_downtimes/_legacy_downtimes_error_summary.html.erb
- app/views/shared/_error_summary.html.erb
- test/functional/downtimes_controller_test.rb
- test/integration/downtime_with_invalid_dates_test.rb
- test/models/downtime_test.rb
- test/support/downtimes_controller_parameterised_tests.rb
- test/unit/helpers/errors_helper_test.rb
- Update validations on the "Add downtime" page now that we're using text fields for all of the input fields.
- When there are validation errors, populate the fields with the values that were submitted.
- Make model validation error messages consistent (so the `message` does not include the field name at the start, which is prepended when using `full_message`).
Part of the transition of Mainstream Publisher to the GOV.UK Design System.
> Transition add downtime page/field level validation messages

- app/views/downtimes/_form.html.erb
The default bottom margin is 30px for a textarea, but the Figma designs specify 50px.
> Increase the margin at the bottom of "Add Downtime"

- app/assets/stylesheets/downtimes.scss
- app/controllers/downtimes_controller.rb
- app/models/downtime.rb
- app/views/downtimes/_form.html.erb
- app/views/downtimes/delete.html.erb
- app/views/downtimes/edit.html.erb
- config/routes.rb
- test/functional/downtimes_controller_test.rb
- test/integration/downtime_integration_test.rb
- test/integration/downtime_with_invalid_dates_test.rb
- test/models/downtime_test.rb
[Trello card](https://trello.com/c/i3Jjd1sr/157-upgrade-edit-downtime)
This PR is to upgrade the edit downtime page to use the design system. There is also a new delete downtime page too that uses the design system.
Edit down page before:
Edit downtime page after:
Delete downtime page:
Changes also include:
- Adding a new style in the downtime.scss to make the downtime remove-link red.
- The destroy method in the downtimes_controller opens the delete page. (Previously this did not exist as there was no delete page as it was on the edit page).
- Adding delete to the routes and added it to the design_system_downtime_edit flipflop switch.
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-you …
> Transition edit downtime and destroy downtime to use the design system

- app/controllers/downtimes_controller.rb
- app/views/downtimes/_form.html.erb
- app/views/downtimes/delete.html.erb
- Remove link in success message for downtime update and remove
- Add speech marks around the remove downtimes paragraph
- Change heading size of message
[Trello card](https://trello.com/c/i3Jjd1sr/157-upgrade-edit-downtime)
> Improvements for the edit and remove downtime page

- app/assets/stylesheets/forms.scss
- app/lib/presentation_toggles.rb
- app/presenters/formats/completed_transaction_presenter.rb
- app/views/completed_transactions/_fields.html.erb
- test/integration/completed_transactions_create_edit_test.rb
- test/models/completed_transaction_edition_test.rb
Remove the Register to Vote promo option from Publisher.
Requested to be removed.
[Relevant Trello Card](https://trello.com/c/NpANWWTr/223-remove-promote-register-to-vote-option-when-editing-completed-transactions-in-publisher)
> Remove Register to Vote Promo

- app/assets/stylesheets/forms.scss
- app/lib/presentation_toggles.rb
- app/presenters/formats/completed_transaction_presenter.rb
- app/views/completed_transactions/_fields.html.erb
- test/integration/completed_transactions_create_edit_test.rb
- test/models/completed_transaction_edition_test.rb
Add Photo ID promo to list of promos for Completed Transaction pages.
Request from content team.
> Add Photo ID Promo

- app/assets/stylesheets/forms.scss
- app/lib/presentation_toggles.rb
- app/presenters/formats/completed_transaction_presenter.rb
- app/views/completed_transactions/_fields.html.erb
- test/integration/completed_transactions_create_edit_test.rb
- test/models/completed_transaction_edition_test.rb
Reverts alphagov/publisher#2111
Needs to be reverted until the update is made to content schema in Publishing API!
> Revert "Add Photo ID Promo"

- docs/arch/adr-009-replace-mongodb-with-postgres.md
https://trello.com/c/S1BbvoQN/262-document-our-decision-to-replatform-our-db-to-postgresql
> Adds a new ADR that documents our decision to move to Postgres

- app/controllers/editions_controller.rb
- app/services/unpublish_service.rb
- test/functional/editions_controller_test.rb
- test/unit/services/unpublish_service_test.rb
The changes in this PR is to solve the issue that arises when inconsistency happens between publishing-api and artefact db because of publishing api error happening after artefact db is already updated. The solution is documented in [the ADR](https://github.com/alphagov/publisher/pull/2139/files).
[Trello card](https://trello.com/c/Vx4ZTIwU/72-handle-error-from-publishing-api-when-unpublishing-edition)
> Handle error from publishing-api when unpublishing edition

- .github/workflows/deploy.yml
- Dockerfile
This gets Publisher ready for ARM.
Changes:
* Allow Docker Build to use latest Ruby 3.2.X
* Switch to the Multi-Arch Build Workflow
> Get Publisher ready for ARM

- app/workers/scheduled_publisher.rb
- test/unit/scheduled_publisher_test.rb
[Trello card](https://trello.com/c/z6XJSVge/765-scheduled-help-pages-dont-have-their-last-updated-value-set-mainstream-publisher)
This will send the latest edition payload to the publishing api before asking it to publish, which will update the last updated at date when publish is scheduled.
> Fix scheduled last updated at date

- lib/tasks/tmp_zendesk_5819067.rake
Somehow energy-company-obligation and manage-your-tax-credits have ended up with Artefacts with kind "completed_transaction", even though their editions are Answer and Transaction (note _not_ CompletedTransaction).
This prevents the editions from being published, because the artefacts are not valid because their slugs don't begin with "done/"
We ran equivalent code to this rake task in integration which appears to have fixed the issues. We'll test again in staging before running in production.
https://govuk.zendesk.com/agent/tickets/5819067
> Add temp rake task to fix data integrity issues

- app/models/artefact.rb
In 000fbeeb we fixed a data issue which was causing two artefacts in publisher's database to fail to update.
There was effectively no visibility of this situation from the developers' perspective - only the user saw the error. We didn't get an error in sentry, a log message in logit, or even a 500 in the metrics.
The [update](https://www.mongodb.com/docs/mongoid/master/api/Mongoid/Persistable/Updatable.html#update-instance_method) method in mongoid returns false if the record can't be updated because it's not valid. We weren't checking the result and logging anything, so the failure was effectively silent.
Switching to [update!](https://www.mongodb.com/docs/mongoid/master/api/Mongoid/Persistable/Updatable.html#update!-instance_method) will raise Errors::Validations if the record being …
> Raise exceptions when updates fail

- .govuk_dependabot_merger.yml
Allow the GOV.UK dependabot merger bot to automatically merge minor
version updates to the rubocop-govuk dependency. This was
unintentionally restricted to only allow patch updates.
> Enable minor rubocop-govuk gem update automerges

- app/controllers/application_controller.rb
- config/initializers/govuk_admin_template.rb
As of version 7.0, the config is now the default gem behaviour.
https://github.com/alphagov/govuk_admin_template/blob/06d93749b4482f062e721ce300ff9509d08c4c0b/lib/govuk_admin_template.rb#L10
> Remove redundant govuk_admin_template config

- app/assets/stylesheets/_summary-card.scss
- app/assets/stylesheets/application.scss
- app/controllers/homepage_controller.rb
- app/controllers/root_controller.rb
- app/helpers/popular_links_helper.rb
- app/models/edition.rb
- app/models/popular_links_edition.rb
- app/views/homepage/popular_links/_link.html.erb
- app/views/homepage/popular_links/_version_and_status.html.erb
- app/views/homepage/popular_links/show.html.erb
- app/views/shared/_summary_card.html.erb
- config/routes.rb
- test/functional/homepage_controller_test.rb
- test/integration/homepage_popular_links_test.rb
- test/integration/root_overview_test.rb
- test/models/edition_test.rb
- test/models/popular_links_edition_test.rb
- test/support/factories.rb
[Trello card](https://trello.com/c/6xb4YYE7/299-create-a-page-to-show-popular-links)
We want the ability to view the latest published popular links within Mainstream Publisher.
In order to be able to do that, this is the first story to allow us to navigate to popular links page and view the last version of popular links. The ability to view the popular links will be provided by subsequent tickets. In order to be able to view we needed to create the model so that we can insert the very first record.
> Show popular links

- app/controllers/homepage_controller.rb
- app/models/popular_links_edition.rb
- app/presenters/formats/popular_links_presenter.rb
- app/services/edition_presenter_factory.rb
- test/functional/homepage_controller_test.rb
- test/integration/homepage_popular_links_test.rb
- test/unit/presenters/formats/popular_links_presenter_test.rb
- test/unit/services/edition_presenter_factory_test.rb
This PR does the following:
- Calls publishing api to store the updated popular links content to draft content store when an edit and save action is performed on popular links.
- Calls publishing api to store the published popular links content to content store when a publish action is performed on popular links.
[trello](https://trello.com/c/szYiEKlQ/298-enable-publishing-of-popular-links)
> Publish popular links

- docs/arch/adr-011-restricting-access-to-content-by-organisation.md
An architecture decision record to record the approach to be used for restricting access to publications in Mainstream Publisher.
> ADR for restricting access to content by organisation

- app/assets/javascripts/legacy-application.js
- app/views/layouts/design_system.html.erb
- test/integration/completed_transactions_create_edit_test.rb
Resolve issues relating to the loading of Javascript in Mainstream Publisher after the [upgrade to version 40](https://github.com/alphagov/publisher/pull/2225) of the `govuk_publishing_components` gem.
[Trello card](https://trello.com/c/iRiqyukz)
> Fix javascript errors

- lib/tasks/create_popular_links_and_link_to_homepage.rake
Create popular links and links to homepage
this task performs two actions
1. Create the very first popular links record in publisher db
2. Calls publishing-api patch links endpoint to link homepage and popular links content-ids
[Trello](https://trello.com/c/dTSlgdbI/302-create-a-rake-task-to-bootstrap-popular-links)
> Add rake task to create popular links and links to homepage

- app/controllers/application_controller.rb
Log a warning when a `Mongoid::Errors::DocumentNotFound` error is raised in a controller. These errors were being silently swallowed by the application.
The error occurs when an attempt is made to load a document that doesn't exist, which can happen when the overnight DB replication from prod->integration fails. It will also happen if the edition ID is manipulated in the URL (e.g. in URLs of the form
`/editions/[edition-id]`), so it's not _necessarily_ an error when it happens.
> Log a warning on DocumentNotFound

- app/controllers/homepage_controller.rb
- app/models/popular_links_edition.rb
- test/functional/homepage_controller_test.rb
This commit tries to bring following changes
1. Handle publishing api errors and give user more understandable messages where possible for publishing api errors.
2. Handle database errors.
[Trello](https://trello.com/c/sw3DmXgK/363-update-error-messaging-copy)
> Handle publishing api errors and save content before publishing

- app/assets/stylesheets/popular_links.scss
- app/helpers/paths_helper.rb
- app/views/homepage/popular_links/_sidebar.html.erb
- test/integration/homepage_popular_links_test.rb
- test/unit/helpers/admin/paths_helper_test.rb
This commit involves changes to 
- Fix sidebar navigation to adjust for mobile devices, (this seems to be a miss from previous discussion).
- Add preview functionality to view popular links on draft frontend and live frontend using 'preview' link and 'View on GOV.UK' link.
[Trello](https://trello.com/c/Vn1ig5N2/353-create-a-preview-link-for-homepage)
> Preview homepage

- app/controllers/root_controller.rb
- app/helpers/editions_helper.rb
- app/models/edition.rb
- app/presenters/filtered_editions_presenter.rb
- app/views/legacy_root/index.html.erb
- app/views/root/index.html.erb
- app/views/user_search/index.html.erb
- test/functional/root_controller_test.rb
- test/models/edition_test.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
Update the new root controller, which uses the GOV.UK Design System layout template, to accept various submitted filter parameters, which are then used to make a filtered list of editions available to the rendered view, via a presenter.
There is a very basic, unstyled UI, (using basic rails controls rather than Design System components) for the purposes of demonstrating that the filters work / manual testing. This UI is simply there for test purposes and will be replaced by the separate ongoing work that will create the filter component and the results table component.
The controller is behind a feature flag, and so none of this is visible to general users.
[Trello ticket](https://trello.com/c/wucvIcYg) …
> Backend filtering support for the new publications page (root controller)

- app/models/popular_links_edition.rb
- test/functional/homepage_controller_test.rb
- test/integration/homepage_popular_links_test.rb
- test/models/popular_links_edition_test.rb
- test/support/factories.rb
- test/unit/presenters/formats/popular_links_presenter_test.rb
Currently popular links are populated by changing the values in [yml file in frontend app](https://github.com/alphagov/frontend/blob/52223125bea632fc5f608e8d09a1a97549c8de3a/config/locales/en.yml#L575), these urls have been relative and hence keeping it consistent, we have decided to keep popular links url published via mainstream to be saved and published as relative urls instead of absolute url's
> Allow urls for popular links to be relative url.

- app/assets/javascripts/legacy_modules/ajax_save.js
- app/assets/javascripts/legacy_modules/tab_switcher.js
- app/controllers/editions_controller.rb
- app/models/transaction_edition.rb
- app/presenters/formats/service_sign_in_presenter.rb
- app/presenters/formats/transaction_presenter.rb
- app/views/transactions/_fields.html.erb
- lib/service_sign_in/example.en.yaml
- spec/javascripts/spec/ajax_save.spec.js
- test/integration/transaction_create_edit_test.rb
- test/models/transaction_edition_test.rb
- test/unit/presenters/formats/service_sign_in_presenter_test.rb
- test/unit/presenters/formats/transaction_presenter_test.rb
The old Google Analytics, Universal Analytics (UA), has stopped working after 1st July 2024.
This PR removes any reference or use the old Analytics code.
This means we wont be sending department_analytics_profile for cross domain tracking for transaction edition and service sign wont be tracking domains anymore.
[Trello](https://trello.com/c/W01PhDtL/342-remove-remaining-ua-code-from-mainstream-publisher)
> Remove ga code

- app/controllers/homepage_controller.rb
- test/functional/homepage_controller_test.rb
In order to provide user consistent and useful messaging around database errors, we have updated the messaging to give user information on what they can do.
Discussions and feedbacks around this is captured in the [documentation ](https://docs.google.com/document/d/1r_z2JLF-5RHpuHLainh0u4-pYHhaayrKvaC-yxNE_pQ/edit)
This might change in future based on the feedback.
[Trello](https://trello.com/c/NBTlQZEj/372-take-homepage-popular-links-to-production)
> Update error message copy

- lib/tasks/create_popular_links_and_link_to_homepage.rake
Homepage popular links are now relative instead of absolute, hence we have updated rake task to update urls as relative urls
> Update rake task to have relative urls

- app/controllers/homepage_controller.rb
- test/functional/homepage_controller_test.rb
- test/integration/homepage_popular_links_test.rb
- test/support/factories.rb
- test/test_helper.rb
In order to restrict access to homepage popular links, we have added homepage editor permission. 
**Why inside Mainstream?**
- Homepage popular links is going to be managed inside Mainstream and hence its related permission.
**Considerations and side-effects:**
Homepage appears as a separate app on sign-on though technically its just a separate controller accessed via Mainstream, this has a side-effect to understand that homepage permissions are to be access via Mainstream. This is something we understand as a team and have gone ahead with.
We are trying to mitigate the degree of effects through our messaging on signon and via access error message. We shall be iterating on this based on any feedback. …
> Add homepage editor permission for all controller actions

- app/controllers/homepage_controller.rb
- app/models/popular_links_edition.rb
- test/functional/homepage_controller_test.rb
This PR includes change to:
Call to save in publishing api only if state is draft before publish is called.
Improve error wordings to reflect publishing api error response
> Refactor save before publish

- Gemfile.lock
Does not update the bson dependency to v5, as that has compatibility
issues.
> Update mongo dependency to 2.20.1

- .gitignore
- Gemfile
- Gemfile.lock
- Procfile.dev
- app/assets/config/manifest.js
- app/assets/stylesheets/legacy-application.scss
- app/assets/stylesheets/sortable_table.scss
- bin/dev
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/dartsass.rb
[Trello](https://trello.com/c/rtkv3YMZ/348-migrate-mainstream-publisher-to-dart-sass-publisher)
This work makes the necessary changes to migrate Publisher to use Dart Sass. It follows the instructions in [Migrate to Dart Sass from LibSass](https://docs.publishing.service.gov.uk/manual/migrate-to-dart-sass-from-libsass.html).
It is close to the changes made in [PR2250 (Switch from sassc-rails to dartsass-rails)](https://github.com/alphagov/publisher/pull/2250) with a couple of slight changes that seem to fix the issues encountered there, specifically bringing the legacy styles into the SASS Builds folder via the initialiser that is created as part of the work.
> 348 migrate to dart sass

- app/assets/stylesheets/application.scss
- app/controllers/root_controller.rb
- app/helpers/pagination_helper.rb
- app/presenters/filtered_editions_presenter.rb
- app/views/components/_pagination.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/root/index.html.erb
- test/functional/root_controller_test.rb
- test/integration/delete_edition_test.rb
- test/integration/edition_scheduled_publishing_test.rb
- test/integration/edition_workflow_test.rb
- test/integration/mark_edition_in_beta_test.rb
- test/integration/root_overview_test.rb
- test/integration/unpublish_test.rb
- test/integration_test_helper.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
Add pagination controls underneath the publications table on the root path of Mainstream Publisher.
> Add pagination to publication page

- app/assets/stylesheets/publications-table.scss
Updated sass allows the contents of the 'More Details' summary section to spread out across all table columns. 
Previously, this content was squashed into the first column which made it difficult to read. 
More work may be done on this in future but this functionality is needed for user testing. 
See Trello Card - [Increase width of 'more details' section of the table [Publication Page]](https://trello.com/c/6jf5jino)
> Fix 'More Details' summary contents width

- app/controllers/root_controller.rb
- test/functional/root_controller_test.rb
When visiting the root page, with no filters set, default the state filters so that only editions in the "pre-published" states are shown, as these are the editions that users of Mainstream Publisher mostly care about.
Uses the presence of the title filter as a proxy for whether any filters have been set, since that filter is always present when the 'update filter' button is clicked (even if no title text has been supplied, in which case it will have an empty value).
[Trello card](https://trello.com/c/GqI64TRd)
> Default the state filters on the publications page

- app/controllers/root_controller.rb
- app/presenters/filtered_editions_presenter.rb
- test/functional/root_controller_test.rb
- test/integration/adding_parts_to_guides_test.rb
- test/integration/adding_variants_to_transactions_test.rb
- test/integration/root_overview_test.rb
- test/integration/simple_smart_answers_test.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
Default the assignee filter on the publications page
When visiting the root page, with no filters set, default the assignee
filter so that only editions assigned to the current user are shown.
Order of precedence is:
1. assignee parameter
2. assignee in session
3. current user
[Trello card](https://trello.com/c/TVkDk1Oe)
> Default the assignee filter on the publications page

- test/integration/root_overview_test.rb
- test/integration_test_helper.rb
[Trello](https://trello.com/c/wucvIcYg/205-upgrade-publications-page-search-filter)
The changes in this PR add a number of tests from the legacy Publications page and refactors them for the new Design System UI. The tests are based on the legacy tests in `/test/integration/legacy_root_overview_test.rb`.
Some legacy tests have not been ported to the Design System as they raise a number of issues about changed or missing functionality that will be dealt with separately. Details of these are in the Trello card.
> 205 filter publications UI root overview tests

- Gemfile
- Gemfile.lock
- app/lib/fact_check_email_handler.rb
- script/mail_fetcher
- test/integration/fact_check_email_test.rb
- test/unit/lib/fact_check_email_handler_test.rb
Inspired by https://github.com/alphagov/search-api-v2/pull/209
This adds the prometheus-client gem, and then uses it to send fact check emails metrics to prometheus via the pushgateway.
We can't use the conventional prometheus collector, because this code runs as a script, rather than a web process.
~This should not be merged until we've set the PROMETHEUS_PUSHGATEWAY_URL environment variable.~ (edit: this is already set automatically for all apps)
In terms of testing this, we could probably just deploy this branch to integration, then see whether we can see the new metric in prometheus, then put some broken emails in the inbox (?) and see if the count goes up?
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/developme …
> Push fact check metrics to prometheus

- script/mail_fetcher
This is job is currently erroring in all environments, albeit after it's already done all the important work.
{"@timestamp":"2024-09-16T13:05:05.605Z","message":"Finished running MailFetcher in production mode - 2024-09-16 13:05:05 UTC","level":"INFO","tags":["rails"]}
script/mail_fetcher:58:in `<main>': uninitialized constant Prometheus::Client::Push (NameError)
Prometheus::Client::Push.new(
Note the "Finished running MailFetcher in production mode" log before the error
- the script has still done everything it needs to, it just hasn't sent the metrics, which fortunately is on the very last line of the script.
This looks like the same mistake I made when doing metrics for publishing-api:
https://github.com/alphagov/publishing-api/commit/30374578660e126bd49e3654ebe0ebf3ce2a3dff
We need to …
> require prometheus client libs in mail_fetcher

- app/assets/javascripts/modules/downtime_message.js
Polyfills closest are no longer available in publishing components and hence we are removing its require.
> Remove require for polyfills closest as its no longer available

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/editions_controller.rb
- app/helpers/tabbed_nav_helper.rb
- app/views/editions/_secondary_navigation.html.erb
- app/views/editions/show.html.erb
- config/routes.rb
- test/integration/edition_edit_test.rb
- test/unit/helpers/admin/tabbed_nav_helper_test.rb
Add sub nav items and default render show edit path for each of the sub nav items.
_Note_: Changes also include Gemfile.lock change although no gem file change, this is to update to latest publishing component gem.
> Add Sub Navigation component to Edit page

- app/assets/stylesheets/application.scss
- app/controllers/artefacts_controller.rb
- app/controllers/editions_controller.rb
- app/helpers/tabbed_nav_helper.rb
- app/views/editions/secondary_nav_tabs/_metadata.html.erb
- app/views/editions/secondary_nav_tabs/_temp_nav_text.html.erb
- app/views/editions/show.html.erb
- test/functional/editions_controller_test.rb
- test/integration/edit_artefact_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/N4sWF2NI/425-metadata-tab-edit-page)
Move Metadata tab to new design system
> 425 metadata tab edit page

- app/assets/stylesheets/bootstrap_and_overrides.scss
[Trello](https://trello.com/c/j3xsgpqe)
These changes add a number of over-ride styles to existing bootstrap styles that became necessary after the upgrade to Dart Sass. 
The need for these became evident in the request receive to fix a problem that became evident after that upgrade (detailed in the Trello card), concerning the user's ability to remove a selection from a dropdown selector. Upon closer inspection it became apparent that a number of other over-ride styles were required to restore some instances of broken UI as follows (see screenshots below): 
- The crown is missing in the header
- The dropdown is missing the remove and arrow icons
- The Select2 search bar is missing the search icon and some shading around the box
- The Select2 search bar in active state is missing the …
> 454 customise select2 styles

- app/controllers/application_controller.rb
- app/controllers/editions_controller.rb
- app/controllers/legacy_editions_controller.rb
- app/controllers/root_controller.rb
- app/models/edition.rb
- app/models/user.rb
- app/presenters/filtered_editions_presenter.rb
- config/features.rb
- test/functional/editions_controller_test.rb
- test/functional/legacy_editions_controller_test.rb
- test/functional/root_controller_test.rb
- test/models/edition_test.rb
- test/models/user_test.rb
- test/test_helper.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
Prevent non-GDS users from accessing editions that are "owned" by other organisations. GDS users will still see all editions.
Introduces the concept of editions having an array of owning organisations, as represented by an array of those organisations' slugs.
The organisation slug is used as it is the only information we have to tie a user to an organisation (via the user's `organisation_slug`).
This is part of our work to open up Mainstream Publisher to users outside of GDS.
This PR does not include assigning any content items to organisations—that will follow as a separate piece of work. This means that, for now, turning on the feature toggle will result in non-GDS users simply seeing no content in Mainstream Publisher.
The changes are behind a new feature toggle …
> Restrict access to publications based on the user's organisation

- app/views/editions/secondary_nav_tabs/_metadata.html.erb
- app/views/editions/show.html.erb
This is a small change on the edit page to move the `<div class="govuk-grid-column-two-thirds">` container from the main page view to the partial that displays the tabbed content. It is needed to render the sidebar on any tabbed content that requires that and will not effect the way the page currently displays. 
This makes that change retrospectively on the metadata tab but will be needed on all the other tabs created from this point on.
> Update grid to allow display of sidebar on some tabs

- app/assets/stylesheets/editions.scss
- app/views/downtimes/delete.html.erb
- app/views/downtimes/edit.html.erb
- app/views/downtimes/index.html.erb
- app/views/downtimes/new.html.erb
- app/views/editions/secondary_nav_tabs/_metadata.html.erb
- app/views/editions/secondary_nav_tabs/_temp_nav_text.html.erb
- app/views/editions/show.html.erb
- app/views/layouts/design_system.html.erb
- app/views/reports/index.html.erb
- app/views/root/index.html.erb
[Trello](https://trello.com/c/Q7Gx5wiI/486-amend-design-system-layout-to-make-correct-use-of-the-grid-system)
These changes updates the Design System template to apply the `govuk-grid-row` wrapper on each view rather than globally. This is necessary to ensure that the Design System Grid is fully utilised throughout the app, by allowing the `govuk-grid-row` wrapper to be able to be used multiple times in each view where required.
In summary:
- Delete `govuk-grid-row` wrapper from Design System template
- Add `govuk-grid-row` wrapper to
- Publications view
- Downtimes views
- Reports view
- Edit views
> Amend Design System layout to make correct use of the grid system

- app/views/homepage/popular_links/confirm_destroy.html.erb
- app/views/homepage/popular_links/edit.html.erb
- app/views/homepage/popular_links/show.html.erb
[Trello](https://trello.com/c/Q7Gx5wiI/486-amend-design-system-layout-to-make-correct-use-of-the-grid-system)
This is a further set of changes related to [PR2377](https://github.com/alphagov/publisher/pull/2377) to update the markup structure for the grid system. These changes are to the Popular Links pages.
> Update popular links views for updated grid

- app/controllers/content_item_controller.rb
- config/routes.rb
- test/functional/content_item_controller_test.rb
[Trello](https://trello.com/c/8XrdpwX2/484-browser-extension-doesnt-work-on-transitioned-publication-page-publications-page?filter=label:Design%20System%20MVP)
As Mainstream publisher moves to new design sytem, we would need to make changes to the current external link that navigates to filter publication page, we did discuss [different options](https://docs.google.com/document/d/1DPl6MuUPDMLqRHjvbt3ByJyGVQT_F8on0Ek_-udcgjE/edit?tab=t.0) we had to make this work.
This PR is coupled with the [changes in browser extension ](https://github.com/alphagov/govuk-browser-extension/pull/212)
> Add route for browser extension to get routed to publisher

- lib/tasks/publish_missed_scheduled_editions.rake
- test/unit/tasks/publish_missed_scheduled_editions_test.rb
[Trello card](https://trello.com/c/FDV98XMH/489-ensure-scheduled-editions-are-published-mainstream)
Daily cronjob is set up to run this rake task in govuk-helm-charts [PR](https://github.com/alphagov/govuk-helm-charts/pull/2716)
> Crating a rake task to publish any missed scheduled editions

- app/presenters/formats/edition_format_presenter.rb
- test/support/presenter_test_helpers.rb
- test/test_helper.rb
- test/unit/presenters/formats/answer_presenter_test.rb
- test/unit/presenters/formats/completed_transaction_presenter_test.rb
- test/unit/presenters/formats/edition_format_presenter_test.rb
- test/unit/presenters/formats/guide_presenter_test.rb
- test/unit/presenters/formats/help_page_presenter_test.rb
- test/unit/presenters/formats/licence_presenter_test.rb
- test/unit/presenters/formats/local_transaction_presenter_test.rb
- test/unit/presenters/formats/place_presenter_test.rb
- test/unit/presenters/formats/simple_smart_answer_presenter_test.rb
- test/unit/presenters/formats/transaction_presenter_test.rb
This is a new field that will allow us to identify the last person who has edited an Edition within the Publishing API.
> Send `last_edited_by_editor_id` to Publishing API

- test/functional/editions_controller_test.rb
The test was failing, depending on the running order of tests. Update
the test to follow the same pattern as other tests in the file.
> Fix a flakey test

- app/constraints/allowed_content_types_constraint.rb
- app/constraints/new_design_system_constraint.rb
- config/routes.rb
- test/integration/routes_test.rb
For incremental release of new design system pages, we want to restrict them with content types and only Answer Edition and Help Page Edition are to be released first.
[Trello](https://trello.com/c/omH0r8co/499-restrict-edit-page-changes-to-help-page-answer-content-types)
> Add constraint to allow only Answer Edition and Help Page Edition

- app/assets/stylesheets/editions.scss
- app/views/editions/secondary_nav_tabs/_edit.html.erb
- app/views/editions/secondary_nav_tabs/_metadata.html.erb
[Trello](https://trello.com/c/CHePz7xP/407-edit-answer-help-content-types-edit-page)
The changes in this PR make a couple of small changes on the Edit and Metadata tabs (screenshots below). The reason for the changes to the label/legend elements on the Metadata tag is to be consistent across Publisher and render these elements just as a `<label>` or `<legend>` without wrapping them in a header tag which is better for accessibility. 
- Edit:
- Increases the depth of the body field
- Adds a rule above change note section (does not display when the change note is not rendered)
- Metatags:
- remove headings from label/legend (no visual changes - removes the `<h3>` tags from the label and legend)
|Current|Updated|
|-|-|
|Admin tab|Admin tab|
|![Screenshot 2024-11-12 at 13 16 …
> Design changes

- app/assets/stylesheets/editions.scss
- app/controllers/editions_controller.rb
- app/views/editions/secondary_nav_tabs/_admin.html.erb
- app/views/editions/secondary_nav_tabs/confirm_destroy.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/SJf1WFqO/456-admin-delete-edition-button-confirmation-page-edit-admin)
Add delete addition functionality to admin page.
Draft edition
fact check edition
confirm delete page
delete success message
> Add delete to admin tab

- app/presenters/filtered_editions_presenter.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
The view calls `#editions` three times, which means it is querying the database three times; memoize the result so that it is only querying the database once.
> Memoize FilteredEditionsPresenter.editions

- lib/tasks/access_and_permissions.rake
- test/unit/tasks/access_and_permissions_test.rb
Two tasks are added that allow us to:
- Assign permissions on a case by case basis for specific artefacts
- Assign an org permission to a group of artefacts from a CSV file containing rows of URLs
There is no easy way to find the OrgID from an org name so OrgID must be provided by us when using it in the rake tasks.
https://trello.com/c/60RkKgwP/478-rake-task-to-set-owning-org-for-hmrc-content-mainstream
> Add rake task to assign access permissions for an organisation

- app/assets/stylesheets/application.scss
[Trello](https://trello.com/c/kbJAW2Ds/528-scss-not-compiling-publisher)
This deals with a problem in how the Sass is compiled that was causing an error when trying to update to a later version of the Publishing Components gem.
There is a reference in the `application.scss` file that duplicates an import in the gem and isn’t required here as that file is already imported in the gem itself. This is causing the SCSS to fail to compile in this app.
Removing the reference to that allows the SCSS to compile successfully and displays the styles on the app as expected. 
This will then allow the updated Publishing Components gem to be included in Publisher.
> Remove duplicate import in `application.scss`

- app/controllers/editions_controller.rb
- app/helpers/tabbed_nav_helper.rb
- app/views/editions/secondary_nav_tabs/_edit_assignee.html.erb
- app/views/editions/show.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
Add an edit link to the document summary (at the top of the page) when viewing an edition with the GOV.UK Design System template.
On the Bootstrap UI this was managed as just another dropdown field on the "Edit" tab. With the new Design System views, the edit link takes the user to a separate page for selecting the user to be assigned.
[Trello card](https://trello.com/c/NMCUGhvR)
> Enable editing the person assigned to an edition

- app/controllers/editions_controller.rb
- app/helpers/editions_helper.rb
- app/views/editions/secondary_nav_tabs/_admin.html.erb
- app/views/shared/_clone_buttons.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/qLZmHXIu/472-admin-update-content-type-edit-admin?filter=label:Design%20System%20MVP)
Adds the functionality for the user to update the content type of a document on the Admin tab. The work involves
- adding a new partial for the Admin tab
- adding the `duplicate` method to the editions controller
- updating the editions controller test 
- updating the edit editions test
- a bit of renaming of methods in the editions helper and where these are used in the legacy code
|View|Screenshot|
|-|-|
|Admin tab|![Screenshot 2024-11-22 at 12 43 36](https://github.com/user-attachments/assets/0ba2b00e-6b45-4d11-86d3-7ae8ded55971)|
|Redirect to edit page on success|![Screenshot 2024-11-22 at 12 47 38](https://github.com/user-attachments/assets/0f7ddf16-f167-4908-a104-b1945b …
> 472 admin tab update content type

- app/controllers/link_checker_api_controller.rb
- app/services/link_check_report_creator.rb
- config/application.rb
- config/initializers/secrets_to_credentials.rb
- test/functional/link_check_reports_controller_test.rb
- test/functional/link_checker_api_controller_test.rb
- test/integration/edition_link_check_test.rb
- test/unit/services/link_check_report_creator_test.rb
Rails 7 has begun to deprecate Rails.application.secrets in favour of Rails.application.credentials, this would ideally need to be fixed by getting secrets from environment variables probably through app config though its a bigger change that we intend to do and for now we have taken this approach of merging secrets with credentials and then just using credentials to stop the noise around deprecation warnings.
> Move secrets to credentials to stop secrets deprecation warning

- app/views/legacy_editions/_content_block_guidance.html.erb
- app/views/legacy_editions/show.html.erb
- config/features.rb
- test/integration/edition_edit_test.rb
https://trello.com/c/UZJt5Je1/703-update-mainstream-publisher-to-allow-insert-journey
To allow user testing of the "insert" journey for Content Modelling, we need to add a link to the Content Block Manager in the sidebar when editing content. This is enabled by a feature flag, which is set to true by default in Staging/Integration.
> (703) Add Content Block guidance to Whitehall in non-production environments

- app/views/editions/secondary_nav_tabs/_admin.html.erb
[Trello](https://trello.com/c/qLZmHXIu/472-admin-update-content-type-edit-admin)
This makes a small update post desk-check to change the button text on the admin tab from "Update" to "Save". 
|Current|Update|
|-|-|
|![Screenshot 2024-12-02 at 15 31 54](https://github.com/user-attachments/assets/30418835-e596-48a8-9193-861370f6f2e8)|![Screenshot 2024-12-02 at 15 31 32](https://github.com/user-attachments/assets/b4069afc-5f59-41c3-9d11-58e4df026a76)|
> Update button text from "Update" to "Save"

- lib/tasks/test.rake
Rake task for test has been generating alot of noise "Non US-ASCII detected and no charset defined.
Defaulting to UTF-8, set your own if this is incorrect.". Have tried to fix the warning itself to no avail and hence just suppressing it.
> Supress warnings

- app/helpers/editions_helper.rb
- app/helpers/tabbed_nav_helper.rb
- app/views/editions/show.html.erb
- test/integration/edition_edit_test.rb
This PR addresses two comments from desk-checking the edit assigned to story:
* It displays the text "None" in the document summary when nobody is assigned to an edition.
* It doesn't show users that would not be able to edit an edition in the list of available users to assign to.
## Trello
[Trello card](https://trello.com/c/NMCUGhvR/408-edit-assigned-to-for-answer-and-help-content-types-edit-page)
> Edit assignee updates following desk check

- app/controllers/content_item_controller.rb
- test/functional/content_item_controller_test.rb
- test/integration/get_content_by_content_id_test.rb
[Trello](https://trello.com/c/ALBWddMn/519-implement-a-new-endpoint-for-searching-by-content-id-mainstream)
Implement an endpoint in Mainstream Publisher that takes a content ID as a parameter, and returns a redirect to the publications (search) page with the appropriate query parameters set.
Note that a route has already been created at /by-content-id/:content_id, which routes to the ContentItemController—this can be used as a starting point (this endpoint was created as part of the first attempt to fix the browser extension issue, and so is not currently in use and can safely be adapted)
Follow [these …
> Get content by content id

- app/models/edition.rb
- test/models/edition_test.rb
This is to ensure new editions have wning_org_content_ids copied from existing ones so department users can create new content
> Add owning_org_content_ids to base_field_keys

- lib/tasks/access_and_permissions.rake
- test/unit/tasks/access_and_permissions_test.rb
Update the rake task for adding owning organisations to publications so that the "updated_at" field is not updated, which given published and archived editions are being modified will avoid potential confusion of them looking like they were updated after publishing/archival.
> Update access and permissions rake task

- app/controllers/editions_controller.rb
The `destroyable_edition?` method had a misleading name, as it isn't a
querying method that returns a boolean value—it checks whether an
edition is destroyable and, if it isn't, shows a flash message and
redirects to the edition's show page.
There's already a similar method, `require_assignee_editable`, for
checking whether an edition can have its assignee updated, so rename
the method to be consistent with that one.
> Rename method to avoid misleading readers

- config/features.rb
- test/functional/editions_controller_test.rb
- test/functional/legacy_editions_controller_test.rb
- test/models/user_test.rb
- test/support/factories.rb
[Trello card](https://trello.com/c/xcawEC5F/585-release-permissions-for-hmrc-content-mainstream)
This is not restrict access to Mainstream content for departments outside of GDS
> Change default to true for restrict_access_by_org feature

- app/views/root/_table.html.erb
- test/functional/root_controller_test.rb
- test/integration/root_overview_test.rb
[Trello](https://trello.com/c/jVusqS9k/538-display-the-slug-in-the-table-on-the-publications-page-publications-page)
> Add slug text for editions listed on publications table

- app/controllers/content_item_controller.rb
- app/controllers/root_controller.rb
- app/models/edition.rb
- app/presenters/filtered_editions_presenter.rb
- app/views/root/_filter.html.erb
- test/functional/root_controller_test.rb
- test/integration/root_overview_test.rb
- test/integration_test_helper.rb
- test/models/edition_test.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
Update the search box on the Design System-ed publications (root) page filter to search by title and slug, instead of just searching the title. This brings the behaviour more inline with how it works on the Bootstrap UI.
Also update some labels on the Design System-ed publications (root) page filter, following a review by the team.
[Trello card](https://trello.com/c/Ur6nAo1J)
> Update publications filter search box

- .github/workflows/ci_mongo_to_pg.yml
- .github/workflows/deploy_mongo_to_pg.yml
[Add workflow to allow creating image from this branch](https://github.com/alphagov/publisher/commit/ecd5d0c5184101ec53f96ba18c9e8c3b29c6e2c7)
> Add workflow to allow creating image from this branch

- .github/workflows/deploy_mongo_to_pg.yml
Replace repo name with image name as repo name does not exists in the actual workflow
> Replace repo name with image name

- .github/workflows/actionlint.yml
This adds Github Action Linting Checks to Publisher. This makes it harder to merge broken Workflows. :-)
> Add Actionlint Github checks to Publisher Repo

- app/assets/stylesheets/application.scss
[Trello](https://trello.com/c/doZRh9Gi/587-list-imported-add-another-component-stylesheet-correctly)
When the "Add another" component is rendered in Publisher (e.g. on the "Related external links" tab) there was a problem if the standard (alphabetical) ordering of imported stylesheets was used whereby some styles specific to the component were over-written by more generic styles imported from the "Button" component. This affected the "Delete" button as shown in the screenshots below. 
To get around this the stylesheets were imported in a different order so that styles for the "Add another" component were imported after the "Button" component. This has now been fixed in the Publishing Components gem so the stylesheets can be imported in alphabetical order.
The change in this PR restores …
> Restore correct ordering for imported stylesheets

- app/assets/stylesheets/application.scss
- app/views/layouts/design_system.html.erb
- test/integration/edition_edit_test.rb
Replace the title component with the heading component.
- should still be a h1 and visually identical
- heading has no margin top, so matches the previous margin_top: 0 option on title
Confession: I've not actually run this locally to check it visually, but I've done this in a lot of applications now and I'm reasonably confident it will work.
The title component is being decommissioned and we've already removed the margin_top option from it as part of some other work. This means that with the latest changes a big space will suddenly appear above it. But if we switch it to the heading component, it looks exactly …
> Replace title component with heading

- .github/workflows/deploy_mongo_to_pg.yml
We're now correctly building the PG branch of Publisher but trying to update the wrong Argo App tag. This should fix it.
> Override the app name for the PG version

- Gemfile.lock
- app/views/editions/secondary_nav_tabs/_related_external_links.html.erb
- test/integration/edition_edit_test.rb
- test/integration/edition_external_links_test.rb
[Trello](https://trello.com/c/0eYge9vM)
The changes here implement the latest release of the Publishing Components gem (version 51.0.0) that contains the configuration option added to the "Add another" component that allows its use on Mainstream as required. This adds the parameter `empty_fields` to the component, which, when set to "true" ensures that no form fields are displayed when the component loads if no content is specified. Additionally these changes update the tests for the changed UI.
They also update the button text from "Add another link" to "Add related external link".
The primary differences between this implementation and the current one are shown in the screenshots below. 
|Scenario|Current implementation|Latest component version|
|-|-|-|
|Loads with no links specified …
> 497 use updated add another component

- app/presenters/filtered_editions_presenter.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
Update the list of users in the “Assigned to” dropdown to move the current user to the top of the list, under “All assignees” and append (You).
Trello: https://trello.com/c/xBKmLTnk/539-move-logged-in-user-to-top-of-assigned-to-list-in-publications-filter-publications-page
> Add user to top assignee list

- app/controllers/editions_controller.rb
- app/controllers/legacy_notes_controller.rb
- app/helpers/tabbed_nav_helper.rb
- app/views/editions/secondary_nav_tabs/_history.html.erb
- app/views/editions/secondary_nav_tabs/add_edition_note.html.erb
- app/views/shared/_history.html.erb
- config/routes.rb
- test/functional/legacy_notes_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/6SZW0if6/558-add-edition-note-edit-page-history-and-notes)
Adds the ability for a user to add an edition note to an edition:
- Adds a new view for the "History & Notes" tab
- Adds a new view for the "Add edition note" page
- Update `edition_edit_test` for the new "History and notes" tab
- Updates `edition_edit_test` for the new "Add edition note" page
- Adds a new `notes_controller` and renames the existing one to `legacy_notes_controller`
- Adds a new `note_controller_test` and renames the existing one to `legacy_note_controller_test`
|View|Visual|
|-|-|
|"History and notes" tab|![Screenshot 2025-02-04 at 10 47 34](https://github.com/user-attachments/assets/b8d95525-fc1d-46f5-b870-40bb107e95b6)|
|"Add edition note" page|![Screenshot 2025-02-04 at 10 50 …
> 558 history notes tab add edition note

- app/controllers/editions_controller.rb
- config/routes.rb
For tabs that have not been upgraded to the GOV.UK Design System view yet, it should not give an error, but just show a tab pane consisting of a "Work in progress" message. This was what was originally implemented, but has got broken as the other tabs were fleshed out.
There's no tests for this, since it's just a placeholder, and the whole design system implementation for the show/edit page is behind a feature flag.
> Show a "work in progress" message on tagging tab

- app/views/root/_filter.html.erb
When we updated the search on the publications page to search the “slug” field of editions we used some custom text for the hint text attribute of the 'Checkbox' component (see [PR#2508](https://github.com/alphagov/publisher/pull/2508)). This was to display the text without the full stop (the default value for hint text in the component). We also raised an [issue](https://github.com/alphagov/govuk_publishing_components/issues/4589) in the Publishing Components to remove the full stop in the default hint text.
The work has now been done to resolve that issue (see [PR#4609](https://github.com/alphagov/govuk_publishing_components/pull/4609)) and the change is now released in the latest version of the Publishing Components gem. 
The change here removes the custom hint text in the rendered …
> Remove custom hint text from Select component

- app/controllers/editions_controller.rb
- app/views/editions/secondary_nav_tabs/request_amendments_page.html.erb
- app/views/editions/show.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/IZQtoxMn/608-2i-reviewer-actions-request-amendments-for-answer-and-help-content-types)
These changes: 
- Adds a 'Request amendments' link to the Edit page if
- the document is "In Review"
- the current user is not also the 2i requester 
|Edit page (current)|Edit page (updated)|
|-|-|
|![Screenshot 2025-02-17 at 16 58 17](https://github.com/user-attachments/assets/83e5a244-41bc-483a-8ea2-a03112445c66)|![Screenshot 2025-02-17 at 16 58 00](https://github.com/user-attachments/assets/4cb61513-8649-474e-9f85-23d8909fdd31)|
- Creates a new 'Request amendments' page for the user to add an option comment and request amendments to an edition.
|-|-|
|User clicks 'Request amendments' link and is taken to the new 'Request amendments' page|![Screenshot …
> 608 2i reviewer request amendments

- app/controllers/editions_controller.rb
- test/functional/editions_controller_test.rb
[Trello](https://trello.com/c/IZQtoxMn/608-2i-reviewer-actions-request-amendments-for-answer-and-help-content-types)
Updates the controller to prevent users without the `govuk_editor` permission from 
- accessing the 'Request amendments' page
- being able to save an amendment request
This matches (and slightly extends) the current behaviour which
- allows a user without govuk_editor permission to access the form (which is an overlay on the same page)
- does not allow that user to save a request
|Scenario|Bootstrap UI|Design System UI|
|-|-|-|
|User on the Edit page without govuk_editor permission clicks on 'Request amendment' button|![Screenshot 2025-02-20 at 12 37 56](https://github.com/user-attachments/assets/ecb0d018-6f33-4c54-bee8-241b689dacd9)|![Screenshot 2025-02-20 at 12 37 …
> Updates behaviour for users without govuk_editor permissions

- .github/workflows/minitest.yml
- Gemfile
- app/helpers/publications_helper.rb
- app/helpers/tabbed_nav_helper.rb
- app/lib/tagging/tagging_update_form.rb
- app/models/action.rb
- app/models/application_record.rb
- app/models/artefact.rb
- app/models/artefact_action.rb
- app/models/edition.rb
- app/models/user.rb
- app/models/workflow.rb
- app/presenters/filtered_editions_presenter.rb
- app/views/legacy_editions/_reviewer_field.html.erb
- config/application.rb
- config/database.yml
- db/migrate/20250212162143_create_user.rb
- db/schema.rb
- db/seeds/user.rb
- test/functional/event_mailer_test.rb
- test/functional/event_notifications_test.rb
- test/legacy_integration_test_helper.rb
- test/models/edition_test.rb
- test/models/user_test.rb
- test/test_helper.rb
- test/unit/helpers/admin/publications_table_helper_test.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
Move User table to postgres and support any existing relation with other models using temporary foreign key.
All the temporary code changes are earmarked with comments to allow assistance when we would undo them.
Note: there is a test failure on test/models/edition_test.rb: should "have a database-level constraint on the uniqueness"
This has been hard to debug, the test passes locally and will change in near future, hence investing any more time trying to fix it might not be worth it.
> Move Users table to postgres

- app/helpers/editions_sidebar_buttons_helper.rb
- app/views/editions/secondary_nav_tabs/_edit.html.erb
- app/views/editions/secondary_nav_tabs/edit/draft/_body.html.erb
- app/views/editions/secondary_nav_tabs/edit/draft/_common_fields.html.erb
- app/views/editions/secondary_nav_tabs/edit/draft/_public_change_note.html.erb
- app/views/editions/secondary_nav_tabs/edit/published/_body.html.erb
- app/views/editions/secondary_nav_tabs/edit/published/_common_fields.html.erb
- app/views/editions/secondary_nav_tabs/edit/published/_public_change_note.html.erb
- test/integration/edition_edit_test.rb
[Trello card](https://trello.com/c/5EuyRleF)
Display a published edition's content as read-only on the "edit" tab when viewing an edition.
Also implements a sidebar, allowing users to view a later draft edition (if one exists), or create a new draft edition (if one doesn't already exist), and also view the published page on GOV.UK.
|-|-|
|Viewing a published edition before the changes in this PR|![published-view-before](https://github.com/user-attachments/assets/eba09f0b-7afb-4ab1-81ba-98f34d451eda)|
|Viewing a published edition when a draft edition does not exist|![published-view-after-no-later-draft](https://github.com/user-attachments/assets/90100237-a2ff-447a-b804-a081b56d533c)|
|Viewing a published edition when a draft edition …
> Edit page for published editions

- test/traits/recordable_actions_test.rb
This resolves the following warning generated when running the tests:
```
DEPRECATED: Use assert_nil if expecting nil from test/traits/recordable_actions_test.rb:44. This will fail in Minitest 6.
```
> Replace assert_equal nil with assert_nil

- test/integration/host_content_update_history_test.rb
The test fails intermittently with the error:
```
Capybara::ElementNotFound: Unable to find visible css ".action-content-block-update" within #<Capybara::Node::Element tag="div" path="/HTML/BODY[1]/SECTION[1]/MAIN[1]/DIV[1]/DIV[2]/DIV[1]/DIV[4]/DIV[1]/DIV[3]/DIV[2]/DIV[3]">
```
This seems to be because the expanding of the edition panel is not always completing before the check for the "content block update" element occurs. Adding the extra `within` selector for the `.collapse.in` classes to be present (which happens once the "expand" animation has completed) appears to at least make the test more reliable (I can't really be 100% sure it's completely resolved, but I've run the test dozens of times locally now without failure).
> Fix flakey test due to Javascript animation timing

- app/helpers/editions_sidebar_buttons_helper.rb
- app/views/editions/secondary_nav_tabs/_edit.html.erb
- app/views/editions/secondary_nav_tabs/_edit_assignee.html.erb
- app/views/editions/secondary_nav_tabs/_history.html.erb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
Updates following a desk check for [the Trello ticket](https://trello.com/c/5EuyRleF).
- Make the "View on GOV.UK" links link to the edition being viewed, not the GOV.UK homepage.
- Increase spacing between items in the sidebar.
- Some code cleanup.
> Edit page for published editions desk check updates

- app/models/host_content_update_event.rb
- test/models/host_content_update_event_test.rb
When an edition is archived, but not published, this was raising an error, as `edition.publised_at` was nil. This adds an additional check to see if the edition had ever been published. If not, then we know this update didn’t occur during the lifecycle of this edition, as it was never public.
> `#is_for_edition?` is false when not published

- app/controllers/application_controller.rb
- app/models/edition.rb
- app/models/user.rb
- test/functional/editions_controller_test.rb
- test/functional/legacy_editions_controller_test.rb
- test/models/edition_test.rb
- test/support/factories.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
[Trello card](https://trello.com/c/HQmmcxJl/599-access-permissions-add-departmentaleditor-permission)
This is to enable specifying restriction to access Mainstream content by departments. It is an addition to giving access by matching owning_org_content_ids with users organisation_content_id, to ensure we do not block access for some departments.
> Add a check for departmental_editor? permission for user

- app/controllers/editions_controller.rb
- app/lib/edition_progressor.rb
- app/views/editions/secondary_nav_tabs/_progress_with_comment.html.erb
- app/views/editions/secondary_nav_tabs/no_changes_needed_page.html.erb
- app/views/editions/secondary_nav_tabs/request_amendments_page.html.erb
- app/views/editions/show.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello card](https://trello.com/c/gohxJSrY)
Add a "no changes needed" link to the show view of editions when the user has the relevant permissions.
| Scenario  | View |
| --- | --- |
| Viewing an "in review" edition before the changes in this PR  | ![image](https://github.com/user-attachments/assets/6334b4b9-66c7-4b8e-a3d5-60a05e118f24) |
| Viewing an "in review" edition with the changes in this PR | ![image](https://github.com/user-attachments/assets/d1f87d80-303c-49ea-8187-8eed1c11ff28) |
| The view displayed after clicking the "no changes needed" link  | ![no-changes-needed-page](https://github.com/user-attachments/assets/332e3d84-5bb5-4f72-82cb-7ee799224c73) |
| Viewing an edition after the "no changes needed" page has been submitted | …
> Implement "no changes needed" link for "In review" editions

- .github/workflows/copy-pr-template-to-dependabot-prs.yml
- .github/workflows/minitest.yml
- test/support/govuk_test.rb
Use an older version of chrome for integration test runs as there is an ongoing 
issue with more recent versions which is causing random test failures
> Pin chrome version for integration tests

- app/views/editions/_important_note.html.erb
- test/integration/edition_edit_test.rb
Now uses govuk format but only for the date (time is excluded) This follows the format requested on the [Trello card](https://trello.com/c/8Mrwt4nG) for Update Important note. 
> Fix to date format for current important note text

- .github/workflows/minitest.yml
Remove the use of a GitHub action from an unverified publisher, and just
use the "setup-chrome" action from a verified one.
Also pins the version of the action referenced to a specific sha as a
security precaution, as recommended by the [developer docs](https://gds-way.digital.cabinet-office.gov.uk/standards/source-code/use-github.html#using-github-actions-and-workflows).
> Simplify chrome version pinning in minitest action

- app/controllers/editions_controller.rb
- app/helpers/edition_activity_buttons_helper.rb
- app/lib/govuk_content_models/action_processors/skip_review_processor.rb
- app/models/user.rb
- app/views/editions/secondary_nav_tabs/skip_review_page.html.erb
- app/views/editions/show.html.erb
- app/views/shared/_review.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
- test/models/user_test.rb
- test/support/factories.rb
Adds a link to the edit page of an edition that takes the user to a page enabling them to skip the review stage.
The link (and linked page) are only available to users with the "skip_review" permission, and only the person that sent the edition for review can skip the review.
> Add skip review functionality

- app/views/editions/secondary_nav_tabs/_progress_with_comment.html.erb
- app/views/editions/secondary_nav_tabs/skip_review_page.html.erb
- test/integration/edition_edit_test.rb
This text was missed off in the original implementation.
[Trello card](https://trello.com/c/tb2kCEel/605-skip-review-link-for-answer-and-help-content-types)
> Add text to "skip review" page

- app/views/editions/secondary_nav_tabs/_edit.html.erb
- app/views/editions/show.html.erb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/oOBPngB2/624-edit-page-for-archived-edition-answer-and-help)
This implements the Edit page for an 'Archived' edition. Essentially it displays the data in read only mode rather than in form fields, using the same headings: 
- Edit
- Title
- Meta tag description
- Is this beta content?
- Body
- Public change note
Additional requirements are
- The 'Unpublish' tab should not be displayed in this scenario. This has already been implemented in a previous piece of work so there are no changes for that requirement here. 
- A message should be displayed to the user when all editions have been unpublished
> 624 edit page archived edition

- app/models/host_content_update_event.rb
- test/integration/edition_edit_test.rb
- test/models/host_content_update_event_test.rb
https://trello.com/c/RxmJ0fe2/977-allow-updates-to-objects-to-appear-in-the-history-and-notes-for-mainstream-draft-editions-story
Previously an event would only show in the
Edition's "history and notes" if the event took
place after the Edition had been published (and if
it was not archived/superseded).
We now want to display event if it took place at
any time after an Edition's creation, IF it is not
archived.
---
> show Content Block update events on in progress Hosts

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/edit.scss
- app/views/editions/secondary_nav_tabs/_edit.html.erb
- app/views/editions/secondary_nav_tabs/edit/published/_body.html.erb
- app/views/editions/secondary_nav_tabs/edit/published/_common_fields.html.erb
- app/views/editions/secondary_nav_tabs/edit/published/_public_change_note.html.erb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/oOBPngB2/624-edit-page-for-archived-edition-answer-and-help)
The changes here (somewhat circuitously) updates how `govuk-body` styles are applied to all `<p>` elements within the read-only content on the Edit page for editions in 'Published' and 'Archived' states. This is necessary to remove the browser-applied top margin to these elements, specifically on the 'body' section. We can only do this by applying the `govuk-body` style directly to the `<p>` element rather than to its parent as it is currently implemented. Since this cannot be done in the 'body' section the alternative approach is to apply the style via a custom stylesheet. 
This is achieved by
- removing the `govuk-body` class from elements on the page
- grouping sections together with the …
> 624 edit page add custom styles

- app/helpers/editions_sidebar_buttons_helper.rb
- test/integration/edition_edit_test.rb
Applies a fix for the missing sidebar buttons for an in-review edition, caused by [Send to 2i link and page](https://trello.com/c/dQepazi0) https://github.com/alphagov/publisher/pull/2618
Adds tests for an edition in the 'in review' (Sent to 2i) state to hopefully catch any similar issues in future.
> Fix sidebar buttons helper to return button array

- app/assets/stylesheets/edit.scss
- app/helpers/editions_helper.rb
- app/helpers/editions_sidebar_buttons_helper.rb
- app/models/workflow.rb
- app/views/editions/secondary_nav_tabs/_edit.html.erb
- app/views/shared/_edition_header.html.erb
- test/integration/edition_edit_test.rb
- test/models/workflow_test.rb
[Trello card](https://trello.com/c/kOQyhYC9)
Implement the content of the "edit" tab when viewing an edition that is scheduled for publishing so that the content is read-only (using paragraph elements instead of form controls to display the field values).
Also implements a few other related changes:
- removes the date and time that the edition is scheduled to be published at from the tag displayed on the "edition" row of the document summary
- adds a "scheduled" row to the document summary to show the date and time that the edition is scheduled to be published at
- adds a "preview" link to the sidebar.
> Edit page for scheduled edition

- app/views/editions/secondary_nav_tabs/no_changes_needed_page.html.erb
- app/views/editions/secondary_nav_tabs/request_amendments_page.html.erb
- app/views/editions/secondary_nav_tabs/send_to_2i_page.html.erb
- app/views/editions/secondary_nav_tabs/skip_review_page.html.erb
This was prompted by a discussion during the Desk Check for [Trello Card]( https://trello.com/c/dQepazi0)
In order to simplify the code, encourage reuse (make it DRY) and to make future formatting changes easier, the Send to 2i page has been adapted to use the same partial as 'Request amendments', 'Skip review' and 'No changes needed' pages. 
Also, in response to the feedback from the 'Send to 2i' desk check: 
- A label has been added to the comment textfield for the Send to 2i page
- The link in the copy above the textfield has been changed to the GOV.UK style
> Refactor send to 2i page to use partial

- app/controllers/editions_controller.rb
- app/helpers/editions_sidebar_buttons_helper.rb
- app/views/editions/secondary_nav_tabs/cancel_scheduled_publishing_page.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello card](https://trello.com/c/4Fg28ZKf/625-cancel-scheduling-for-scheduled-edition-answer-and-help)
Adds the flow for cancelling the scheduling of a publish of an edition when it is currently scheduled for publishing.
> Cancel scheduling for scheduled edition

- app/helpers/editions_sidebar_buttons_helper.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
**WHAT**
Implement Publish button and process for Ready edition.
-------------
[Trello card](https://trello.com/c/ljJbaP3q)
|-|-|
|The Publish button shows when the edition is in a ready state, and user has the right permissions.|![Visible publish button](https://github.com/user-attachments/assets/331891ef-c89a-49ae-bc91-f8f3c3ce640e)|
|Clicking the button sends the user to the send to Publish confirmation page. User can enter optional comments, and click the Send to Publish button to publish the edition. Cancel button takes the user back to the Edit tab.|![Visible publish button and textbox](https://github.com/user-attachments/assets/4f798544-c2ff-4f7c-8dae-81737f845f28)|
|Success message present and edition is in Published state. Edition is now edit-only.|![Edition …
> 642 publish for ready edition

- app/controllers/editions_controller.rb
- app/helpers/editions_helper.rb
- app/helpers/tabbed_nav_helper.rb
- app/views/editions/secondary_nav_tabs/edit_assignee/_edit_assignee.html.erb
- app/views/editions/secondary_nav_tabs/edit_assignee_page.html.erb
- app/views/editions/secondary_nav_tabs/edit_reviewer_page.html.erb
- app/views/editions/show.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/xT4E3nvr/602-add-2i-reviewer-to-document-summary-edit-page)
Allows the user to assign a person to be the 2i reviewer or to deselect the currently assigned user. This makes the following additions: 
- On the edit page a new row is added to the summary to show 
- the current 2i reviewer or display a message if this has not been assigned
- an "Edit" link 
- Creates a new page to edit the 2i reviewer, accessed from the "Edit" link
UI variations are shown below.
|Change to the Edit page|Before|After|
|-|-|-|
|Adds a new row to the summary for "In review" editions|![Screenshot 2025-04-07 at 14 43 37](https://github.com/user-attachments/assets/837c6f63-3e77-4cbd-ab70-8f7dbc72590b)|![Screenshot 2025-04-07 at 14 43 …
> 602 edit page edit 2i reviewer

- app/views/editions/secondary_nav_tabs/edit/draft/_body.html.erb
- app/views/editions/show.html.erb
- test/integration/edition_edit_test.rb
[Trello card](https://trello.com/c/HNQxpjxy/644-edit-page-for-ready-state-edition-answer-and-help-page)
Add a "request amendments" link below the document summary and above the tabs, on the edition "show" view.
Also fixes some duplicated text appearing in a link.
> Edit page for ready state edition

- app/controllers/editions_controller.rb
- test/functional/editions_controller_test.rb
[Trello](https://trello.com/c/xT4E3nvr/602-add-2i-reviewer-to-document-summary-edit-page)
The changes here make a few small updates to some of the messaging associated with adding/removing assignees and 21 reviewers to/from editions: 
- 2i reviewer is unassigned: changed from "The current 2i reviewer has been unassigned" to "2i reviewer removed"
- User tries to save new 2i reviewer without selecting an option: changed from "Please select a person to assign, or 'None' to unassign the currently assigned person." to "Select a person to assign"
- User tries to save new assignee without selecting an option: changed from "Please select a person to assign, or 'None' to unassign the currently assigned person." to "Select a person to assign"
See the screenshots below for updated UI. …
> 602 Update messaging for 2i reviewer and assignee

- docs/arch/adr-013-mongo-to-postgres-edition-uuid-foriegn-key.md
[Trello](https://trello.com/c/bZIvtekB/678-create-an-adr-for-postgres-id-to-be-uuid-and-save-mongoid-in-a-column)
[ADR](https://docs.google.com/document/d/1LxTYFjfJ5KMON4ZH-6QGKAx4LaSATrCQ3QN3OSCPQJY/edit?tab=t.0#heading=h.7m4tdu6y7yy8)
> Add ADR for the decision on keeping edition table primary key as a UUID

- app/controllers/root_controller.rb
- test/functional/root_controller_test.rb
Change the default from 6 of the 9 status checkboxes selected to all 9 of them unselected. This affects the initial view and the 'Reset all fields' link. Further manual testing is required to ensure that there are no regressions for the Browser extension. 
| |Original|New|
|-|-|-|
|Default (initial view) with no user changes|![6 checkboxes checked - current user selected](https://github.com/user-attachments/assets/8ff97fbe-bd46-47a9-bf0e-7a8e1d0e4155)|![No checkboxes checked -current user selected](https://github.com/user-attachments/assets/5807ee4c-6bf6-49e4-9cb5-081faa94025f)|
|Reset all fields if assignee changed|![6_checkboxes_selected](https://github.com/user-attachments/assets/40da310b-d1e3-4d48-915b-5ca12c82053e)|![no checkboxes …
> 671 remove the 6 default status checkbox

- app/controllers/editions_controller.rb
- app/views/editions/show.html.erb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
A link to 'Request amendments' for editions that are out for fact check. The existing Request amendments page is then displayed when the link is clicked, a comment can be saved by the user and the edition is changed to 'Amends needed' state.
|Current|Updated|
|-|-|
|![Existing edit page for an edition in fact check state with no link](https://github.com/user-attachments/assets/092643bd-85db-498c-9668-8fc2e292e6ff)|![New edit page with 'Request amendments' link for fact check state](https://github.com/user-attachments/assets/f5bd3b4b-4467-4312-b022-eec6ec3d106d)|
- **NOTE:** The success message has been changed to a more generic 'Amendments requested' to cover all conditions/state changes 
|-|-|
|User clicks 'Request amendments' link and is taken to the new 'Request …
> Add 'Request amendments link' for editions in fact check state

- app/controllers/editions_controller.rb
- app/helpers/editions_sidebar_buttons_helper.rb
- app/views/editions/secondary_nav_tabs/_progress_with_comment.html.erb
- app/views/editions/secondary_nav_tabs/schedule_page.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/8V0CiJv6/649-schedule-for-ready-edition-answer-and-help-page)
These changes: 
- Adds a "Schedule" button to the Edit page when: 
- the user has the correct permissions
- the edition state is 'ready'
- Adds a new "Schedule publication page" page view
- Adds the logic to 
- progress the edition to the "Schedule for publishing" state
- add success and error messages as applicable
See screenshots for UI and messaging. 
NB: There are two validations here (checking that date/time fields are not blank and are not set to a date in the past) that have been implemented by using flash messages rather than more standard validation and the error message component. There are complications around validation due to how the Edition Progressor is set up to deal with the …
> 649 schedule for ready edition

- app/assets/stylesheets/editions.scss
- app/views/editions/_important_note.html.erb
- app/views/editions/show.html.erb
A large gap between the Important note element and the Inset text was noticed as part of the desk check for [Fact check - [Request amendments] Answer and Help Page](https://github.com/alphagov/publisher/pull/2663). 
This has now been addressed so that with or without the inset text, the gap below the important note should be 30px. 
Out of scope for this is the gap which still exists between the inset text and the summary list which will be addressed as part of a design sweep. 
|-|-|
|New gap between the important note and the inset text|![New gap between the important note and inset text](https://github.com/user-attachments/assets/f15a03ee-9227-4c22-a1ae-07294b7ce7f6)|
|Gap between the important note and tab headers with no inset text|![Gap between the important note and …
> Css important note inset text improvement

- app/assets/stylesheets/edit.scss
- app/controllers/editions_controller.rb
- app/views/editions/secondary_nav_tabs/resend_fact_check_email_page.html.erb
- app/views/editions/show.html.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
[Trello](https://trello.com/c/1WJYlVC2/672-fact-check-resend-fact-check-email-for-answer-and-help-page)
These changes 
- adds a "Resend fact check email" link below the edition summary card of the edition when
- the edition is in "Fact check" state
- the user has
- “govuk_editor” permission
- “welsh_editor” permission and the edition is Welsh
- adds a new "Resend fact check email" view, displayed when the “Resend fact check email” text link is clicked. This page is a read only page displaying the message added to the fact check email and allowingn the user to resent the email. 
|Page/Scenario|View|
|-|-|
|Edit page, user has appropriate permissions|![Screenshot 2025-05-20 at 08 17 16](https://github.com/user-attachments/assets/a489875a-bf12-4954-a1ac-7859bcbfccc5)|
|Resend fact check …
> 672 fact check resend fact check email

- app/views/root/_table.html.erb
- test/integration/root_overview_test.rb
[Trello]( https://trello.com/c/mHCUk2wD/715-hide-option-to-claim-2i-on-publications-page)
This is temporary to buy time to fix bug with reviewer issue on new design system changes
> Donot show claim 2i button

- app/controllers/editions_controller.rb
- app/helpers/tabbed_nav_helper.rb
- app/views/root/_table.html.erb
- test/integration/edition_edit_test.rb
- test/integration/root_overview_test.rb
[Trello](https://trello.com/c/PpxCshge/718-fix-reviewer-issue-to-work-with-both-new-design-system-and-bootstrap)
- Fix claiming 2i by saving name of the user instead of id, as it was always saved by name and not id.
- fetch reviewer from db to show correctly for history and notes and related external links tab.
- Undo the changes to hide claim 2i changes in https://github.com/alphagov/publisher/pull/2698
> Editions reviewer fix

- app/controllers/artefacts_controller.rb
- app/views/editions/secondary_nav_tabs/_metadata.html.erb
- test/functional/artefacts_controller_test.rb
- test/integration/edition_edit_test.rb
Follows the existing permissions for Artefact. This update shows the tab as read-only with no 'update' button if the user does not have the correct permission to update the metadata for the artefact. 
|-|-|
|Previous view for all users with any permission|![Screenshot 2025-06-09 at 17 36 31](https://github.com/user-attachments/assets/2c57706e-cb81-4bbd-8623-30ad46efd710)|
|Current view if user does not have permission|![Screenshot 2025-06-09 at 17 21 40](https://github.com/user-attachments/assets/287baef9-f4a5-4367-aed0-d12a9e9bd42f)|
> 710 Fix metadata permissions

- app/controllers/artefacts_controller.rb
- test/functional/artefacts_controller_test.rb
Small fix for Metadata tab permission issue [Trello card](https://trello.com/c/XPnx8J2j)
- If update fails due to permissions, redirect back to metadata tab not edit tab
- Show correct error message
> Fix redirect - take users back to metadata tab

- app/views/editions/secondary_nav_tabs/send_to_fact_check_page.html.erb
[Trello](https://trello.com/c/Scdl2DBF/724-issue-allow-a-fact-check-to-be-sent-to-multiple-email-addresses)
This deals with a problem whereby the user is prevented from entering multiple email addresses on the "Send to fact check" page. 
This is caused by HTML5 native browser validation, a feature that we generally do not use on Publisher. It is activated here because the field we are concerned with has the "type" attribute of "email". There are a few ways we could deal with this: 
1. Set the form to not use native validation
2. Remove the “email” type from the input so native validation is not triggered
3. Add a “multiple” attribute to the input so that native validation accepts multiple email addresses
I have implemented Option 1 here as the one that makes most sense. My thinking is: 
- …
> Add `novalidate` option to form on "Send to fact check" page

- app/controllers/editions_controller.rb
- app/views/editions/secondary_nav_tabs/_history.html.erb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
Adds the permissions check for the Update Important Note and Add Note
buttons in the History and Notes tab. Should prevent any users without
permissions from easily accessing the relevant pages down the stack.
Also redirects users without permissions from the pages if they somehow
managed to find the URL.
https://trello.com/c/NpSphqXO/712-issue-publisher-fix-permissions-on-history-and-notes-tab
> Fix permissions on history and notes tab

- app/presenters/filtered_editions_presenter.rb
- app/views/root/_filter.html.erb
- app/views/root/_table.html.erb
- test/functional/root_controller_test.rb
- test/integration/get_content_by_content_id_test.rb
- test/integration/root_overview_test.rb
- test/integration_test_helper.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
[Trello](https://trello.com/c/GaaZPBIN)
Apply following updates to the Publications index page:
- Reduce the size of the checkboxes in accordance with the design
- Pluralize the number of documents statement correctly
- Update title for filter to 'Title or slug'
- Add thousands comma for number of documents statement
> Publications index page changes

- test/integration/homepage_popular_links_test.rb
HomepagePopularLinksTest is currently a JavascriptIntegrationTest despite having no Javascript required testing. Some of the tests intermittently fail in CI and locally. Converting this will mean the Selenium driver is used and theoretically remove the flakiness
> Convert HomepagePopularLinksTest to an IntegrationTest

- Dockerfile
This is temporary changes to enable us to install mongo tool that has library for mongoexport.
We need mongoexport to copy data we need for mongo to postgres migration
> Install MongoDB tools in container image

- app/controllers/editions_controller.rb
- app/helpers/editions_sidebar_buttons_helper.rb
- app/helpers/tagging_helper.rb
- app/views/editions/secondary_nav_tabs/_tagging.html.erb
- app/views/editions/secondary_nav_tabs/edit_assignee/_edit_assignee.html.erb
- app/views/editions/secondary_nav_tabs/tagging/_summary_card_empty.html.erb
- app/views/editions/secondary_nav_tabs/tagging/_summary_card_full.html.erb
- app/views/editions/secondary_nav_tabs/tagging_mainstream_browse_page.erb
- config/routes.rb
- test/functional/editions_controller_test.rb
- test/integration/edition_edit_test.rb
- test/support/tag_test_helpers.rb
- test/unit/tagging/linkables_test.rb
[Trello](https://trello.com/c/ZuaOlmWO/688-tagging-add-and-edit-data-in-mainstream-browse-pages-summary-card)
We have already added a summary page for tagging. This is located at `/editions/:id/tagging` and displays the four separate sections of tags that can be added. 
This work is concerned with the "Mainstream browse pages" section and adds a new view linked to from the "Tag to a browse page" link when the edition has no tagging already applied. This link should not be rendered to users without the correct permissions.
If the edition does have tagging applied then this section displays those tags and an "Edit" link (also not rendered to users without the correct permissions).
The view that is linked to here shows all the possible pages that can be tagged to as checkboxes, separated …
> Add and Edit data in [Mainstream browse pages] summary card

- Gemfile.lock
The publisher app fails to start with this updated govspeak gem.
This reverts commit 522116b022bedd1e86364bcaebb468e83d13690b, reversing changes made to 7a8838bd38ff51d630356a80eca424d30bbc0175.
> Revert "Merge pull request #2802…"

- app/assets/javascripts/legacy_modules/related_content_items_select.js
- app/controllers/legacy_editions_controller.rb
- app/views/shared/_tagging.html.erb
- test/integration/tagging_test.rb
[Trello](https://trello.com/c/y4G5SwHu/706-tagging-add-and-edit-data-in-related-content-summary-card)
This makes some additional renaming in the legacy controller and associated areas, which was missed in the original PR ([PR#2790](https://github.com/alphagov/publisher/pull/2790)) to implement the tagging for related content. This is necessary because of the creation of a new `UpdateTaggingForm` during that work and the renaming of the existing one to `LegacyUpdateTaggingForm`.
> Tagging refinement

- app/lib/tagging/tagging_update_form.rb
- test/integration/edition_edit_test.rb
PR #2785 removed references to Maslow (via "meets user needs"), but
there were some extra references added between that PR being raised and
then being merged. Delete the extra, unnecessary references.
> Fix tests after Maslow code removal

- .github/workflows/deploy_mongo_to_pg.yml
The deployment is necessary for our final migration to PostgreSQL (from Mongo).
> Enable the deployment of publisher-on-pg app to production environment

- app/helpers/base_helper.rb
- test/functional/legacy_root_controller_test.rb
- test/unit/presenters/filtered_editions_presenter_test.rb
The counts used in the "Filter by status" box in the top left corner of the publications page were incorrectly showing the number of editions in a page rather than the total count when there were more than a page's worth of editions in a state. Update to get the total count instead.
> Update bootstrap UI to use correct counts

- app/controllers/legacy_editions_controller.rb
- app/views/local_transactions/_devolved_administrations.html.erb
- test/integration/local_transaction_create_edit_test.rb
- Type field was previously renamed to 'authority_type' but radio buttons had not been updated to match.
- Added missing test coverage to catch this in future
> Fix saving of local transaction editions

- app/models/simple_smart_answer_edition.rb
- test/models/simple_smart_answer_edition_test.rb
Update the code which copies SimpleSmartAnswerEdition data over when a new edition is created from an existing artefact. 
Prevents the mongo_id from being copied across to new editions as they have never existed in mongo.
> Fix create new edition for simple smart answers

- app/models/local_transaction_edition.rb
- app/models/parted.rb
- test/models/edition_test.rb
- test/models/local_transaction_edition_test.rb
- test/support/factories.rb
- test/unit/edition_duplicator_test.rb
- test/unit/guide_edition_test.rb
- Add tests to ensure that mongo_ids in editions are not copied across when edition is cloned. (New editions do not need a mongo id as they never existed in the mongo db)
- Ensure that mongo ids for parts are not copied over when a guide edition is cloned
- Ensure that mongo ids for devolved administration availabilities are not copied over when a local transaction edition is cloned.
> Fix postgres issues related to dependencies and cloning

- app/controllers/editions_controller.rb
- app/views/editions/secondary_nav_tabs/tagging_remove_breadcrumb_page.html.erb
- test/integration/edition_edit_test.rb
**Jira**: https://gov-uk.atlassian.net/jira/software/c/projects/MAIN/boards/1555?selectedIssue=MAIN-2105
This PR add the validation for remove breadcrumb page when user click on save  button without selecting an option.
**It does the following:**
- Add the validation on save button for remove breadcrumb page to prompt the user to select an option.
- Add the relevant tests
|Existing/updated journey|Current views|Updated views|
|-|-|-|
|Remove breadcrumb page: user clicks on "Save" without selecting an option|<img width="1148" height="433" alt="Screenshot 2025-09-11 at 10 57 14" src="https://github.com/user-attachments/assets/95a104d7-f318-44f6-9f86-c09e98a47a82" />|<img width="1148" height="433" alt="Screenshot 2025-09-11 at 10 57 14" …
> 745 tagging remove breadcrumb validation

- app/models/host_content_update_event/action.rb
- app/views/legacy_editions/_content_block_guidance.html.erb
- test/models/host_content_update_event/action_test.rb
We are moving Content Block Manager to its own app, so we need to update the URLs.
~~I'll leave this in draft until the move is complete.~~
> (CM-441) Update links to new Content Block Manager

- app/controllers/editions_controller.rb
- app/views/editions/secondary_nav_tabs/approve_fact_check_page.html.erb
- app/views/editions/show.html.erb
- config/routes.rb
- test/integration/edition_edit_test.rb
This PR implements the 'Request amendments' (`request_amendments` state action) and the 'No changes needed' (`approve_fact_check` state action) buttons for when an edition is in the `fact_check_received` states, creating a new view for the approve fact check page.
|Scenario|Screenshot|
|-|-|
|Inset text|<img width="1226" height="593" alt="image" src="https://github.com/user-attachments/assets/7ab31e38-df44-4dfc-b742-316f14c6af16" />|
|Approve message|<img width="873" height="630" alt="image" src="https://github.com/user-attachments/assets/9ea96222-cd8c-4251-a54e-2fbabc2d732a" />|
|Success banner|<img width="1186" height="430" alt="image" src="https://github.com/user-attachments/assets/9ffa812f-34df-48c7-a4fc-c0b60d4f0d3a" />|
|Message in history|<img width="624" height="432" alt="image" …
> MAIN-4930 fact check received options

- app/views/editions/secondary_nav_tabs/schedule_page.html.erb
- test/integration/edition_edit_test.rb
[MAIN-4928](https://gov-uk.atlassian.net/browse/MAIN-4928)
This PR changes the scheduled publishing page to dynamically generate a date three months in the future for the hint text, rather than the existing static date
I've followed https://www.gov.uk/guidance/style-guide/a-to-z#dates and other examples on not including padding 0's (i.e. 6 1 2026 rather than 06 01 2026)
[MAIN-4928]: https://gov-uk.atlassian.net/browse/MAIN-4928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAIN-4928 scheduled publishing hint date

- app/views/editions/secondary_nav_tabs/_progress_with_comment.html.erb
- app/views/editions/secondary_nav_tabs/send_to_2i_page.html.erb
[MAIN-4927](https://gov-uk.atlassian.net/jira/software/c/projects/MAIN/boards/1555?selectedIssue=MAIN-4927)
This PR makes sure that the link to the new page in the send to 2i page is properly opening in a new tab by correcting the `progress with comment` component that was stripping the target attribute from the link
[MAIN-4927]: https://gov-uk.atlassian.net/browse/MAIN-4927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAIN-4927 - Send to 2i guidance link in new tab
